### ISSUE TITLE
Add "shared_with_groups" field in Project struct

### ISSUE THREAD

**Issue by the-shank** [xanzy/go-gitlab#101]
In the api docs for [getting a single project](https://docs.gitlab.com/ce/api/projects.html#get-single-project), under the JSON returned for the project, there is a field `shared_with_groups`. I wish to add support for this to the library.
Is it ok if I send a pull request with the required changes?

**Comment by svanharmelen** [comment]
Sure thing... Would be greatly appreciated!

**Comment by the-shank** [comment]
this is strange... I added the following to the `Project` struct in `projects.go`
```go
SharedWithGroups     []struct {
	GroupID          int    `json:"group_id"`
	GroupName        string `json:"group_name"`
	GroupAccessLevel int    `json:"group_access_level"`
} `json:"shared_with_groups"`
```
But in the decoded `Project` object, I am getting and empty []
I will dig in further...

**Comment by the-shank** [comment]
Ah, nevermind, the JSON being returned from the API did not have the `shared_with_groups` field.
I will test for and example in which it does and then update here and send the pull request after testing it
