### ISSUE TITLE
Is there a way to ignore "x509: certificate signed by unknown authority" when trying to login?

### ISSUE THREAD

**Issue by supercom32** [xanzy/go-gitlab#1022]
Hi Everyone,

Is there a way with "go-gitlab" to ignore "x509: certificate signed by unknown authority" errors when trying to login? Since this is a private gitlab server, I'd like to ignore any cert issues if possible. However, I wasn't sure exactly how to go about doing so. I know this package uses "go-retryablehttp" and with that package you can add "InsecureSkipVerify: true" to the transport to ignore cert issues, but I'm not sure if that's exposed here in go-gitlab?

**Comment by svanharmelen** [comment]
You can pass in a custom client that has a transport with the ssl options you want using the WithHTTPClient option func: https://github.com/xanzy/go-gitlab/blob/master/client_options.go#L46

**Comment by supercom32** [comment]
Gee, I can't belive I missed that. :+1: 

Thanks for the clarificataion!
