### ISSUE TITLE
Could jobs.DownloadArtifactsFile return a bytes.Reader instead of an io.Reader

### ISSUE THREAD

**Issue by hartzell** [xanzy/go-gitlab#1023]
I'm not sure how fixed these function signatures are, but it would be very useful if things like `jobs.DownloadArtifactsFile` returned a `bytes.Reader` instead of an `io.Reader` (the thing that is being returned is/was actually a `bytes.Buffer`).

I have a little tool that downloads and unzips the artifacts for a bunch of jobs in a project.  With the current interface I need to create an `ioutil.Tmpfile`, `io.Copy` the zipfile from memory into the temp. file, then pass its name to `zip.OpenReader`.

If `jobs.DownloadArtifactsFile` returned a `bytes.Reader` (or something that implemented `io.ReaderAt` and `len`) then I could use it with `zip.NewReader` and avoid creating the temporary file.

It seems like widening the scope of the returned item shouldn't break current consumers.  I'm not sure if the underlying implementation (reading the response body into the `bytes.buffer) is likely to change.

As it stands right now the API library is doing the least useful thing possible, reading and closing the response so that consumers can't use it but the only passing back an `io.Reader`

**Comment by svanharmelen** [comment]
The underlying implementation is not going to change any time soon. The patterns is perfect for all API calls where there is a 1-to-1 request and response. Only for the kind of calls where the response is actually a file or an archive it's a less good fit. But since that are only a few calls, I would like to keep it like this.

Yet I'm open to updating the response type to `bytes.Reader` if that makes things better/easier. I can see how that can be helpful at zero or no additional costs. So by all means open a PR for that...

**Comment by hartzell** [comment]
Thanks for the feedback.  It looks like there are only 4 cases (`GetJobArtifacts`, `DownloadArtifactsFile`, `DownloadSingleArtifactsFile`, `GetTraceFile`) that use this pattern.

I can see arguments for:

- returning the underlying `bytes.Buffer`, because it's what's really being used and you see the implementation being stable;
- returning `[]byte`, because that's what's returned from the very common "read the data from the response body" pattern:
  ```
   body, err := ioutil.ReadAll(resp.Body)
   ```
- returning a `bytes.Reader`, because that's an easily accessible abstraction that doesn't expose the underlying implementation (plus it directly addresses my use case :wink:).

Do you have a preference or recommendation?

**Comment by svanharmelen** [comment]
I prefer the last option... 👍🏻
