### ISSUE TITLE
Merge Request-level MR approvals support

### ISSUE THREAD

**Issue by ecornelisse** [xanzy/go-gitlab#1028]
There is no support for all mr approval rule endpoints in this package as far as i can see. Is there any chance that this will be supported soon?

The documentation about those endpoints can be found here: https://docs.gitlab.com/ee/api/merge_request_approvals.html#merge-request-level-mr-approvals

**Comment by svanharmelen** [comment]
I think most of them are implemented: https://github.com/xanzy/go-gitlab/blob/feature/authentication/merge_request_approvals.go Anything specific that you are missing?

**Comment by svanharmelen** [comment]
@ecornelisse can you elaborate what you are missing? If not I suggest we close this issue again...

**Comment by akfaew** [comment]
Can someone please confirm that `GetMergeRequestApprovals()` still works for gitlab.com, after the recent update, if there are two or more approvers?

**Comment by svanharmelen** [comment]
Closing due to no response and my impression that this is already supported. Feel free to reopen if you have concrete examples of what is missing.
