### ISSUE TITLE
add support for group/project invitations api

### ISSUE THREAD

**Issue by calebwashburn** [xanzy/go-gitlab#1029]
Looking for ability to leverage invitations api https://docs.gitlab.com/ee/api/invitations.html#invite-by-email-to-group-or-project

**Comment by svanharmelen** [comment]
Does seem to be supported by this package yet, but open to merge a PR for it if your up for that...

**Comment by framled** [comment]
I'm working for a PR for this.

**Comment by Bouwdie** [comment]
@svanharmelen this has a closed mr - I guess we can close this?

**Comment by svanharmelen** [comment]
Yes, seems so. Thanks for the ping 👍🏻
