### ISSUE TITLE
How to get tags count of a repository

### ISSUE THREAD

**Issue by owykui** [xanzy/go-gitlab#1057]
Some attempts:
1. Projects api: get a project, the tag_list in the response is empty
2. Tags api: list tags with ListOptions only each page most 100, and can not list all

Since the gitlab "Project overview" page having a tags count, is there any way to get the number?

**Comment by svanharmelen** [comment]
The response should have a `TotalItems` field that you can use for this: https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L557

**Comment by owykui** [comment]
Thank you so much,  it takes effect. Perfect!👏
