### ISSUE TITLE
Provide a factory function for FileAction

### ISSUE THREAD

**Issue by ahuret** [xanzy/go-gitlab#1063]
Hi !

While using commits api, type `FileAction` is required to provide `Action` to `CommitActionOptions`.
Action ask for `*FileAction` while vars FileCreate/FileDelete/FileMove/FileUpdate returns `FileAction`.
In practice, it means we have to declare a new variable, then use this variable pointer as parameter like below :

```go
fa := gitlab.FileCreate
ca := gitlab.CommitActionOptions{Action: &fa}
```

I propose to add a factory function like `String(v string) *string` `Bool(v string) *string` to get better developper experience.
I was thinking of `NewFileAction(v FileAction) *FileAction` but it would break the naming convention.
`FileAction(v FileAction) *FileAction` is not possible cause of conflict with type name.

Any idea how to handle this properly ?

**Comment by svanharmelen** [comment]
Following the convention would mean a breaking change. But to be honest, I think I'm OK with that... So in that case the `FileAction` type should be renamed to `FileActionValue` and a new function like `FileAction(v FileActionValue) *FileActionValue` can then be added as a helper function... What do you think?

**Comment by ahuret** [comment]
What about `CommitFileAction` ?

**Comment by ahuret** [comment]
Let's deal with it. Gonna propose a PR.
