### ISSUE TITLE
List a group's projects

### ISSUE THREAD

**Issue by biancalana** [xanzy/go-gitlab#107]
I can' find method to list group' projects (https://docs.gitlab.com/ce/api/groups.html#list-a-group-s-projects) is this implemented ?

**Comment by mustafayildirim** [comment]
@svanharmelen 
I can implement. Do you want?

**Comment by svanharmelen** [comment]
@biancalana it seems that one is not implemented yet, but it should be pretty straight forward to add it though...

@mustafayildirim that would be much appreciated of course 👍

**Comment by biancalana** [comment]
@mustafayildirim @svanharmelen what do you think about #110 ?

**Comment by svanharmelen** [comment]
Fixed by PR #110
