### ISSUE TITLE
Set cleanup policy for container tags

### ISSUE THREAD

**Issue by oschrenk** [xanzy/go-gitlab#1072]
Does the project currently support setting the cleanup policy for container tags? 

See https://docs.gitlab.com/ee/user/packages/container_registry/#use-the-cleanup-policy-api

**Comment by svanharmelen** [comment]
No, I don't think so.

**Comment by armsnyder** [comment]
It looks like we would need to add a `ContainerExpirationPolicyAttributes` field to the `Project` struct.

Here's the API reference: https://docs.gitlab.com/ee/api/projects.html#create-project

**Comment by pkostohrys** [comment]
I would take this , @svanharmelen

**Comment by svanharmelen** [comment]
All yours @pkostohrys, as long as you make sure to follow the style I showed in your last PR 👍🏻

**Comment by pkostohrys** [comment]
As i can see it is already here , [https://github.com/xanzy/go-gitlab/blob/master/projects.go#L575](url)

**Comment by svanharmelen** [comment]
Yup, indeed 👍🏻  So then I'll just go ahead and close this one...
