### ISSUE TITLE
[BUG] Get Raw File With dot  return  file not found

### ISSUE THREAD

**Issue by Just-maple** [xanzy/go-gitlab#1075]
here should use  `pathEscape` to parse `.` to `%2E`

not so some filename(most of normally) with `.` will return file not found 

[gitlab doc](https://docs.gitlab.com/ce/api/repository_files.html#get-raw-file-from-repository)

#1074

**Comment by svanharmelen** [comment]
No need to create an issue if you already created a PR 👍🏻
