### ISSUE TITLE
Issue event struct out of date?

### ISSUE THREAD

**Issue by mvdan** [xanzy/go-gitlab#108]
Seeing this when unmarhsaling a webhook into `IssueEvent`:

```
json: cannot unmarshal string into Go struct field Project.namespace of type gitlab.ProjectNamespace
```

**Comment by mvdan** [comment]
This is the problematic one:

```
type Project struct {
    [...]
    Namespace                     *ProjectNamespace    `json:"namespace"`
```

I commented it out for now to avoid the error, since I don't use the field anyway. The error seems to indicate that this is a string in the json body.

The gitlab webhook docs seem to agree with this error:

```
    "namespace":"GitlabHQ",
```

**Comment by svanharmelen** [comment]
Thanks @mvdan, seen this before with the PipelineEvent so now fixed/updated for all event structs...

**Comment by mvdan** [comment]
Awesome, thanks!

Perhaps all of these anonymous structs should be a separate type, with a `TODO` to merge back into the regular `Project` struct at some point?

**Comment by svanharmelen** [comment]
Yeah, that would indeed also be a good option as they are now all the same (only different from the currently existing `Project` struct). Not going to do that right now, but if you're up for it a PR is of course welcome :wink:
