### ISSUE TITLE
ListMergeLabelEvents should be ListMergeRequestsLabelEvents

### ISSUE THREAD

**Issue by gravis** [xanzy/go-gitlab#1080]
The name is not consistent with the rest of the API. But updating it will be a breaking change, so before creating a pull request, I'd like to have some insights.  
We can also create an "alias" to have the right name, and keep the other one for retro compatibility.

**Comment by svanharmelen** [comment]
I'm good with fixing this. Seems like a super minor breaking change, so good to make it consistent.
