### ISSUE TITLE
add WIP to ListGroupMergeRequestsOptions as well

### ISSUE THREAD

**Issue by fonsecas72** [xanzy/go-gitlab#1083]
As per documented, i believe we are missing the WIP field from ListGroupMergeRequestsOptions 

https://docs.gitlab.com/ee/api/merge_requests.html

**Comment by svanharmelen** [comment]
Do you mean this one: https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L167

**Comment by fonsecas72** [comment]
no, this one https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L197

**Comment by fonsecas72** [comment]
not sure why the documentation is missing. it works

**Comment by fonsecas72** [comment]
awesome!! many thanks 🙇
