### ISSUE TITLE
ErrorResponse is parsing validation errors and return a corrupt content instead

### ISSUE THREAD

**Issue by brodock** [xanzy/go-gitlab#1091]
When looking at an ErrorResponse content, I have this in the body:

```
{"message":{"name":["has already been taken"],"path":["has already been taken"],"limit_reached":[]}}
```

and that is being parsed in `Message` as:

```
{message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}
```

This is not useful, as the syntax went from : Hash<Hash> to something we can't parse with JSON because the syntax is invalid.

The mistake is in here: https://github.com/xanzy/go-gitlab/blob/4fe716571a964ae37a21b28d99fd7dc28bf29b2b/gitlab.go#L797

**Comment by svanharmelen** [comment]
I get your point, but the parsed error is not meant to be parsable as valid JSON. Instead it's meant to be human readable. Not saying we cannot see if we can change or improve that, but just saying it was designed to return valid JSON.

**Comment by svanharmelen** [comment]
Looking a bit further, it uses that code path if it failed to unmarshal the error to the `ErrorResponse` struct. So this is actually used as a fallback solution to be able to show something useful. The full response body is still available in `ErrorResponse.Body` so you can use that directly if you desire to parse the response in a different way.

**Comment by brodock** [comment]
That makes sense. I've realized later on I could get the original from the
Body.

Would you think it makes sense to try to create a slightly different
structure to parse validation errors like this one?

I guess my initial goal was to have them not all in Message flattened out.

At least I see one important improvement here. We know this is about the
"message", so we can omit that when parsing and just show the content
inside it.

My more broad proposal would be to extract all fields and their messages to
something like `ValidationErrors` and have a fallback message as
"validation errors" when the API doesn't return the "error" Key.

WDYT?

Em sáb, 6 de mar de 2021 10:51, Sander van Harmelen <
notifications@github.com> escreveu:

**Comment by svanharmelen** [comment]
Let's leave it as it is for now. I think the current flattened format also has its uses and like we discussed, you can always get the raw data yourself if this format doesn't suite you.

I'll close this issue, but feel free to reopen it if you want to continue the discussion.
