### ISSUE TITLE
Support publishing and downloading generic packages

### ISSUE THREAD

**Issue by sirlatrom** [xanzy/go-gitlab#1100]
There are no separate API docs, but the API endpoints are documented here: https://docs.gitlab.com/ee/user/packages/generic_packages/

**Comment by sirlatrom** [comment]
@svanharmelen What is your opinion on adding a non-API function to GenericPackagesService (added in this PR in the first place) which gives you the API download URL for a generic package? Or should other users of the library figure that out on their own after publishing a generic package? I'm specifically trying to add that for goreleaser/goreleaser#2006.

**Comment by svanharmelen** [comment]
Go for it 👍🏻 I'm open to merging that PR when you finish it 😃
