### ISSUE TITLE
Not all response fields returning correct for some search and list functions. 

### ISSUE THREAD

**Issue by finn-ball** [xanzy/go-gitlab#1111]
Try playing around with this search. I've also tried this with `Search.MergeRequestsByGroup` and get the same result. I can't seem to get it working with pages. Roughly, if you look at this:

```go
git, _ := gitlab.NewClient(token, gitlab.WithBaseURL(url))

options := gitlab.SearchOptions{
  PerPage: 1,
}

# Assuming "foo" matches more than one MR.
mrs, resp, err := git.Search.MergeRequests("foo", &options)
if err != nil {
    return nil, err
}

for resp.CurrentPage > 0 {
    fmt.Println(resp.NextPage)
    fmt.Println(resp.CurrentPage)
    fmt.Println(resp.PreviousPage)
    fmt.Println(resp.TotalPages)
    fmt.Println(options)

    req, resp, err := git.Search.MergeRequests(query, &options)
    if err != nil {
        return nil, err
    }
    mrs = append(mrs, req...)
    options.Page = resp.NextPage
}

fmt.Println(mrs)
```

No matter what I do, `TotalPages` is always 0. The `CurrentPage` and `PreviousPage` never change in value. Can you reproduce something like this?

**Comment by szucsitg** [comment]
I run into the same issue with commits, my simplified workaround was this, I hope that helps:
```go
projectID := 1
opt := &gitlab.ListCommitsOptions{
	ListOptions: gitlab.ListOptions{
		Page:    1,
		PerPage: itemsPerPage,
	},
}

nextPage := true
for nextPage {
	commits, _, _ := CommitService.ListCommits(projectID, opt)
	if len(commits) == itemsPerPage {
		opt.Page++
	} else {
		nextPage = false
	}
}
```

**Comment by finn-ball** [comment]
Any idea what is causing this?

**Comment by finn-ball** [comment]
@szucsitg - thanks for your suggestion, it did help. I should have started my page at 0 and had looked at the `NextPage` field. I can offer a slightly better suggestion.
```go
projectID := 1
opt := &gitlab.ListCommitsOptions{
	ListOptions: gitlab.ListOptions{
		Page:    1,
		PerPage: itemsPerPage,
	},
}

commits, resp, _ := CommitService.ListCommits(projectID, opt)

nextPage := resp.NextPage
for nextPage > 0 {
	commits, resp, _ = CommitService.ListCommits(projectID, opt)
	options.Page++
	next_page = resp.NextPage
}
```

I still think some of these fields are broken. So I'll amend the issue title accordingly.

**Comment by szucsitg** [comment]
Thanks for the suggestion, I think I originally had similar, I need to retest yours. IIRC if there's no more than 1 page of results, it'll result an infinite loop, but I might used another field from resp.

**Comment by finn-ball** [comment]
I tried it for the merge request example I originally sent and it worked for that. The result is that `NextPage` is set to 0, so long as the `Page` is set to 1 in the first instance :)

Quick question though, have you figured out how to get the `query` parameter in the search working? I'm unable to search by `state=opened`. It doesn't yield any results. Though if I do a dumb, `foo`, it'll return anything where it had `foo` in the title.

**Comment by alex1989hu** [comment]
For `Commits API` I found that `GitLab v13.5` removed headers related to pagination from response: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/43159 - so this behaviour for `Commits API` is not `go-gitab` library issue.

@finn-ball you can check your API call: whether contains pagination headers or not.

**Comment by finn-ball** [comment]
You're right, closing now.
