### ISSUE TITLE
Declare 'Variables' field as subfield of ObjectAttributes in PipelineEvent struct

### ISSUE THREAD

**Issue by cgrime01** [xanzy/go-gitlab#1120]
Per https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#pipeline-events, webhook pipeline events are have a `variables` field in `object_attributes`, so the PipelineEvent struct seems to need a similar field, e.g.:

type PipelineEvent struct {
    …
    ObjectAttributes struct {
	…
	Variables []map[string]string   `json:”variables"`
	…

**Comment by svanharmelen** [comment]
Feel free to create a PR for that 👍🏻

**Comment by M0roSan** [comment]
I took this issue and open the MR above. instead of slice of map, I use slice of struct
