### ISSUE TITLE
Can't create an empty commit

### ISSUE THREAD

**Issue by didroe** [xanzy/go-gitlab#1123]
It's not possible to create an empty commit with the `go-gitlab` client. 

This is because `actions` is required by the API but it's [marked](https://github.com/xanzy/go-gitlab/blob/85dd177da2c0ae094687e9b550dda5b52ebb0e28/commits.go#L188) as `omitempty`, so an empty array can't be sent.

**Comment by svanharmelen** [comment]
Guess we should remove the `omitempty` from that particular field then...

**Comment by didroe** [comment]
Cool. I'll create a PR
