### ISSUE TITLE
GitLab GraphQL support

### ISSUE THREAD

**Issue by bmeneguele** [xanzy/go-gitlab#1129]
Hi all,

are there any plans to start supporting the [GitLab GraphQL API](https://docs.gitlab.com/ee/api/graphql/) any time soon?
Or is it not a plan for go-gitlab module in particular?

**Comment by svanharmelen** [comment]
Hi @bmeneguele, there are no plans whatsoever to support the GraphQL API with this package.

**Comment by davidferlay** [comment]
Would you be open to PR for it anyways ?

**Comment by svanharmelen** [comment]
No, sorry... GraphQL is something completely different and should (IMHO) not be added in this package.

**Comment by mitar** [comment]
Given that GitLab is adding to GraphQL features which are only available through GraphQL, I think it would be great if this package served as an abstraction so that end-users of this package would not have to care about what type of API calls are being made. It could serve as an abstraction to unify APIs from GitLab.

**Comment by Jitsusama** [comment]
> Given that GitLab is adding to GraphQL features which are only available through GraphQL, I think it would be great if this package served as an abstraction so that end-users of this package would not have to care about what type of API calls are being made. It could serve as an abstraction to unify APIs from GitLab.

I second this. For modifying user profile details, I believe the GraphQL API is the only way that opens up doing this for your own account when you are not an admin user. I appreciate that it would be a big deviance from how things are currently structured in this code base, but I do think it would provide value.
