### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by willianpaixao** [xanzy/go-gitlab#1136]
Hi!

When looking for what was added, changed, deprecated, or removed in each version of the library is kinda hard. A very common solution and widely adopted is a simple Markdown file called `CHANGELOG.md` in the root of this repository.

[Keep a Changelog](https://keepachangelog.com/en/0.3.0/) is a very good how-to and template to start.

Additionally, the same text of a version could be copied to a [Github release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) for quick reference, while the `CHANGELOG.md` would contain and accumulate the information across versions.

Since there are a few versions of the library already released, my suggestion would simply to start the Changelog from the next tag. 

Here are a few examples:

- [github.com/gitlabhq/terraform-provider-gitlab](https://github.com/gitlabhq/terraform-provider-gitlab/blob/master/CHANGELOG.md)
- [github.com/hashicorp/consul](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md)
- [github.com/kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md)

**Comment by svanharmelen** [comment]
I hear you and I actually fully agree this would be a very nice addition to the project, yet I hardly have time to keep up with the issues and PR's as it is (next to my day job that is), so I'm not going to commit to adding and maintaining a changelog on top of that. Sorry!
