### ISSUE TITLE
new version release

### ISSUE THREAD

**Issue by bmeneguele** [xanzy/go-gitlab#1139]
Hi all,

I would like to know if there is an ETA for the next release of the module.
I'm asking it because the project I'm working on ([lab](https://github.com/zaquestion/lab)) is waiting on two features added recently: https://github.com/xanzy/go-gitlab/pull/1121 and https://github.com/xanzy/go-gitlab/pull/1130, to release a new version for the users.

Thanks in advance!

**Comment by svanharmelen** [comment]
Added tag `v0.49.0` 👍🏻

**Comment by svanharmelen** [comment]
Thanks for the feedback... That's what you get from adding a tag from your phone 🙈 

Should be fixed now!
