### ISSUE TITLE
when send a request with array params, which can not be parsed correctly

### ISSUE THREAD

**Issue by woody712** [xanzy/go-gitlab#1151]
For example the struct like "ListMilestonesOptions", there is a key 'iids' in this struct, when I send a request, and the params will be encoded like this "iids=xxx&iids=xxx". which will not be parsed  correctly by Gitlab.

I have some tests in postman, when I change the URL like "iids[]=xxx&iids[]=xxx", it will be parsed  correctly.

my Gitlab version is 14.14.29, hope fix it quickly

**Comment by svanharmelen** [comment]
It turned out we missed a couple of these, but should fixed by PR #1166  👍🏻
