### ISSUE TITLE
Search blobs by ref

### ISSUE THREAD

**Issue by f-sys** [xanzy/go-gitlab#1158]
In project search API (https://docs.gitlab.com/ee/api/search.html#project-search-api) is a value `ref` described as: `The name of a repository branch or tag to search on. The project’s default branch is used by default. This is only applicable for scopes: commits, blobs, and wiki_blobs.`

But in go-gitlab it is missing in all three scopes.

**Comment by svanharmelen** [comment]
Can you clarify or give an example/link that shows what you expect?

**Comment by f-sys** [comment]
In Gitlab api example (https://docs.gitlab.com/ee/api/search.html#scope-blobs-premium-2), there is `ref` as a parameter:
`curl --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/6/search?scope=blobs&search=installation&ref=feature"`

It is missing in api, I can't just write
```
cli, _ := gitlab.NewClient("<your_access_token>", gitlab.WithBaseURL("https://gitlab.example.com"))
ret, resp, err := cli.Search.BlobsByProject(6, "installation", &gitlab.SearchOptions{Ref: "feature"})
```
because there is not a `Ref` option in `SearchOption` structure.

**Comment by svanharmelen** [comment]
Would PR #1162 be a proper fix? Don't know if you can test it by using that branch?

**Comment by f-sys** [comment]
Yes, it works.

**Comment by svanharmelen** [comment]
Thanks for checking 👍🏻
