### ISSUE TITLE
Inconsistent Users type structures for Webhook events

### ISSUE THREAD

**Issue by wizzardich** [xanzy/go-gitlab#1164]
## Problem Description

Type definitions for Webhook events are not consistent in treatment of the Users data that the webhook represents. While some webhook events represent a user as a struct with one set of fields (e.g. [pipeline events][pipeline-event-user]):

```go
User struct {  
    Name      string `json:"name"`
    Username  string `json:"username"`
    AvatarURL string `json:"avatar_url"`
}  `json:"user"`
```

other events represent them as a struct with another set of fields (e.g. [job/build events][job-event-user]):

```go
User struct {
    ID    int    `json:"id"`
    Name  string `json:"name"`
    Email string `json:"email"`
} `json:"user"`
```

while yet other events just refer to a predefined User API object (e.g. [merge events][merge-event-user]):

```go
User       *User  `json:"user"`
```

This leads to confusion and inconvenience while using the library, especially operating under assumption that webhooks translate one-to-one from an incoming JSON to a golang object. The description given in the [official documentation][1] actually is fairly consistent throughout my tests with the struct format of 

```go
User struct {
    ID        int    `json:"id"`
    Name      string `json:"name"`
    Email     string `json:"email"`
    Username  string `json:"username"`
    AvatarURL string `json:"avatar_url"`
}
```

## Purpose

Introducing consistency with GitLab webhook API implementation and consistency within this library's own type system.

## Conclusion

It also seems like `Users` `struct` is not the only such an inconsistent occurrence within the webhook types; seems like, for example, `Project` could benefit from a similar refactor.

That said, I'm perfectly willing to take a stab at trying to improve the library - I personally enjoy using it very much, there's been some great work done here! A big thank you to the maintainers for an amazing job on the project!

[1]: https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#pipeline-events
[2]: https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#merge-request-events
[merge-event-user]: https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go#L470
[pipeline-event-user]: https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go#L670
[job-event-user]: https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go#L335

**Comment by svanharmelen** [comment]
I personally love consistency, but with 321 contributors that's sometimes quite a challenging 😉 I do know that previously a `User` in an event was not always similar to a Gitlab `User` (field wise), but if they improved that now I'm all for making it more consistent. So if your up for it... Go for it 👍🏻

**Comment by wizzardich** [comment]
In their documentation GitLab unfortunately do not have a proper documentation on webhook structure, just examples. I did test on both gitlab.com as well as self-hosted GitLab though, and only observed webhooks which are in line with the updates that are present in the PR.

Also, yes, I get why the inconsistency is there, with that many contributors! That's a great point :D
