### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by lyda** [xanzy/go-gitlab#117]
This might be something people more used to REST wrappers know, but for me the [Response](https://godoc.org/github.com/xanzy/go-gitlab#Response) docs are incomplete. What is the behaviour of `NextPage`? Should I assume there's more data if `NextPage` is not zero?

Also the GitLab [pagination](http://docs.gitlab.com/ce/api/README.html#pagination) docs indicate there's also `X-Page` and `X-Total-Pages` headers sent back. Would it be helpful to include them?

I note that the GitHub API does not have such fields so perhaps you're trying to stay similar to theirs?

If not, might it be an idea to make iterators that hide the pagination?

**Comment by jangrewe** [comment]
Yes, i just got bitten by this, too. How can this be handled?

**Comment by jakubknejzlik** [comment]
Assuming from this source code:
https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L428

The XPage is populated from `Link` header which is in format:
```
<https://git.example.com/api/v4/users?active=false&blocked=false&external=false&page=1&per_page=20>; rel="prev",
...
```
So if theres no such link with `rel="next"` the NextPage *should* be 0.

**Comment by Lorac** [comment]
@svanharmelen I guess we could close this one?

**Comment by svanharmelen** [comment]
I agree... I'll close this one for now. Of course it can be reopened or a new issue can be opened if any additional questions pop up. Thx!
