### ISSUE TITLE
Export not found project

### ISSUE THREAD

**Issue by omar26begue** [xanzy/go-gitlab#1170]
Hello, I am using the library to interact with Gitlab but when I go to download the repository files it gives me this error, if someone could help me

Thanks

![image](https://user-images.githubusercontent.com/32799806/122853934-f9c6e180-d2e0-11eb-8d78-e6cf3a77340d.png)

![image](https://user-images.githubusercontent.com/32799806/122937106-b2237280-d33f-11eb-85c4-5297c162a490.png)

When I run this method it returns this to me

https://gitlab.com/api/v4/projects/26975042/export

{"id":26975042,"description":"","name":"template-technique-java-springboot","name_with_namespace":"cli-project / template-technique-java-springboot","path":"template-technique-java-springboot","path_with_namespace":"proyectos/template-technique-java-springboot","created_at":"2021-05-27T18:28:38.369Z","export_status":"none"}

**Comment by svanharmelen** [comment]
Are your credentials correct for that project? I.e. does it have the correct permissions?

**Comment by omar26begue** [comment]
> ¿Son correctas sus credenciales para ese proyecto? Es decir, ¿tiene los permisos correctos?

Where you can verify these permissions, however that same user is the creator of that repository

**Comment by svanharmelen** [comment]
Hey... Did you manage to solve this, or it this still an issue?

**Comment by svanharmelen** [comment]
I'm going to close this due to no response and no way to reproduce.
