### ISSUE TITLE
Add support for refresh_token when create client

### ISSUE THREAD

**Issue by linneawang** [xanzy/go-gitlab#1172]
in the current interface: 
NewXXXClient(token string, ... Options)

it only takes in access_token as first parameter, we need to support refresh_token in the Client as well (like in form of oauth2.Token) so that the long-lasting Client works properly.

please advise how to achieve that if we've already done so.

**Comment by svanharmelen** [comment]
Hi @linneawang, I'm not sure what you want to achieve? What kind of token would you like to use (where and how did you create the token)?

**Comment by linneawang** [comment]
@svanharmelen thanks for your reply!  

I'm using golang/oauth2 to do oauth2 authentication with gitlab.com (OAuth2.1, Chapter 4.1 Authorization Code Grant). so when flow finishes, I get both access_token and refresh_token from Gitlab. What I want to do is create new gitlab.Client with both access_token  *and* refresh_token, so that when the access_token is outdated, gitlab.Client could renew it automatically.

**Comment by svanharmelen** [comment]
I'm afraid that is currently not (yet) supported by this package.

We do have a `NewBasicAuthClient` method which takes a username and password which are then used to get an OAuth token. When the OAuth token expires, it will use the same username and password again to request a new token.

Not sure if that could be a solution for your setup?

**Comment by svanharmelen** [comment]
Hi @linneawang, did using `NewBasicAuthClient` work out?

**Comment by svanharmelen** [comment]
Closing this issue due to no response.

**Comment by akfaew** [comment]
I think that I have the same issue. It seems that GitLab introduced an expiry date for AccessTokens, and my app no longer works. Is it possible to use Refresh Tokens with go-gitlab to refresh an AccessToken?

**Comment by dsanader** [comment]
Yep, you can't have permanent tokens anymore : https://docs.gitlab.com/ee/integration/oauth_provider.html#access-token-expiration
