### ISSUE TITLE
Add Support for Merge Results

### ISSUE THREAD

**Issue by Alfredo-Moreira** [xanzy/go-gitlab#1185]
Please add support for 

Projects -> General Settings -> Merge Options -> Merge Result pipelines and Merge Trains
![Screen Shot 2021-07-30 at 11 21 56 AM](https://user-images.githubusercontent.com/11844106/127691170-c33b3694-7857-4dd6-9137-803cdcf0ff68.png)

**Comment by svanharmelen** [comment]
Closing this issue as this is not currently supported by the GitLab API. Once (if) support is added in the future we can look at this one again...
