### ISSUE TITLE
July release?

### ISSUE THREAD

**Issue by prarit** [xanzy/go-gitlab#1186]
Just curious if there is going to be a release anytime soon?  I've noticed that the releases are approximately a month apart and there hasn't been one for July 2021.  I need a8ebc2ffcde1 ("Add commit_id field") in a release to implement commit commenting in the [lab](https://github.com/zaquestion/lab) project.

**Comment by svanharmelen** [comment]
Done... I don't follow a predefined schedule but just release every now and then 😉

**Comment by svanharmelen** [comment]
No worries! All good 👍🏻
