### ISSUE TITLE
How to handle pagination?

### ISSUE THREAD

**Issue by clns** [xanzy/go-gitlab#12]
I'm sorry but I can't seem to find how to handle pagination. I see the `ListOptions` type but for example I can't use it for `ListAllProjects()`. Maybe I'm missing something.

**Comment by svanharmelen** [comment]
@clns I must admit I didn't test to much with that part, so it can very well not work as expected. I will try to free up some time to look into this one, but in the mean time I would happily review any PR's :wink:

**Comment by clns** [comment]
Actually I don't think pagination is implemented at all, apart from the [`Response`](https://godoc.org/github.com/xanzy/go-gitlab#Response) type which indeed parses `PrevPage`, `NextPage`, `FirstPage` and `LastPage`.

The [`ListOptions`](https://godoc.org/github.com/xanzy/go-gitlab#ListOptions) type is not used anywhere. I think it was meant to be an anonymous field on the other List methods, but it's not.

For now I used a quick and dirty approach and re-submit the same request with `Client.Do()`, which obviously is very ugly. I'll try to make some time to submit a PR, for the moment I can't.

**Comment by svanharmelen** [comment]
Thanks for the feedback! When time permits I'll also try to have a look...

**Comment by svanharmelen** [comment]
It seems @difro already fixed this for a couple of API calls in PR #14, so it should be trivial to fix other API call using the same logic...

Still no time on my hands, but it seems the solution is pretty straight forward and simple now.
