### ISSUE TITLE
Search Namespaces Deprecated?

### ISSUE THREAD

**Issue by Urento** [xanzy/go-gitlab#1205]
The Search Namespaces is not in the Docs anymore (https://docs.gitlab.com/ee/api/namespaces.html) and should maybe get deprecated 

https://github.com/xanzy/go-gitlab/blob/5f216031d9ef0581f96286a5ec48d086c1833868/namespaces.go#L80

**Comment by Urento** [comment]
Its in the Docs from Version 13.12

https://docs.gitlab.com/13.12/ee/api/geo_nodes.html

I added Tests for all of the Functions in the Namespaces in the #1206 Pull Request

**Comment by svanharmelen** [comment]
I would say leave it as it for now. Thanks 👍🏻
