### ISSUE TITLE
Create thread instead of comment

### ISSUE THREAD

**Issue by kniec** [xanzy/go-gitlab#1209]
When adding a note to a MR I can also make this a `thread` which is showing as something that needs to be resolved before the MR will go through.
I can not find this in the Gitlab API documentation...? Any idea how that would be used?
<img width="978" alt="Screenshot 2021-09-09 at 13 40 20" src="https://user-images.githubusercontent.com/53055915/132679377-b2b05d41-c32c-4a5a-be10-161e2238a7a6.png">

**Comment by svanharmelen** [comment]
If it's not in the API docs, then it's not (yet) something that we can use programmatically I guess.

**Comment by svanharmelen** [comment]
Is that what you are looking for: https://docs.gitlab.com/ee/api/discussions.html#create-new-issue-thread

**Comment by kniec** [comment]
Ah, I guess it is more that:

**Comment by svanharmelen** [comment]
Yeah, they are all the same thing but for different entities. Guess those thread related endpoint or not implemented yet. Always open for PRs, but I don't have time for it myself...

**Comment by kniec** [comment]
ok, you got me hooked, I am going to hack together a cli (like [this](https://github.com/plouc/go-gitlab-client)) for my CI/CD pipeline: 
And I really would love to have threads added to MR instead of just comments.

**Comment by Bouwdie** [comment]
@kniec  @svanharmelen  is this issue still relevant? If i look at the implementation and the documentation the discussions functionality brings threads right?

**Comment by ChristianKniep** [comment]
Look like it with this: https://github.com/xanzy/go-gitlab/blob/master/discussions.go
I'll give it a spin - thanks!

**Comment by svanharmelen** [comment]
Did you have a change to test this @ChristianKniep? Would be nice if we can close this one.

**Comment by 2785** [comment]
just passing by but can confirm this works as expected. When you use the discussion API to make a discussion (not attached to lines of code) on a merge request it makes an "unresolved" discussion. 

Unrelated, but things like "person assigned this MR to <@person>" is apparently also a `discussion` entity & the discussion entity is _not_ an "individual note" unless it's one of those "person assigned this MR to person" things...

**Comment by svanharmelen** [comment]
Thanks for confirming! For now I'm to close this one... Feel free to open a new issue if any of the other finding you mentioned causes any issues.
