### ISSUE TITLE
Notification settings API

### ISSUE THREAD

**Issue by sindrepm** [xanzy/go-gitlab#123]
In Gitlab 8.12, the [notification settings](https://docs.gitlab.com/ce/api/notification_settings.html) feature was introduced, allowing a user to set email notification preferences globally or at project/group level.

Are there any immediate plans or work in progress to add this functionality to `go-gitlab`? If not I will be happy to contribute.

**Comment by svanharmelen** [comment]
No, there is no work in progress for the notification API... Off course a PR is much appreciated :wink:

**Comment by sindrepm** [comment]
@svanharmelen Alright! I'll have a look at this shortly.

**Comment by sindrepm** [comment]
@svanharmelen MR ready: #124 
Please review and let me know what you think. It should be a complete implementation of https://docs.gitlab.com/ce/api/notification_settings.html.

**Comment by svanharmelen** [comment]
Fixed by your PR #124 topped of with a little refactoring in PR #130
