### ISSUE TITLE
Pagination stopped working with gitlab.com Groups.ListGroupProjects

### ISSUE THREAD

**Issue by gabrie30** [xanzy/go-gitlab#1234]
Using the following example client/options

```go
client, err = gitlab.NewClient(token)
opts := &gitlab.ListGroupProjectsOptions{
    ListOptions: gitlab.ListOptions{
	    PerPage: 20,
	    Page:    1,
    },
    IncludeSubgroups: gitlab.Bool(true),
}

client.Groups.ListGroupProjects("gitlab-org", opts)
```

To get projects from here https://gitlab.com/gitlab-org

Will not properly paginate `response.TotalPages` returns 0

**Comment by gabrie30** [comment]
Thanks, the work around I used was to check NextPage. 

```go
if resp.NextPage == 0 {
	break
}
```

They might need to update their pagination example https://github.com/xanzy/go-gitlab/blob/master/examples/pagination.go

**Comment by svanharmelen** [comment]
Thanks for letting me know, in that case I will close this issue 👍🏻
