### ISSUE TITLE
Private Domain

### ISSUE THREAD

**Issue by mztikz** [xanzy/go-gitlab#1240]
Hey, 
There is no option to overwrite the base url with different base url for private domain,
I tried to fix it and open merge request but had no permission to push my branch.

simple example for usecase:
if company uses gitlab.google.com , this package does not support it .

If you can simply expose the setBaseURL method as public that will be good enough to overwrite the existing one,
Thanks in advanced.

**Comment by svanharmelen** [comment]
This already exists: https://github.com/xanzy/go-gitlab/blob/master/client_options.go#L29

Additionally if you want to make a PR, it is common to fork the repo, create a branch and the make a PR from your fork to this repo. But in this case the functionality you want already exists.
