### ISSUE TITLE
panic: json: cannot unmarshal string into Go struct field LinePosition.notes.position.line_range.start.old_line of type int

### ISSUE THREAD

**Issue by wynla** [xanzy/go-gitlab#1265]
Create new merge request thread

**Comment by svanharmelen** [comment]
Is this still an issue? If so, then please provide a bit more info (response/error/GitLab version). If not I'm going to close this issue. Thanks.

**Comment by svanharmelen** [comment]
Closing as stale... Feel free to reopen in the future if applicable.
