### ISSUE TITLE
Jobs have some missing fields while coming from List Runner Jobs API endpoint

### ISSUE THREAD

**Issue by apendragon** [xanzy/go-gitlab#1284]
Hi,

When you come from the [List runners jobs](https://docs.gitlab.com/ee/api/runners.html#list-runners-jobs) API endpoint, the fields related to the linked project on which each job has been run are missing.  

Regards,

**Comment by apendragon** [comment]
Please see my PR #1285

**Comment by svanharmelen** [comment]
Fixed by #1285
