### ISSUE TITLE
Can i obtain merge_yaml from Lint function?

### ISSUE THREAD

**Issue by jwillker** [xanzy/go-gitlab#1286]
Hi, really nice project, I appreciate that and use it in production code.

But I have some questions:

Why there are two response types for Lint:

https://github.com/xanzy/go-gitlab/blob/6b645e887f27bdee7a6aa2d9ee7cf95f467f50da/validate.go#L35-L50

And why the first one doesn't have the `MergedYaml` field?

I want to use the Lint function https://github.com/xanzy/go-gitlab/blob/6b645e887f27bdee7a6aa2d9ee7cf95f467f50da/validate.go#L55
Because I can pass any gitlab-ci file of any branch, but this function does have a merged_yaml result.
If a use the `ProjectLint` function I can only use the gitlab-ci file from the default branch.

Any idea how to solve this?

**Comment by svanharmelen** [comment]
They are different because they are used for different endpoints that support different types (see the doc links on both types). I do see in the docs that the `LintResult` should also have a `MergedYaml` field. Once that is added I guess you should be good right?

**Comment by JohnWillker** [comment]
> They are different because they are used for different endpoints that support different types (see the doc links on both types). I do see in the docs that the `LintResult` should also have a `MergedYaml` field. Once that is added I guess you should be good right?

Sure, if you added this field will solve my problem, thanks for that :+1:

**Comment by svanharmelen** [comment]
Fixed by #1287

**Comment by JohnWillker** [comment]
> Fixed by #1287

Thanks a lot
