### ISSUE TITLE
Support GitLab Topics API 

### ISSUE THREAD

**Issue by timofurrer** [xanzy/go-gitlab#1288]
GitLab 14.5 introduced a new GitLab Topics API: https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/api/topics.md

It would be great if this library could support this. There are also requests in the [GitLab terraform provider to support it](https://github.com/gitlabhq/terraform-provider-gitlab/issues/748) which depends on this library :)

**Comment by svanharmelen** [comment]
Fixed by #1309
