### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by sguillia** [xanzy/go-gitlab#1289]
Hi!

This commit breaks build

https://github.com/xanzy/go-gitlab/commit/8f8fc8c529f769832cbfd6c22ce2df4267bf37ca#diff-044b5a63fdba539bf87d25040d91912aec34173e76af7b9e0f40d14da57edebeR670

```
../../xanzy/go-gitlab/gitlab.go:670:26: req.Request.Header.Values undefined (type http.Header has no field or method Values)
```

**Comment by svanharmelen** [comment]
I think I need some more input as I cannot reproduce that error.

**Comment by sguillia** [comment]
This reproduces on Go 1.13 which I found out is no longer a supported version ([docs](https://golang.org/doc/devel/release#policy)). Sorry! Works on Go 1.16
