### ISSUE TITLE
Pipeline webhook events structs out of sync.

### ISSUE THREAD

**Issue by brewkode** [xanzy/go-gitlab#1290]
I've been using the gitlab sdk from here and it has helped me. Thanks for working on it. When working with pipeline webhooks, I noticed that, the current payload returned for [pipeline webhooks](https://docs.gitlab.com/14.5/ee/user/project/integrations/webhook_events.html#pipeline-events) from the server is different compared to what we have in [`event_webhook_types.go` in `master`](https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go). There are a few fields that have changed.

I started making changes, but, I wanted to check how version compatibilities are being managed ? Is there something that I should do to ensure things don't break ?  

PS: There are also potentially a bunch of other structs in `event_webhook_types.go` that are out-of-sync.

**Comment by svanharmelen** [comment]
As long as we're only adding missing fields it should be fine. Removing fields because they only apply to (slightly) older versions is not something I prefer to do...

**Comment by brewkode** [comment]
Thanks. Fixed this as part of the #1291
