### ISSUE TITLE
Pipeline Webhook Event RunnerType contains wrong field type with 0.52.1

### ISSUE THREAD

**Issue by vntw** [xanzy/go-gitlab#1297]
Hi,

I started getting an error with 0.52.1 `json: cannot unmarshal string into Go struct field .builds.runner.runner_type of type bool`. #1291 added the `RunnerType` field which seems to be wrong, see https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#pipeline-events - this should be a `string`, not a `bool`.

While it's documented, here's also a real example that I'm getting:

```json
"runner": {
  "id": 1,
  "description": "shared-runners-manager-5.gitlab.com",
  "runner_type": "instance_type",
  "active": true,
  "is_shared": true,
  "tags": [
	"docker",
	"gce"
  ]
}
```

I can send a PR (before or after the incoming breaking change in #1294) if there are no objections/reasons for this 🙂

**Comment by svanharmelen** [comment]
Nice catch, yes please do create a PR for this one before we land the breaking change. Thanks!
