### ISSUE TITLE
Support List Registry Repositories within a group

### ISSUE THREAD

**Issue by developer-guy** [xanzy/go-gitlab#1299]
We (w/@dentrax) noticed that there is support for listing registry repositories within a group in the official documentation of GitLab[^1]. Current support within the `go-gitlab` project covers only listing registry repositories by the given project[^2]. 

what we are proposing is that consider adding group support.

[^1]: https://docs.gitlab.com/ee/api/container_registry.html#within-a-group
[^2]: https://github.com/xanzy/go-gitlab/blob/master/container_registry.go

please feel free to assign it to us 🙋🏻‍♂️🤝

**Comment by svanharmelen** [comment]
By all means feel free to open a PR for this 👍🏻
