### ISSUE TITLE
json: cannot unmarshal number into Go struct field Pipeline.coverage of type string

### ISSUE THREAD

**Issue by vr333dev** [xanzy/go-gitlab#1308]
Hello, calling function pipeline.go/GetPipeline caused this error to come up (started recently, and strangely not all pipelines are causing this error): json: cannot unmarshal number into Go struct field Pipeline.coverage of type string

I don't see any pipeline patterns (MR, tag, branch, main pipelines etc.) which would help identify where the issue is coming from, but it seems like more and more responses come back with that error (we're processing all pipelines in multiple projects).

Current Gitlab version: 14.6.0-pre

Thanks

Vlad

**Comment by vr333dev** [comment]
Update: Coverage type "string" should be changed to "float32".  This was tested locally by replacing struct Pipeline (included several other dependencies, overridden GetPipeline function etc.)

**Comment by svanharmelen** [comment]
Please see #1307, this seems to be a regression in GitLab so for now I'm not going to change it in this package.
