### ISSUE TITLE
Can seem to get AcceptMergeRequest to work.

### ISSUE THREAD

**Issue by downright-ux** [xanzy/go-gitlab#1310]
Trying to use AcceptMergeRequest to do a merge but doesn't seem to be working tried a couple different options. Here is what trying to do right now.

```
func AcceptMergeRequest(git *gitlab.Client, projectId int, bn string, issueId int)  {
	a := &gitlab.AcceptMergeRequestOptions{
		Squash: 					        gitlab.Bool(true),
		ShouldRemoveSourceBranch: 	gitlab.Bool(true),
		MergeWhenPipelineSucceeds: 	gitlab.Bool(true),
	}

	_,_, err := git.MergeRequests.AcceptMergeRequest(projectId, issueId, a)
	if err != nil {
		log.Fatal(err)
	}
}
```

any suggestions on how we get the MR to start pushing through?

**Comment by svanharmelen** [comment]
Please provide more info. What do you expect to happen and what actually happens? What errors do you get?

**Comment by svanharmelen** [comment]
Please provide more info as otherwise I will (in a week or so) close this issue again. Thanks.

**Comment by downright-ux** [comment]
I don't get any errors. I would expect when the function is called that the merge request would be completed. Instead nothing happens. Maybe I'm using the wrong func type and if so can you direct me to the one to push a merge

**Comment by svanharmelen** [comment]
I suggest you take a closer look to the API docs as they describe what each method does. A link to the relevant API is added in the comments of each method supported by this package.

The API call you are using now is meant to approve/accept a PR (https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr). So you are not merging anything, but you are marking the PR as being approved and ready to be merged.

I think this API is what you are looking for: https://docs.gitlab.com/ee/api/merge_requests.html#merge-to-default-merge-ref-path Yet it seems that one isn't supported just yet. I'll add it in a minute...

**Comment by zye300** [comment]
@svanharmelen @downright-ux

**Comment by zye300** [comment]
Yeah, https://docs.gitlab.com/ee/api/merge_requests.html#merge-a-merge-request This is the API I am looking for and I think your AcceptMergeRequest is the method to support it.It is supposed to merge a merge request as stated in the gitlab document. However, it now does nothing currently. Can you help me check on that? @svanharmelen  Thanks a lot!

**Comment by svanharmelen** [comment]
Hmm... Seems that old URL doesn't exist anymore. Wonder if they changed the name...

But anyway, it indeed looks like the API call you are referring to is the one that should merge an MR. But no clue what I can do if nothings happens when you call this API. So what happens if you try to make the same API call with cURL?

And can you define what you mean with "noting happens"? Do you get an API response of any kind? Or an error?

**Comment by zye300** [comment]
So for the response, I will get a 405 Method Not Allowed status, but there's no error.

**Comment by svanharmelen** [comment]
Did you try it using cURL? And did you check the comment: https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L683

Either way this seems related to how the GitLab API works, not this package...

**Comment by zye300** [comment]
I see. Thanks!

**Comment by vl-shopback** [comment]
try this workaround, sleep for some time and then call the api

**Comment by svanharmelen** [comment]
Closing as stale... Feel free to reopen in the future if applicable.
