### ISSUE TITLE
ProjectMembers.ListAllProjectMembers() hangs on rate limiting

### ISSUE THREAD

**Issue by dheitman42** [xanzy/go-gitlab#1311]
I've got some code that calls ProjectMembers.ListAllProjectMembers().  Normally this works fine, but I've found that in cases where gitlab is rate-limiting API requests (at least for the "throttle_authenticated_api" reason, only one I've encountered so far).  When running a curl request using the same API key and query string, I get the following response:

`< HTTP/1.1 429 Too Many Requests
< Cache-Control: no-cache
< Content-Type: text/plain
< Date: Fri, 10 Dec 2021 20:44:54 GMT
< Ratelimit-Limit: 167
< Ratelimit-Name: throttle_authenticated_api
< Ratelimit-Observed: 11176
< Ratelimit-Remaining: 0
< Ratelimit-Reset: 1639170000
< Ratelimit-Resettime: Fri, 10 Dec 2021 21:00:00 GMT
< Referrer-Policy: strict-origin-when-cross-origin
< Retry-After: 906
< Vary: Origin
< X-Request-Id: xxxxxx
< X-Runtime: 0.011418
< Content-Length: 12
< Connection: keep-alive
<
Retry later
* Connection #0 to host gitlab.checkrhq.net left intact
* Closing connection 0`

However, when running the same query via ListAllProjectMembers(), the code simply hangs indefinitely.  Not sure what is causing the hang yet, perhaps it's a retry mechanism?  But I would expect this to return an error, rather than waiting and retrying.

**Comment by svanharmelen** [comment]
@dheitman42 is this still a problem or did you manage to solve this problem/issue?

**Comment by dheitman42** [comment]
Honestly haven't had time to revisit this code in quite a while, busy busy.  I'll see if I can find a spare moment to check.

**Comment by svanharmelen** [comment]
Closing this one a stale issue. Feel free to reopen it if applicable.
