### ISSUE TITLE
NewRequest does not accept absolute path

### ISSUE THREAD

**Issue by mitar** [xanzy/go-gitlab#1315]
Its documentation states:

```
// NewRequest creates an API request. A relative URL path can be provided in
// path, in which case it is resolved relative to the base URL of the Client.
// Relative URL paths should always be specified without a preceding slash. If
// specified, the value pointed to by body is JSON encoded and included as the
// request body.
```

Reading this looks like you can provide relative or absolute URL path. But with absolute URL path it just does the wrong thing. So maybe documentation should be improved to say only relative paths are supported or implementation fixed?

**Comment by svanharmelen** [comment]
I wouldn't like to change the implementation, so maybe we can update the doc just a little to make it a bit more clear. I guess the reasoning here was that an empty string is also valid.
