### ISSUE TITLE
Pagination helper

### ISSUE THREAD

**Issue by mitar** [xanzy/go-gitlab#1320]
It seems I am writing many boilerplate pagination loops. Maybe this package could provide a pagination helper to do this automatically?

It could help with #815, too, so that we could update pagination helper and users would automatically get benefits of keyset pagination when it is available.

**Comment by svanharmelen** [comment]
Can you share an example of such boilerplate?

**Comment by mitar** [comment]
It is already [in the repository](https://github.com/xanzy/go-gitlab/blob/master/examples/pagination.go). The only difference is that I am `append`ing results into a slice and then returning it at the end (instead of printing them out).

**Comment by svanharmelen** [comment]
Check... But looking at that code it looks like it would mean that each own endpoint (type) would need it's own custom function (loop). I'm not too excited (read not really open) to add that to this package as I try to keep the load on maintaining this package reasonable by limiting the functionality 1:1 to the GitLab API.

Maybe when generics have landed we can see if we can write a single function that can work for all of the list calls, but until then I don't want to add a helper function for each list call.

**Comment by Roemer** [comment]
I just stumbled upon this closed issue and also tried to get rid of some boilerplate with generics.
The best method I came up with for now is with the following:
```go
func getPaginated[I any, O gitlab.ListOptions](searchFunc func(pageNum int) ([]I, *gitlab.Response, error)) ([]I, *gitlab.Response, error) {
	items := []I{}
	pageNum := 1
	for {
		tempItems, response, err := searchFunc(pageNum)
		if err != nil {
			return nil, response, err
		}
		items = append(items, tempItems...)
		if response.NextPage == 0 {
			break
		}
		pageNum = response.NextPage
	}
	return items, nil, nil
}
```
The idea is that you basically use your existing method that needs pagination and you get the information which page you need and you need to add this as list option.
So for example:
```go
gitlabBranches, _, err := getPaginated(func(pageNum int) ([]*gitlab.Branch, *gitlab.Response, error) {
	return git.Branches.ListBranches(myProjectId, &gitlab.ListBranchesOptions{
		ListOptions: gitlab.ListOptions{Page: pageNum},
	})
})
```
or
```go
treeNodes, _, err := getPaginated(func(pageNum int) ([]*gitlab.TreeNode, *gitlab.Response, error) {
	return git.Repositories.ListTree(myProjectId, &gitlab.ListTreeOptions{
		Path:        gitlab.String(basePath),
		Recursive:   gitlab.Bool(false),
		ListOptions: gitlab.ListOptions{Page: pageNum},
	})
})
```

**Comment by svanharmelen** [comment]
Yes, open to a PR but please do not create a `utils.go` file for it 😅 Would be open to either putting it in `gitlab.go` or I guess a file called `pagination.go` would also be fine...
