### ISSUE TITLE
Update label functions to new endpoints

### ISSUE THREAD

**Issue by mitar** [xanzy/go-gitlab#1321]
`PUT /projects/:id/labels` with `name` or `label_id` in the parameters is deprecated. `DELETE /projects/:id/labels` with `name` in the parameters as well.

See:
* https://docs.gitlab.com/ee/api/labels.html#edit-an-existing-label
* https://docs.gitlab.com/ee/api/labels.html#delete-a-label

**Comment by svanharmelen** [comment]
That's fine, it still needs to be there so this package also works with older versions.

**Comment by mitar** [comment]
With older versions of local GitLab installations?

This has been [changed 2 years go (September 2019)](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17239). How long should support for old versions be kept?

**Comment by svanharmelen** [comment]
As long as practically possible. So as long as this doesn't break or interfere with current versions, I prefer to "just" keep it in there and with that support as much versions as possible.
