### ISSUE TITLE
Add support for listing projects starred by a user

### ISSUE THREAD

**Issue by amitsaha** [xanzy/go-gitlab#1331]
Currently, the SDK doesn't have a function for listing projects that are starred by a user: https://docs.gitlab.com/ee/api/projects.html#list-projects-starred-by-a-user (The docs need slight updation: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/77453)

I _think_ the old API had a different mechanism or it was mixed with listing the starred projects of a user, since this PR: https://github.com/xanzy/go-gitlab/pull/170/files removed what seems like the functionality this issue is referring to.

I will be attaching a PR shortly.

I realize that for the authenticated user, once can use the use the `ListProjects()` functionality, but for any arbitrary user, this SDK function will be useful i think.

**Comment by svanharmelen** [comment]
Fixed by #1332
