### ISSUE TITLE
Support the `job_events` field in Slack Notification integration service

### ISSUE THREAD

**Issue by timofurrer** [xanzy/go-gitlab#1354]
The GitLab API supports a `job_events` field in the [Slack Notification Service Integration](https://docs.gitlab.com/ee/api/integrations.html#slack-notifications) which is not yet available in `go-gitlab`. 

Would be good to implement this. Also the `ConfidentialNoteChannel` is currently not supported. I noticed the comment in the source code here, however, if it's "only" ignored by the upstream GitLab API I think you should implement it nevertheless.
It's a bug in upstream and actually documented as it should be available.

**Comment by timofurrer** [comment]
Also the `commit_events` is currently not supported here.

**Comment by timofurrer** [comment]
There is actually quite some problems in the upstream GitLab API which may block you to correctly implement this at the moment: https://gitlab.com/gitlab-org/gitlab/-/issues/28903

**Comment by svanharmelen** [comment]
Is this still applicable or did things change?

**Comment by svanharmelen** [comment]
Closing this one due to no response. Feel free to reopen if needed...

**Comment by timofurrer** [comment]
It's still applicable: https://github.com/xanzy/go-gitlab/blob/1983bd31dfff9674b9e92c37eb9abd7bf2269d50/services.go#L1212

Sorry for not responding ;)

**Comment by svanharmelen** [comment]
No problem, just reopened it 👍🏻

**Comment by Mareo** [comment]
Hello, I opened a MR to fix various issues with the GitLab project integration API, I'll open a MR here to account for these changes and add support for the Discord integration once it is merged: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122943
