### ISSUE TITLE
Allow to remove `due_date` from Issue

### ISSUE THREAD

**Issue by timofurrer** [xanzy/go-gitlab#1384]
The `.Issues.UpdateIssue()` endpoint doesn't seem to support removing the `due_date`.

This is because the library stored to `due_date` as `*gitlab.ISOTime`. In case it's `nil` it's not passed as payload and therefore the field is left unmodified. However, the API has more states for that field:

* omitted: the field is unchanged
* null / empty string: the due date is removed
* valid date: the due date is added

**Comment by svanharmelen** [comment]
If you can come up with a reasonable way to support all these options I'm open to have a look at it.

The difficulty is the fact that Go uses default (zero) values for each type. If we were to remove the `omitempty` tag, you can no longer omit the field which means you always have to give this field the correct value even when you don't want to change it and only want to change another field.

In a lot of cases this would mean that you first need to get the object from the API the get the current value and then use that in the call to actually make a change to another field...

Of course we could update the marshal logic for the `ISOTime` type as we already have custom logic for that. But that would only solve it for this one type. Or is this only applicable for this type?

**Comment by timofurrer** [comment]
> If you can come up with a reasonable way to support all these options I'm open to have a look at it.

Not really so far, except the special unmarshaling logic which separates the point (1) and (2) from my list above.

> Or is this only applicable for this type?

I'm not 100% sure if it's a 1:1 relationship for the type itself or just the semantics of the API here. I can certainly imagine that others are affected, too.

Limiting ourselves to the `ISOTime`, I've mostly seen it for event timestamps (like `created_at`, `updated_at`, `closed_at`) etc. and also `expires_at` (which usually can't be changed, thus it isn't affected). And there is the `due_date`, which usually can be removed with an update, but also omitted to leave it unchanged. Point being, I don't think that a lot of endpoints are affected.

But if the `due_date` field were a `*string` with the `omitempty` tag wouldn't that mean that:

* omitted / unchanged: if `due_date = nil` (because of `omitempty`)
* removed: if `due_date = ""` (because `omitempty` would not take affect because it applies to the pointer and not the underlying string)
* change date: if `date_date = "..."`

**Comment by svanharmelen** [comment]
I don't think `ISOTime` is the wrong type here. The field is actually a time (date), not a generic string. So having a type that represents that data is fine. So I guess for now we can update the marshal logic to help us out for this specific one... I'll have a look at that in a bit...

**Comment by timofurrer** [comment]
Yes, my only point is that how do you tell a `*ISOTime` (which is just a `*time.Time`) that you want to "clear" (which is never a valid date, nor `nil`) it? 

You would need an additional state in the type or the options, right?

**Comment by svanharmelen** [comment]
By comparing the given value against the types zero value. And if they match, then write `null` instead of a value (assuming `null` works as well? Or does it have to be `""`?

And then writing &ISOTIme{} would remove the `due_date`...

**Comment by timofurrer** [comment]
Just verified that `null` works, too 👍
