### ISSUE TITLE
External status check: creation calls

### ISSUE THREAD

**Issue by chmouel** [xanzy/go-gitlab#1405]
I see from #1261 that status checks has been implemented. But only the listing calls seems to be available.

There is other calls that probably could be useful to create external checks integrations

https://docs.gitlab.com/ee/api/status_checks.html#set-status-of-an-external-status-check

If there is no objections I may try to implement them

**Comment by svanharmelen** [comment]
Go right ahead 👍🏻  Just take a good look at other parts of the code and make sure it consistent... Thanks!

**Comment by svanharmelen** [comment]
Is this an open issue, or do we already support this by now?
