### ISSUE TITLE
AssigneeID should also accept "none" and "any"

### ISSUE THREAD

**Issue by ygarasab** [xanzy/go-gitlab#1408]
Hey, I'd like to list unassigned issues, but to do so I'd have to pass the AssigneeID with the value "none", wich is not currently possible, given the option type definition below.

https://github.com/xanzy/go-gitlab/blob/bd30483e865c054c52179448051bef0c597a2495/issues.go#L218

So I was thinking if we could change that in a way to allow for this "any" and "none" possible values.

I'm likely to create a pull request for that sson, but as such strcuture would be quite werid (blame gitlab for that), I'd realy like to know if you guys have tackled this problem and maybe just decided to live it be.

**Comment by svanharmelen** [comment]
Please checkout: https://github.com/xanzy/go-gitlab/blob/master/types.go#L133

**Comment by ygarasab** [comment]
Oh, thx
If I got it right, should we set this `AssigneeIDValue` as the type for `AssigneeID` in the `ListIssuesOptions` struct?
And then we could just use the `UserIDNone` constant here.

Or maybe I didn't get it?

**Comment by svanharmelen** [comment]
Almost... The type should be `*AssigneeIDValue` and then you can set it using the helper function:
```go
gitlab.AssigneeID(gitlab.UserIDNone)
```
Which returns a `*AssigneeIDValue`

**Comment by ygarasab** [comment]
Ok, thx for ur patience, PR comming soon
