### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by feeops** [xanzy/go-gitlab#1413]
runtime error: invalid memory address or nil pointer dereference

core code 

`
job, _, err := git.Jobs.GetJob(projectID, jobID)
ftm.Println(job.Project.WebURL)
`

**Comment by svanharmelen** [comment]
I guess `job.Project` is `nil`. So you should probably test if the `Project` is `nil` before trying to access any fields in it.

**Comment by svanharmelen** [comment]
Closing this for now as I think you should be good. Feel free to reopen the issue if not...
