### ISSUE TITLE
Support all Services

### ISSUE THREAD

**Issue by johanbrandhorst** [xanzy/go-gitlab#142]
Currently only a couple of the following services are supported:

Drone CI
Hipchat
Slack Notifications

Furthermore, only Drone CI has the getter defined, and there's also definitions for a Gitlab CI service which does not seem to exist anymore (using https://docs.gitlab.com/ce/api/services.html as a reference).

**Comment by svanharmelen** [comment]
Yeah, the Gitlab API is being extended and improved continuously so I guess there are a few new services that are not supported in here yet. I a bit constrained on time, but will try to allocate some time in the near future.

Meanwhile of course any PR's adding what you need are much appreciated!

**Comment by svanharmelen** [comment]
I'm going to close this issue as this is a never ending ongoing effort to keep this package in sync with the GitLab API.
