### ISSUE TITLE
Retry request also on non-HTTP errors

### ISSUE THREAD

**Issue by mitar** [xanzy/go-gitlab#1476]
If I am reading `retryHTTPCheck` correctly, current implementation retries only on HTTP responses with 429 status code or if status code is >= 500. But on other errors it does not. From my experience, there are also errors where it would be nice to automatically retry. For example, I just got the following error:

```
Get "https://gitlab.com/api/v4/projects?id_after=762150&order_by=id&per_page=100&simple=false&sort=asc&visibility=public&pagination=keyset": dial tcp 172.65.251.78:443: i/o timeout
```

It looks like there was some TCP/IP connection issue, and it is a temporary one. Retrying worked immediately.

Because `client` is a private field, one cannot really do much to fix this (e.g., I cannot set my own `CheckRetry` function) unless fixed in the package.

**Comment by svanharmelen** [comment]
You can create your own versions of these function using the client options: https://github.com/xanzy/go-gitlab/blob/master/client_options.go

**Comment by mitar** [comment]
Nice. Thanks.

I still think it would be useful if the default would retry on TCP errors.

**Comment by mitar** [comment]
Hm, strange. Default seems to not retry even 500 error. In my logs (logged with `%v` for error) I get:

```
GET https://gitlab.com/api/v4/projects: 500 {message: 500 Internal Server Error}
```

I think the issue is that `err != nil` check comes before `resp.StatusCode == 429 || resp.StatusCode >= 500` check in `retryHTTPCheck`.

**Comment by mitar** [comment]
Hm, strange. Default seems to not retry even 500 error. In my logs (logged with `%v` for error) I get:

```
GET https://gitlab.com/api/v4/projects: 500 {message: 500 Internal Server Error}
```

I think the issue is that `err != nil` check comes before `resp.StatusCode == 429 || resp.StatusCode >= 500` check in `retryHTTPCheck`.

**Comment by svanharmelen** [comment]
Not going to implement that right now as I can also imagine situations where you don't want that...

**Comment by mitar** [comment]
For posterity, I ended up just using default retry policy: `gitlab.WithCustomRetry(retryablehttp.DefaultRetryPolicy)` Works like a charm for me.

> I can also imagine situations where you don't want that...

I cannot. I think it is reasonable to try at least few times on TCP errors. But it is OK. :-)
