### ISSUE TITLE
Projects: Unused `Public` field

### ISSUE THREAD

**Issue by amitsaha** [xanzy/go-gitlab#1478]
I believe https://github.com/xanzy/go-gitlab/blob/f48435557d76313df1854d881fd8b8eab5e93244/projects.go#L43 is not being set correctly, likely because there is no `public` field in the JSON response any more? Hence, it is always `false` for all projects, irrespective of their visibility.

To reproduce:

1. Create a test private project
2. Create a test public project

Run:

```
package main

import (
    "log"
    "os"

    "[github.com/xanzy/go-gitlab](http://github.com/xanzy/go-gitlab)"
)

func main() {
    git, err := gitlab.NewClient(os.Getenv("GITLAB_TOKEN"))
    if err != nil {
        log.Fatal(err)
    }

    opts := gitlab.ListProjectsOptions{
        Owned: gitlab.Bool(true),
    }

    projects, _, err := git.Projects.ListProjects(&opts)
    if err != nil {
        log.Fatal(err)
    }
    for _, p := range projects {
        log.Printf("%v -> visibility: %v -> public: %v\n",
p.PathWithNamespace, p.Visibility, p.Public)
    }
}
```

You will see `Public` is always `false`. Happy to create a PR as well.

**Comment by svanharmelen** [comment]
Guess a quick check with the docs or GitLab codebase would be good... And also make sure it's not used in older versions (as we still like to be able to support those as well).

**Comment by heidiberry** [comment]
This field was present in the first release of this repo in 2015. Looking through the GitLab codebase, it was removed from the API in this merge request back in 2017 https://gitlab.com/gitlab-org/gitlab/-/merge_requests/1267/diffs which was around version 9.0 of GitLab.

**Comment by svanharmelen** [comment]
In that case I guess it's save to remove it...
