### ISSUE TITLE
Add support for "resource group" API

### ISSUE THREAD

**Issue by MichaelGissingNC** [xanzy/go-gitlab#1479]
Resource groups are kind of a semaphore to prevent multiple deployments to the same environment. If there are multiple deployment jobs queued there is a setting `process_mode` to control the order in which these jobs are processed. There is no GUI to change this setting, it's only available via API.

Therefore it would be great to have this API available in the library.

* Feature Documentation: https://docs.gitlab.com/ee/ci/resource_groups/index.html
* API Documentation: https://docs.gitlab.com/ee/api/resource_groups.html

**Comment by MichaelGissingNC** [comment]
@svanharmelen Suppose I would find time to work on this (which I can't promise yet) - Is there a contribution guide or similar?

**Comment by svanharmelen** [comment]
Not really, other then that I prefer to follow the naming and ordering from the docs as much as possible. And it's probably good to have a quick look around the existing code and make sure any new code is consistent with that...
