### ISSUE TITLE
Add support for project triggers

### ISSUE THREAD

**Issue by johanbrandhorst** [xanzy/go-gitlab#148]
Doesn't look like [project pipeline triggers](https://docs.gitlab.com/ce/api/pipeline_triggers.html) are supported yet?

**Comment by johanbrandhorst** [comment]
I'm gonna have a crack at this

**Comment by svanharmelen** [comment]
Sure thing, go right ahead!

**Comment by johanbrandhorst** [comment]
Is this project going to target v3 or v4? I'm assuming it's v3 now, which [according to Gitlab](https://docs.gitlab.com/ce/api/v3_to_v4.html) has just been deprecated (9.0 is released today). Do you plan on making a branch for v4 support and have some clean cutoff?

**Comment by johanbrandhorst** [comment]
Having looked a bit more at v3 -> v4 details it'll be quite an undertaking to update all the things changed. Here's the document with the changes https://docs.gitlab.com/ce/api/v3_to_v4.html. Also I suppose the README.md could make it more explicit that this library targets v3?

**Comment by svanharmelen** [comment]
Yeah, I guess it's about time to think about this one a little... I think I would like to work up to a final release that supports the V3 API, and then start with making the package support the V4 API.

I don't think having separated branches would work nicely in the longer run. Of course during development that's just fine, but once all is good I think master should be the latest and greatest.

And of course the V3 API will become obsolete in the longer run. But I'll make a V3 branch for hotfix releases in the case those will ever come...
