### ISSUE TITLE
VariableType not omitted properly

### ISSUE THREAD

**Issue by andrewbaxter** [xanzy/go-gitlab#1486]
In `PipelineVariable` if you omit `VariableType` you get a 500 error.  If you specify `"env_var"` it works fine.  I assume it's serialized to json `""` instead of having the key omitted entirely and gitlab doesn't like that.

**Comment by svanharmelen** [comment]
@andrewbaxter I assume this fixes your issue right? I noticed this was the only place where the `PipelineVariable` was used as an option struct, so I guessed this was where you saw the error?

**Comment by andrewbaxter** [comment]
Ah yeah, exactly.  Sorry, I should have added more details.  That looks like it will fix things!
