### ISSUE TITLE
how to clone to local

### ISSUE THREAD

**Issue by xiaoliang002** [xanzy/go-gitlab#1487]
How to pull the repository from the remote to the local directory, or execute the git pull command through the local directory

**Comment by svanharmelen** [comment]
Hi 👋🏻  This package is not meant to execute standard Git commands, but it's purpose is to talk against the GitLab API. If you want to use Git commands from a Go application you can try this package: https://github.com/go-git/go-git

**Comment by svanharmelen** [comment]
I assume this answers your question so I will close this issue. Feel free to reopen it if you have additional questions!

**Comment by xiaoliang002** [comment]
thank you
