### ISSUE TITLE
Project's Merge Request approval configuration

### ISSUE THREAD

**Issue by Twicefan98** [xanzy/go-gitlab#1502]
Hi, can't seem to find a way to retrieve Project's Merge request approval configuration as shown in Gitlab API https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-configuration

The current go-gitlab services seems to only be able to retrieve Merge request level configurations.

**Comment by 2785** [comment]
https://github.com/xanzy/go-gitlab/blob/master/projects.go#L1691

it exists :thinking:

**Comment by svanharmelen** [comment]
Thanks for the reference @2785! I'll close this one for now. If needed feel free to reopen it...
