### ISSUE TITLE
Add support for listing issues for a given project / repository

### ISSUE THREAD

**Issue by jamietanna** [xanzy/go-gitlab#1503]
In https://docs.gitlab.com/ee/api/issues.html#list-project-issues it's noted that there's the ability to list a given project's issues, which would be helpful to expose.

Maybe we could extend the `IssuesService`' `ListIssuesOptions` to take a `Project` ID?

**Comment by lizalc** [comment]
[`ListProjectIssues`](https://github.com/xanzy/go-gitlab/blob/master/issues.go#L352) does what you need, yes? The first parameter, `pid`, is for the project ID.

**Comment by svanharmelen** [comment]
Closing due to no response and the assumption this isn't a problem...

**Comment by jamietanna** [comment]
Apologies for the super late reply, but yes, you're absolutely right! I think I didn't see it at first as I was looking for `not[username]` but I can do a search with `not[author_id]` and that works :clap:
