### ISSUE TITLE
Helath/Liveness/Readiness Probes check for gitlab

### ISSUE THREAD

**Issue by mayankmike86** [xanzy/go-gitlab#1533]
We have requirement to get the  Helath/Liveness/Readiness Probes check for gitlab through  a go client.
Gone through the documentation but do not see anything for Helath/Liveness/Readiness Probes.

Can anyone from team help with some examples or the methods.

**Comment by svanharmelen** [comment]
I guess this question should be asked to GitLab, unless you can already find support among their APIs: https://docs.gitlab.com/ee/api/api_resources.html

**Comment by graza-io** [comment]
They have support for these endpoints (in self-managed only) - [https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html#health-check](https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html#health-check)

**Comment by svanharmelen** [comment]
Check 👍🏻

**Comment by mayankmike86** [comment]
Yes found those and using api to get health 
thanks @svanharmelen @graza-io 
closing this now.
