### ISSUE TITLE
Mismatch between `public_builds` and `public_jobs`

### ISSUE THREAD

**Issue by mtneug** [xanzy/go-gitlab#1538]
The projects API will respond with a `public_jobs` field, while `public_builds` should be used when setting this field according to the documentation. This is already known upstream. It appears that `public_jobs` can be used for setting and retrieving.

See <https://gitlab.com/gitlab-org/gitlab/-/issues/329725>
See <https://github.com/gitlabhq/terraform-provider-gitlab/issues/1233>

**Comment by svanharmelen** [comment]
Feel free to create a PR to fix it...
