### ISSUE TITLE
`*CommitDiscussion` functions: how to convert a commit SHA from `string` to `int`?

### ISSUE THREAD

**Issue by claytonrcarter** [xanzy/go-gitlab#1546]
Hi! I was investigating upgrading the `lab` project to a newer version of `go-gitlab` (we're currently on 0.51) and ran into an issue about translating commit SHAs (as strings) into ids (as ints) for `CreateCommitDiscussion()`, which led me down a rabbit hole. I'm not very strong in Go, so I'm fumbling around a little bit, but PR 1260 changed all of the `*CommitDiscussion` and `*CommitDiscussionNote` functions to take a `commit int` instead of a `commit string` (which I think was released in 0.56), and I haven't been able to figure out how to convert SHA strings into an int id that GL will understand.

Any pointers?

(FWIW, GL API docs for commits don't mention int ids, in fact they are all explicitly strings; and even the docs for commit discussions have different values for different endpoints: most say it's an `int`, but at least 1 says it's a `string`. Beyond that, I've even been able to pass string SHAs to those other endpoints w/o issue. 🤷 )

**Comment by claytonrcarter** [comment]
FWIW I'm finding more hints that the API docs might just be wrong:
- I have successfully used cURL to create, list and get commit discussions w/ a commit SHA (ie string not int)
- The one API endpoint in the docs that uses `string` was [changed from an `int` via MR last year](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67406/diffs)
- Several of the endpoints also require a `discussion_id`. The docs state that these are `int`, too, but the `*CommitDiscussionNote` functions all treat them as `string`. (And in the API response, these discussion ids look SHA-like.)

**Comment by claytonrcarter** [comment]
PS If I'm not off my rocker and you agree w/ my assessment, I'd be happy to PR this. 😄

**Comment by claytonrcarter** [comment]
Apparently, I'm on a mission. I've opened [!97586](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97586) to either update the API docs or confirm that I'm off my rocker. 😄

**Comment by svanharmelen** [comment]
Converting a SHA to an ID is not possible, they are two different things all together. But if the docs and/or the code turns out to be wrong, than by all means feel free to create a PR to fix it.
