### ISSUE TITLE
Return all projects

### ISSUE THREAD

**Issue by DaveDrupsteen** [xanzy/go-gitlab#1564]
Hi,

I am not sure if this has been asked before. If so i apologize. 

Is it possible to return all the projects where the authenticated user has access to? 
By default it seems the response is limited to (I believe) 20. You can, via the API use a `per_page` param to get max 100 per page.
But then the library would need support for pagination or something, which i am not seeing when looking through the docs.

**Comment by svanharmelen** [comment]
This should probably get you going: https://github.com/xanzy/go-gitlab/blob/master/examples/pagination.go
