### ISSUE TITLE
Add custom header for passthrough Google IAM

### ISSUE THREAD

**Issue by insomnius** [xanzy/go-gitlab#1583]
Currently the library won't work if the gitlab is under google IAM, need to add custom additional header to insert IAM token in the request.

**Comment by theoriginalstove** [comment]
I'm wondering if this is as simple as adding a new `RequestOptionFunc` and then when creating a new client just passing it into `WithRequestOptions`.

**Comment by insomnius** [comment]
Yup, just simple custom header could work. But getting the IAM header is another thing, since it's not visible in regular network console.
