### ISSUE TITLE
Support validation of event data types？

### ISSUE THREAD

**Issue by coder-user** [xanzy/go-gitlab#1587]
Currently, the received events are only parsed json.unmarshal, and the validity of the data values is not verified.

**Comment by svanharmelen** [comment]
Hmm... I don't think I'm very open to adding something like that to be honest. My gut feeling is that it would be pretty tedious and potentially needs to be changed updated frequently as the GitLab API updates and changes a lot.

But besides that I'm not sure what problem it would solve? If some data is not correctly returned that is a bug in the GitLab API and so I would argue the tests in their API should flag it and if not an issue should be created in the GitLab repo.

**Comment by coder-user** [comment]
Yes, we believe that gitlab's official request is reliable.
However, we cannot determine the validity of the attack request.
If I need to use the ID, I need to judge its existence again:
```go
func adjustFormatCommitID(id string) string {
	if len(id) == 0 {
		return ""
	}

	if len(id) > 8 {
		return id[:8]
	}

	return id
}
```

**Comment by svanharmelen** [comment]
So when would this be applicable? As in, what scenario would enable such attack? You provide the URL you want to connect to yourself, so while I'm all for making things are secure I don't feel comfortable adding custom validation functions for all structs...

**Comment by armsnyder** [comment]
@coder-user You could validate the request in your handler by checking the `X-Gitlab-Token` request header, as in this example:

https://github.com/xanzy/go-gitlab/blob/52eedaaf1853682e004da82611d0940fc3d62e3c/examples/webhook.go#L86-L91

**Comment by svanharmelen** [comment]
Closing as stale... Feel free to reopen in the future if applicable.
