### ISSUE TITLE
List commit only support maximum 20 commit

### ISSUE THREAD

**Issue by AlfieNguyen1107** [xanzy/go-gitlab#1591]
Currently, listing commit from a project only list 20 latest commit and there seem to be no way to increase the limit.

**Comment by svanharmelen** [comment]
Does the result differ when making the API call using cURL? And/or could pagination play a role here?

**Comment by EdgeJ** [comment]
I've run into the same issue. It does seem that the gitlab API paginates results by default.  I have 21 open MRs currently. Using curl against the API I see only 20 MRs unless I paginate to see the last one:
```
➜ curl -sL https://gitlab.com/api/v4/projects/<REDACTED>/merge_requests\?state\=opened\&order_by\=updated_at --header "PRIVATE-TOKEN: <REDACTED>" | jq -r '.[].iid' | wc -l
      20

➜ curl -sL https://gitlab.com/api/v4/projects/<REDACTED>/merge_requests\?state\=opened\&order_by\=updated_at\&page\=2 --header "PRIVATE-TOKEN: <REDACTED>" | jq -r '.[].iid' | wc -l
       1
```

**Comment by svanharmelen** [comment]
`ListCommitOptions` includes an embedded `ListOptions` struct (https://github.com/xanzy/go-gitlab/blob/master/commits.go#L75) that can be used to do pagination: https://github.com/xanzy/go-gitlab/blob/master/examples/pagination.go

Closing this one as I assume this solved your question. If not feel free to reopen, but in that case please add more details and/or and example of what exactly you are trying to do...
