### ISSUE TITLE
Define more types needed for testing event webhooks

### ISSUE THREAD

**Issue by armsnyder** [xanzy/go-gitlab#1592]
Hi,

I am building a [webhook integration](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html) using go-gitlab. Since the [event types](https://github.com/xanzy/go-gitlab/blob/511533c923152bb46ffa4e7985a3023fb7015398/event_webhook_types.go) use anonymous struct definitions, it isn't possible to construct an event to test my hook without using json.

What I have:

```go
func TestMyHandler(t *testing.T) {
	event, _ := gitlab.ParseHook(gitlab.EventTypeIssue, []byte(`{
  "project": {"id": 111},
  "object_attributes": {"iid": 222, "state": "open"}
}`))
	err := myHandler(event)
	if err != nil {
		t.Fatal(err)
	}
}
```

What I would like:

```go
func TestMyHandler(t *testing.T) {
	event := &gitlab.IssueEvent{
		Project:          gitlab.EventProject{ID: 111},
		ObjectAttributes: gitlab.IssueEventObjectAttributes{IID: 222, State: "open"},
	}
	err := myHandler(event)
	if err != nil {
		t.Fatal(err)
	}
}
```

I saw that there are already some types in go-gitlab like [EventUser](https://github.com/xanzy/go-gitlab/blob/511533c923152bb46ffa4e7985a3023fb7015398/event_webhook_types.go#L610), so if there is precedence, are you open to contributions that add more? Is there a better way of testing hooks that others have used?

**Comment by svanharmelen** [comment]
I'm open adding more named types in there if that makes things easier to work with...

**Comment by svanharmelen** [comment]
I'll close this issue as any follow ups should probably be PRs
