### ISSUE TITLE
Label names are not unmarshalled from webhook events

### ISSUE THREAD

**Issue by armsnyder** [xanzy/go-gitlab#1594]
Hi,

## What happened

Some GitLab webhook events contain information about the related issue or merge request. For these events, there is currently no way to extract the label names, because the structs used for unmarshalling the event do not contain a field for the label name.

## More context

The various webhook structs are incorrectly [reusing a struct](https://github.com/xanzy/go-gitlab/blob/ac5896fb7752ddd0eacaf1f724acef4b1d121455/labels.go#L36-L48) from the [Labels API](https://docs.gitlab.com/ee/api/labels.html#get-a-single-project-label). Unfortunately one of the major differences between the Labels API and the webhooks is in how you parse the label name. In the Labels API, the field is "name", but in an event the field is "title".

Example webhook request (irrelevant top-level fields are omitted):

<details>

```json
{
  "object_kind": "issue",
  "event_type": "issue",
  "object_attributes": {
    "labels": [
      {
        "id": 11199,
        "title": "status::Done",
        "color": "#00b140",
        "project_id": null,
        "created_at": "2022-11-07 17:34:03 UTC",
        "updated_at": "2022-11-07 17:34:03 UTC",
        "template": false,
        "description": "",
        "type": "GroupLabel",
        "group_id": 2168
      }
    ]
  },
  "labels": [
    {
      "id": 11199,
      "title": "status::Done",
      "color": "#00b140",
      "project_id": null,
      "created_at": "2022-11-07 17:34:03 UTC",
      "updated_at": "2022-11-07 17:34:03 UTC",
      "template": false,
      "description": "",
      "type": "GroupLabel",
      "group_id": 2168
    }
  ],
  "changes": {
    "updated_at": {
      "previous": "2022-12-09 19:10:02 UTC",
      "current": "2022-12-09 19:10:02 UTC"
    },
    "updated_by_id": {
      "previous": 2471,
      "current": 14363
    },
    "labels": {
      "previous": [
        {
          "id": 9212,
          "title": "status::In Review",
          "color": "#ed9121",
          "project_id": null,
          "created_at": "2021-10-14 21:24:46 UTC",
          "updated_at": "2022-11-07 17:31:54 UTC",
          "template": false,
          "description": "",
          "type": "GroupLabel",
          "group_id": 2168
        }
      ],
      "current": [
        {
          "id": 11199,
          "title": "status::Done",
          "color": "#00b140",
          "project_id": null,
          "created_at": "2022-11-07 17:34:03 UTC",
          "updated_at": "2022-11-07 17:34:03 UTC",
          "template": false,
          "description": "",
          "type": "GroupLabel",
          "group_id": 2168
        }
      ]
    }
  }
}
```
</details>

We have 3 options:
1. Overload the existing `Labels` struct with fields required to unmarshal events.
   * Pros: Backward compatible.
   * Cons: May confuse developers who do not know when to use "title" vs "name" in code.
2. Create a new dedicated struct `EventLabel`
   * Pros: Avoids extraneous fields.
   * Cons: Requires a breaking change to event structs, more maintenance.
3. Write custom json `Marshal`/`Unmarshal` methods on `Labels` that marshal the "title" field into the existing "name" field.
   * Pros: Backward compatible, should be a drop-in fix for everyone.
   * Cons: May be considered too high a tech debt, doesn't scale if in the future the two schemas continue to diverge.

I'd suggest option 2, even though it's breaking. Thoughts?

**Comment by svanharmelen** [comment]
Thanks for the detailed report and suggestions @armsnyder! I'm good with option 2 as it seems that is the most correct solution. It's of course never good to have breaking changes, but for improvements like this I think it's worth it (also considering that fixing this in a codebase is extremely straight forward and should hardly take any effort)...
