### ISSUE TITLE
What is Context?

### ISSUE THREAD

**Issue by Cmaster-co** [xanzy/go-gitlab#162]
Failed to build the application: ../github.com/xanzy/go-gitlab/gitlab.go:21:2: cannot find package "context" in any of:
	/Users/apple/golang/src/github.com/xanzy/go-gitlab/vendor/context (vendor tree)
	/usr/local/go/src/context (from $GOROOT)
	/Users/apple/golang/src/context (from $GOPATH)

**Comment by svanharmelen** [comment]
See here for more details: https://golang.org/pkg/context

Also please note the README which mentions that from release 0.5.x you will need at least Go version 1.7.x

If you use an older version of Go, please checkout (or vendor) version 0.4.x which will work with older versions of Go as well.

Does this help?

**Comment by svanharmelen** [comment]
In absence of a follow up question I'll close this issue. Feel free to open it again if you do have a follow up question after all!
