### ISSUE TITLE
GetProjectApprovalRules has a wrong interface

### ISSUE THREAD

**Issue by gravis** [xanzy/go-gitlab#1628]
[`GetProjectApprovalRules`](https://pkg.go.dev/github.com/xanzy/go-gitlab#ProjectsService.GetProjectApprovalRules) has this interface:

```go
func (s *ProjectsService) GetProjectApprovalRules(pid interface{}, options ...RequestOptionFunc) ([]*ProjectApprovalRule, *Response, error)
```

which doesn't allow to pass a [ListOptions](https://pkg.go.dev/github.com/xanzy/go-gitlab#ListOptions) parameter. This is needed, because according to the [GitLab docs](https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-project-level-rules), the resource is paginated.

Since changing the signature of the function would be a breaking change, how do we deal with this kind of update?

**Comment by svanharmelen** [comment]
Unfortunately the GitLab API is changing a lot and trying to keep this package compatible with as much GitLab versions as possible is sometimes a challenge and sometimes means there is a breaking change... I'm OK with that if it solves a "bug" in the current code, which I think this is the case for this one. It's at least "fixing" a incomplete implementation...

**Comment by gravis** [comment]
@svanharmelen Could you please take a look at #1641? Thanks

**Comment by bmendric** [comment]
@gravis @svanharmelen I am incredibly confused by this update... I can mostly look past the breaking change to track GitLab's API, but the implementation on #1641 doesn't actually implement pagination - we require the parameter and do nothing with it. Am I reading this correctly?

**Comment by gravis** [comment]
@bmendric you're absolutely right, thanks for pointing out. I haven't passed the new param [here](https://github.com/xanzy/go-gitlab/pull/1641/files#diff-399dbfc23d1ac7ebbd6d572b1d6b654c9bc3e506fd0d7a439eba528af6f24a03L1786). I'll create a new PR before the end of the week to fix it. Sorry for that!

**Comment by svanharmelen** [comment]
#1653 fixed this bug @bmendric
