### ISSUE TITLE
Feature Request: Import repository from Bitbucket Server

### ISSUE THREAD

**Issue by lilyyanglt** [xanzy/go-gitlab#1629]
According to the Gitlab Docs, there's an api that allows you to import bitbucket repositories to gitlab: https://docs.gitlab.com/ee/api/import.html#import-repository-from-bitbucket-server 
But I don't believe I see this api implemented in this amazing repo, so I am hoping to create a ticket as a new feature for this repo. 
I have just started my software development journey. Perhaps I can add this api to the source code? 

I've tried the using the git.ProjectImportExport.ImportFromFile() by archiving the bitbucket repository and then using this api to import the project, but the project import fails using this method, and so it would be really helpful to be able to have this api. 

Thank you!

**Comment by svanharmelen** [comment]
Sure, feel free to take a stab at it 👍🏻 Please do make sure you first look at the style and patterns used in other places in the package and try to use the same style/patterns when possible. Thanks!

**Comment by pwlandoll** [comment]
This should be resolved with the changes in #1979.
