### ISSUE TITLE
Confidential field on Epic missing in struct

### ISSUE THREAD

**Issue by inputvalidation** [xanzy/go-gitlab#1652]
The Gitlab API allows for a confidential bool to be set on an Epic: https://docs.gitlab.com/ee/api/epics.html#new-epic. The Epic struct in https://github.com/xanzy/go-gitlab/blob/master/epics.go does not show this field. It is present in the UpdateEpicOptions struct, but it's not present in CreateEpicOptions.

Happy to work on a PR but not sure how you handle these cases typically.

**Comment by lpearson-trek10** [comment]
I see a merge for this can this be close @inputvalidation
