### ISSUE TITLE
Newbie question about Gitlab project export to S3

### ISSUE THREAD

**Issue by nikatjef** [xanzy/go-gitlab#1656]
Greetings,

  I am trying to backup our Gitlab (SaaS) projects and the documentation makes it look like we should be able to tell Gitlab to upload directly to an S3 bucket instead of downloading locally first, and maybe I am just to new, but I can't quite seem to figure out how to do so. Would some kind soul post a sample of how to do it?  I know the project.ID(s), the bucket and folder.

**Comment by svanharmelen** [comment]
Can you point me to the docs you are referring to so I can have a look? My initial guess and that this package doesn't support that call as I don't remember implementing anything that uses S3.

**Comment by svanharmelen** [comment]
Ah, check... Well I guess using the method in the GitLab client is quite straight forward, but the difficulty is probably in defining the URL. Did you follow the docs here to pre-generate the URL: https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html? As the URL will not be generated automatically by this package.
