### ISSUE TITLE
Groups.ListGroupProjects returns projects from other unrelated groups 

### ISSUE THREAD

**Issue by francovp** [xanzy/go-gitlab#1681]
Something very strange is happening when I use the `Groups.ListGroupProjects` method, it's returning projects from other groups that are not in the group I passed to it 

Example code:

```
projects, _, err := client.Groups.ListGroupProjects(groupId, &gitlab.ListGroupProjectsOptions{
	ListOptions: gitlab.ListOptions{
		Page:    page,
		PerPage: 100,
	},
	OrderBy: &[]string{"name"}[0],
	Sort:    &[]string{"asc"}[0],
})
```

I get this behaviour using version 0.72, but I update to latest 0.81 and it's the same

Any idea what this could cause this?

**Comment by svanharmelen** [comment]
Nope... I would start by trying to make the same API call using `cURL` (using the same token) to see if that results in the same response...
