### ISSUE TITLE
PipelineScheduleService::ListPipelineSchedules() always empty

### ISSUE THREAD

**Issue by larscom** [xanzy/go-gitlab#1683]
Hi, 

Somehow this function always returns an empty array and there are no errors whatsoever.
https://github.com/xanzy/go-gitlab/blob/b88a1b2a51ce442b28e0a4148c1ad50a50ec1370/pipeline_schedules.go#L67

The URL seems correct, whenever i do a CURL by hand i get the right response back.

The curl command: `curl https://gitlab.com/api/v4/projects/41540327/pipeline_schedules`

**Response**
`[{"id":369851,"description":"Schedule 1","ref":"master","cron":"0 12 * * *","cron_timezone":"Europe/Amsterdam","next_run_at":"2023-04-05T10:00:00.000Z","active":true,"created_at":"2023-04-03T19:51:22.767Z","updated_at":"2023-04-04T10:00:31.363Z","owner":{"id":13081321,"username":"gitlab.ci.dashboard","name":"Gitlab CI Dashboard","state":"active","avatar_url":"https://secure.gravatar.com/avatar/b9a841206944c648a27eea7669f452e1?s=80\u0026d=identicon","web_url":"https://gitlab.com/gitlab.ci.dashboard"}}]`

On the other hand: `PipelineScheduleService::GetPipelineSchedule()` seems to work fine.

**Comment by svanharmelen** [comment]
Could you investigate the `*Response` that is returned? Maybe print it out with something like [this](https://pkg.go.dev/net/http/httputil#DumpResponse) to see the actual API response?

**Comment by larscom** [comment]
This was my bad, somehow my projectId was set as pageNumber in the request options which obviously doesn't work.
Thanks anyway!
