### ISSUE TITLE
Add support for getting a single personal access token

### ISSUE THREAD

**Issue by justenstall** [xanzy/go-gitlab#1684]
This API route is missing from the package: https://docs.gitlab.com/ee/api/personal_access_tokens.html#get-single-personal-access-token

Especially interested in the `/personal_access_tokens/self` route: https://docs.gitlab.com/ee/api/personal_access_tokens.html#using-a-request-header

**Comment by svanharmelen** [comment]
PR's are always welcome so if you want to take a stab at it, go right ahead! Please do have a look at the rest of the code in the package and make sure you follow the existing style as much as possible...

**Comment by svanharmelen** [comment]
Fixed by #1686
