### ISSUE TITLE
BuildEvent and JobEvents are duplicate Webhook types

### ISSUE THREAD

**Issue by smit-modi** [xanzy/go-gitlab#1691]
I can see that  [BuildEvent](https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go#L45) and [JobEvent](https://github.com/xanzy/go-gitlab/blob/master/event_webhook_types.go#L341) refer to the same [Job events with "object_kind": "build"](https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#job-events) on GitLab

**Comment by svanharmelen** [comment]
While I'm open to a PR to consolidate the two structs, I'm also fine with just keeping both structs. It doesn't break anything so closing this "issue".
