### ISSUE TITLE
Add support for `allow_pipeline_trigger_approve_deployment` in `EditProject` API

### ISSUE THREAD

**Issue by gunturaf** [xanzy/go-gitlab#1693]
Set whether or not a pipeline triggerer is allowed to approve deployments.

References:
- https://docs.gitlab.com/ee/api/projects.html#edit-project
- https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111747

**Comment by svanharmelen** [comment]
If it's in the docs, feel free to open a PR to add the field...
