### ISSUE TITLE
Support for gopkg.in / Release 1.0

### ISSUE THREAD

**Issue by theduke** [xanzy/go-gitlab#171]
Right now, the API can not be used with http://gopkg.in because the version is still 0.5.

What do you think about releasing api v3 support as 1.0?
Then when the upgrade to v4 is finished you could bump the version to 2.0.

(An alternative would be to have the major version track the gitlab api version, but that would mean no breaking changes ever for one API version which is maybe not ideal).

**Comment by svanharmelen** [comment]
@theduke sorry, but I'm not going to release the current master branch to v1.0. I guess the best option to ensure repeatable builds, is to vendor this package.
