### ISSUE TITLE
Some parameters are enums, some are plain strings

### ISSUE THREAD

**Issue by kingcrunch** [xanzy/go-gitlab#1712]
I realized, that some parameters, that accepts a distinctive set of values, are strings, while others are enum-like

Example: `scope`, `source` and `status` of `ListProjectPipelines`

https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines

https://github.com/xanzy/go-gitlab/blob/master/pipelines.go#L163-L165

Is this intended? Actually, I don't think so, because it looks inconsistent
What should be the outcome? String, or enums everywhere?

A change would be a bc-break of course. It would probably make sense to unify this before `v1`?

**Comment by svanharmelen** [comment]
I prefer to keep things consistent and I also prefer to use enums if we are sure we know all possible variants 👍🏻

**Comment by kingcrunch** [comment]
Thanks for the info. I guess I can provide some pull request then :)

**Comment by Roemer** [comment]
Did you ever create a PR regarding this? I still think this would be great.
