### ISSUE TITLE
gitlab Client why not ”SetBaseURL“ method

### ISSUE THREAD

**Issue by ZhangLeishan** [xanzy/go-gitlab#1713]
```go
client, _ := gitlab.NewClient(token.AccessToken)
//client.BaseURL() == "https://gitlab.com"
//But what I expect is a custom endpoint, such as: https://gitlab.example.com

//I found `setBaseURL`, But it's not exposed to the public, it looks like carelessness, right?

```

**Comment by svanharmelen** [comment]
I guess your looking for this one: https://github.com/xanzy/go-gitlab/blob/master/client_options.go#L30 This client option lets you configure a custom base URL like this:

```go
client, _ := gitlab.NewClient(token.AccessToken, gitlab.WithBaseURL("https://gitlab.example.com"))
```

**Comment by svanharmelen** [comment]
Closing this one as I expect it is "fixed" by pointing you to the correct client option... If not feel free to reopen.

**Comment by svanharmelen** [comment]
No idea what you are trying to do, but the `gitlab.NewClient` function definitely returns 2 variables: https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L240 and `gitlab.WithBaseURL` is definitely not undefined: https://github.com/xanzy/go-gitlab/blob/master/client_options.go#L30

Are you maybe using a modified or custom version of the package?
