### ISSUE TITLE
Issue with a group milestone

### ISSUE THREAD

**Issue by WinXaito** [xanzy/go-gitlab#1749]
It is possible to link a group milestone in a project issue, and the json output is that:

```json
  {
    ...
    "milestone": {
      "id": 65,
      "iid": 27,
      "group_id": 13,
      "title": "Sprint - 2023.07 | 01",
      "description": "",
      "state": "active",
      "created_at": "2023-06-14T12:14:18.785Z",
      "updated_at": "2023-07-04T08:46:42.856Z",
      "due_date": "2023-07-07",
      "start_date": "2023-06-26",
      "expired": false,
      "web_url": "https://***/-/milestones/27"
    },
  }
```

But with this SDK, I have only access to `*Milestone` object, so I have `ProjectID` but not `GroupID`, So I'm unable to fetch the Milestone details. 

Maybe I'm doing something wrong, what do you think about that ? 

Thanks ! (otherwise, this SDK works like a charm ! 💯  )

**Comment by WinXaito** [comment]
That's not clearly indicated in the [issues API doc](https://docs.gitlab.com/ee/api/issues.html).

But, depending on which milestone is selected (current project milestone or a parent group milestone).


So, if the assigned milestone is a project milestone, we receive a [Milestone (Project)](https://docs.gitlab.com/ee/api/milestones.html) object:

```json
{
    "id": 12,
    "iid": 3,
    "project_id": 16,
    "title": "10.0",
    "description": "Version",
    "due_date": "2013-11-29",
    "start_date": "2013-11-10",
    "state": "active",
    "updated_at": "2013-10-02T09:24:18Z",
    "created_at": "2013-10-02T09:24:18Z",
    "expired": false
  }
```

Otherwise, if the assigned milestone is a group milestone, we receive a [Milestone (Group)](https://docs.gitlab.com/ee/api/group_milestones.html) object:

```json
{
    "id": 12,
    "iid": 3,
    "group_id": 16,
    "title": "10.0",
    "description": "Version",
    "due_date": "2013-11-29",
    "start_date": "2013-11-10",
    "state": "active",
    "updated_at": "2013-10-02T09:24:18Z",
    "created_at": "2013-10-02T09:24:18Z",
    "expired": false,
    "web_url": "https://gitlab.com/groups/gitlab-org/-/milestones/42"
  }
```


------------

>  feel free to create a PR to add them to the struct

Yes, but I'm not sure on what is the best.

As I can see, adding a field `MilestoneGroup *MilestoneGroup` ([here](https://github.com/xanzy/go-gitlab/blob/master/issues.go#L95) to issue is the best deal, and feed the correct one.

That implies to do something [here](https://github.com/xanzy/go-gitlab/blob/master/issues.go#L141) to assign the correct object... But how to know if it's a project or group milestone ? The only thing is to check if a properties called `projectID` or `groupID` is present.


Another solution is to add the field `GroupID` to the `Milestone` object, but that doesn't correspond exactly to the Gitlab API Documentation.

**Comment by svanharmelen** [comment]
It indeed doesn't correspond exactly to the GitLab API documentation, but in this case I guess it makes the most sense as the other suggested solution doesn't seem feasible...
