### ISSUE TITLE
missing "owner" for ProjectCreationLevelValue in types.go

### ISSUE THREAD

**Issue by sgtpham** [xanzy/go-gitlab#1761]
missing the options for owner in the ProjectCreationLevelValue in the types.go const definition

**Comment by svanharmelen** [comment]
Feel free to create a PR for adding the missing options (please checkout [CONTRIBUTING.md](https://github.com/xanzy/go-gitlab/blob/master/CONTRIBUTING.md)) 👍🏻

**Comment by svanharmelen** [comment]
In that case I will close the issue 👍🏻
