### ISSUE TITLE
Epic Boards

### ISSUE THREAD

**Issue by giuliohome** [xanzy/go-gitlab#1763]
Do you have any plans to implement boards for epics? They should be very similar to Group Issue Boards. Or perhaps should I consider sending a pull request for that? Thank you.

**Comment by svanharmelen** [comment]
Yup, go right ahead... [CONTRIBUTING.md](https://github.com/xanzy/go-gitlab/blob/master/CONTRIBUTING.md)

**Comment by giuliohome** [comment]
Just to show you how I am progressing, this is the implementation of the `ListGroupEpicBoards` function.

https://github.com/giuliohome/go-gitlab/commit/f077f25e9578c74c027ef5fb875c7731e854907d

In case this preliminary check is not helpful, feel free to ignore my comment. After completing the other functions, I will proceed with a merge request shortly after.

**Comment by giuliohome** [comment]
Sadly, I'm afraid that the **creation/update** is implemented only via **GraphQL** but not as REST... in that case I wonder whether it makes sense to merge only the list function...

**Comment by svanharmelen** [comment]
This was added in #1764
