### ISSUE TITLE
Wondering any support for User delete  with hard-delete option

### ISSUE THREAD

**Issue by rockburning** [xanzy/go-gitlab#1790]
this project is super great, i was wondering if there is any plans to update the deltete user api to support hard delete ;thanks a lot .    https:docs.gitlab.com/ee/api/users.html#user-deletion ;

**Comment by svanharmelen** [comment]
A PR to add the option is certainly welcome if your up for it. Please check [CONTRIBUTING.md](https://github.com/xanzy/go-gitlab/blob/master/CONTRIBUTING.md) for some basic guidelines...
