### ISSUE TITLE
Wondering basicAuth will automatic renew the access token when using the client? 

### ISSUE THREAD

**Issue by rockburning** [xanzy/go-gitlab#1797]
"I would like to ask if using xanzy/go-gitlab will automatically handle OAuth 2.0 renewal. If using Basic Authentication with the same client.
the problem is that when I use the same client  with diffrent goroutine; my gitlab sever(in docker ) it tells me that "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."

And my situation is that i have admin user's name and password, I want to create user or delete user using the same client with basic Auth. Any help would be appreciated. Thanks a lot

**Comment by svanharmelen** [comment]
It should, according to this code: https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L807

**Comment by svanharmelen** [comment]
Closing as I think the question is answered. Feel free to reopen if not...
