### ISSUE TITLE
Return response body when decoding into json fails

### ISSUE THREAD

**Issue by somtochiama** [xanzy/go-gitlab#1799]
It would be great to return the response body along with the error when decoding the response from the API fails.
Currently, [the decoding error is returned](https://github.com/xanzy/go-gitlab/blob/0d372da030bf8100144fe1bb6a215ee87ba39dc2/gitlab.go#L835) and it masks the actual response.

This is an example of the error returned:
```
invalid character '<' looking for beginning of value
```

I am happy to contribute a PR !

**Comment by svanharmelen** [comment]
Hi @somtochiama 👋🏻 If you look at [this](https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L839) line you see that we actually do send the raw response as well as the error. Or did I misunderstand your question?

**Comment by somtochiama** [comment]
@svanharmelen I missed that.
Thanks! I will close this out then.
