### ISSUE TITLE
Build variables: support protected flag

### ISSUE THREAD

**Issue by totallyunknown** [xanzy/go-gitlab#181]
GitLab 9.3 introduce protected build variables. In 9.3.0 this field is mandatory (documentation says something else). I've created https://gitlab.com/gitlab-org/gitlab-ce/issues/34282 to fix GitLab here. 

But anyway, go-gitlab should support the new flag.

**Comment by svanharmelen** [comment]
Fixed by commit 0be61ab0655bfd6f16f956147b0ff8df337db9ad I will only fix this in the v4 branch as that one is related to the newer API...

**Comment by totallyunknown** [comment]
Thanks.
