### ISSUE TITLE
Add: Delete project artifacts

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [xanzy/go-gitlab#1816]
API: https://docs.gitlab.com/ee/api/job_artifacts.html#delete-project-artifacts

[Introduced](https://gitlab.com/gitlab-org/gitlab/-/issues/223793) in GitLab 14.7

**Comment by xuxiaowei-com-cn** [comment]
https://github.com/xanzy/go-gitlab/pull/1815

**Comment by svanharmelen** [comment]
Closed by #1815
