### ISSUE TITLE
Add: Appearance API

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [xanzy/go-gitlab#1819]
API: https://docs.gitlab.com/ee/api/appearance.html

[Introduced](https://gitlab.com/gitlab-org/gitlab/-/issues/16647) in GitLab 12.7.

The appearance API allows you to maintain the appearance of GitLab as if you’re using the GitLab UI at `/admin/appearance`. The API requires administrator privileges.

**Comment by svanharmelen** [comment]
Already fixed by #1820
