### ISSUE TITLE
Implement Username to Username helper

### ISSUE THREAD

**Issue by Smithx10** [xanzy/go-gitlab#182]
While trying to expand the terraform gitlab provider [https://github.com/terraform-providers/terraform-provider-gitlab](url) I discovered that the gitlab-api only accepts UserID ints, for Adding GroupMembers, GetUser etc.    

I have added a helper function into the terraform provider,  but am sure I am not the only person that will confront this issue and think we could add a GetUserID Helper to go-gitlab.

Basic function is to Take a Username (Which I discovered you can't have duplicates of in gitlab, so feel this functionality honestly should just be added to their ruby api) and Return that UserNames UserID to be consumed by AddGroupMemberOptions, GetUser etc.  

```
// function to convert usernames to userids
func GetUserID(un string, meta interface{}) (int, error) {
	client := meta.(*gitlab.Client)

	l := &gitlab.ListUsersOptions{
		Username: gitlab.String(un),
	}

	u, _, err := client.Users.ListUsers(l)
	if err != nil {
		return fmt.Printf("%v", err)
	}
	if un != u[0].Username {
		return fmt.Printf("%v", un)
	}

	return u[0].ID, nil
}
```

**Comment by svanharmelen** [comment]
I fully understand how this could add value, but for now I would like to stay away from adding custom helper functions and only support the functionality that the Gitlab API itself offers.

At least for the time being...
