### ISSUE TITLE
Use of deprecated Group/Project Label API

### ISSUE THREAD

**Issue by idwagner** [xanzy/go-gitlab#1823]
The current API methods for Delete and Update labels for projects and groups are using the deprecated api to reference the label by name rather than label ID. 

It looks like this would be a breaking change to go-gitlab to modify in place since the respective options parameters would need an id field added to the type. I'm not sure how this project handles breaking changes. Perhaps for now, new update/delete functions could be created (i.e. DeleteGroupLabelById) and the old ones removed at a later date?

**Comment by ysmilda** [comment]
Running into this as well. 

Another option I see would be to add the `label_id` to the existing struct and switch based on the existence of that. 

I'm going to create a pull request which at least matches the latest API specs and we can see from there
