### ISSUE TITLE
Stop environment endpoint has a force option, how to introduce it to go-gitlab?

### ISSUE THREAD

**Issue by inputvalidation** [xanzy/go-gitlab#1836]
https://docs.gitlab.com/ee/api/environments.html#stop-an-environment has a "force" option which is currently not exposed in go-gitlab. I'm happy to submit a PR but unsure if I can introduce this and maintain backwards compatibility with the existing function signature.

Any pointers on how the project would like to see this get implemented?

**Comment by svanharmelen** [comment]
I see... We need to introduce an option struct for this... I'm OK to make a breaking change for this, so feel free to create a PR.

**Comment by inputvalidation** [comment]
@svanharmelen I have created the PR, let me know what you think :)
