### ISSUE TITLE
Correct Json.Marshal for issue labels

### ISSUE THREAD

**Issue by tkschmidt** [xanzy/go-gitlab#1839]
Labels for issues (epics are fine) are not converted to the same JSON representation as a gitlab API would provide it (see [docs](https://docs.gitlab.com/ee/api/issues.html#list-issues)). The custom MarshalJson [here](https://github.com/xanzy/go-gitlab/blob/3e35f87026dc981f6e482534dce664c69844493f/issues.go#L178) converts it to a comma-seperated string when using `Json.Marshal`.

This comma-seperated list is not compatible with the provided [UnmarshalJSON](https://github.com/xanzy/go-gitlab/blob/3e35f87026dc981f6e482534dce664c69844493f/issues.go#L182C1-L188).

## How to reproduce it

1. Request any kind of `gitlab.Issue`
2. export to a file 
```go
  func WriteIssueFile(issuesReport []IssueReport) {

	// Marshal the struct to JSON
	jsonData, err := json.MarshalIndent(issuesReport, "", "  ")
	if err != nil {
		fmt.Println("Error marshaling struct to JSON:", err)
		return
	}

	// Write JSON data to a file
	err = ioutil.WriteFile("issues.json", jsonData, 0644)
	if err != nil {
		fmt.Println("Error writing to JSON file:", err)
		return
	}

}
```
3. Results are  e.g. "labels": ["Communicate,Refine"]. All labels are always a list with exactly 1 entry (empty string "" if no label is provided

## How to fix it

Simplify the Marshal function as provided in the merge request #1840

**Comment by svanharmelen** [comment]
This one is closed by #1840
