### ISSUE TITLE
Delete issue notes?

### ISSUE THREAD

**Issue by Rukenshia** [xanzy/go-gitlab#185]
I can't seem to find a function to delete a note. I hope I am just blind, so can you help me maybe?

**Comment by svanharmelen** [comment]
Strangely enough it seems you're absolutely right... Seems those functions are indeed missing. Will try to add them later this week. Or, if you feel up to adding them yourself, I would of course welcome any PR's adding the missing functions.

Thanks for reporting this issue!

**Comment by svanharmelen** [comment]
@Rukenshia should be fixed in master now...

**Comment by Rukenshia** [comment]
awesome, thanks a lot @svanharmelen :)
