### ISSUE TITLE
API Broken with the update from v0.94.0 to v0.95.0

### ISSUE THREAD

**Issue by zbindenren** [xanzy/go-gitlab#1852]
Hi

In the Update `MergeRequestOptions` struct the `AssigneeID` got changed to `LabelOptions` instead of an int:

```go
type UpdateMergeRequestOptions struct {
...
	AssigneeID         *LabelOptions `url:"assignee_id,omitempty" json:"assignee_id,omitempty"`
...
}
```

Is this intentional? If I check the api specification it is described as integer: https://docs.gitlab.com/ee/api/merge_requests.html#update-mr

```
assignee_id	integer	No	The ID of the user to assign the merge request to. Set to 0 or provide an empty value to unassign all assignees.
```

If this is intentional, then the usage of the API is a little cumbersome now. I have to get the id of the user, then convert it to a list of strings with one entry.

**Comment by svanharmelen** [comment]
Fixed in `v0.95.1`
