### ISSUE TITLE
Feature request: merge request draft notes support

### ISSUE THREAD

**Issue by earl-warren** [xanzy/go-gitlab#1861]
A short reminder that support for the merge request draft notes API is in the TODO list

https://docs.gitlab.com/ee/api/draft_notes.html

**Comment by svanharmelen** [comment]
Not sure what the purpose of this issue is? Is this a feature request, bug report, personal reminder 😂 Please let me know so I can respond and/or close this issue appropriately.

**Comment by earl-warren** [comment]
It is a feature request.

**Comment by svanharmelen** [comment]
Check... PRs are always welcome if you want something to be added 👍🏻

**Comment by earl-warren** [comment]
Thanks for fixing the title. I do not plan to propose a pull request any time soon but I appreciate the gentle nudge.

**Comment by harrisoncramer** [comment]
I'd like to work on this. I'll open up an MR in a bit, or if I get stuck.

**Comment by vntw** [comment]
@svanharmelen seems like this issue can be closed, implemented in #1905 🎉

**Comment by earl-warren** [comment]
@harrisoncramer well done :+1:
