### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by heidiberry** [xanzy/go-gitlab#1929]
Hi @svanharmelen, could you create a new release tag please?

How would you feel about automating the tag creation either on every new change on main or on a schedule (if there have been changes)?

**Comment by svanharmelen** [comment]
I prefer to create a release manually for the time being. There are a couple of open PR's that I want to get merged first, after that I will create a new release again.

**Comment by svanharmelen** [comment]
Released a version yesterday...
