### ISSUE TITLE
Erroring on 204 response code

### ISSUE THREAD

**Issue by TreyLawrence** [xanzy/go-gitlab#194]
Right now only 200, 201, and 304 are supported response codes:
https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L475-L477

But after deleting a user, I'm getting a 204 (no content), which is not an error.

**Comment by TreyLawrence** [comment]
I'm using the `gitlab/gitlab-ce:latest` docker image, which is using `GitLab Community Edition 9.4.3 b125d21`

**Comment by svanharmelen** [comment]
The 204 code is already added to the `f-api-v4` branch. This branch is used to prepare full API V4 support which contains some backwards incompatible changes. I hope to be able to finish that branch soon and merge it into master, but for now please just manually select/use that branch. Thx!
