### ISSUE TITLE
Deprecated Fields in README example

### ISSUE THREAD

**Issue by wcolburn** [xanzy/go-gitlab#1945]
In both the README's example section and in examples/projects.go, "gitlab.CreateProjectOptions" has two deprecated fields: MergeRequestsEnabled and SnippetsEnabled. 

I believe this should be updated so the example code is accurate and easy to use for new users.

**Comment by svanharmelen** [comment]
Feel free to make a PR to update the docs and example 👍🏻

**Comment by vntw** [comment]
This can be closed with the merge of #1949 I think
