### ISSUE TITLE
DELETE EOF

### ISSUE THREAD

**Issue by hellojukay** [xanzy/go-gitlab#195]
i am using f-api-v4 branch, when delete a file, the go-gitlab return error : EOF.
my golang version is 1.8.3, my os is osx.

**Comment by svanharmelen** [comment]
I would need a bit more details in prder to be able to help. Like a short example code showing which calls you make, and the error output you see. Thx.

**Comment by hellojukay** [comment]
<img width="844" alt="gitlab" src="https://user-images.githubusercontent.com/10371891/29703604-c98f22dc-89a8-11e7-8168-36fea35c8827.png">
this is my code , in order to fix this "bug", i add the EOF check,it works. In fact, when return EOF, go-gitlab also delete file success.

**Comment by svanharmelen** [comment]
And what response do you get when you try this with a curl cms, like shown here: https://gitlab.com/gitlab-org/gitlab-ce/blob/9-5-stable/doc/api/repository_files.md#delete-existing-file-in-repository

Does that give the same response?

And/or, if you look at the second return value (which is the response), you could check the content of `resp.Body` and post that back as well... Thx!
