### ISSUE TITLE
Feature request: add support for Service Accounts

### ISSUE THREAD

**Issue by PascalRoose** [xanzy/go-gitlab#1964]
Recently the GitLab team has added CRUD actions for Service Accounts. [See GitLab Issue](https://gitlab.com/gitlab-org/gitlab/-/issues/416729).

I would like to contribute to have these new endpoints added in go-gitlab.

**Comment by svanharmelen** [comment]
Feel free to contribute, but please follow the [guidelines](https://github.com/xanzy/go-gitlab/blob/main/CONTRIBUTING.md) 👍🏻

**Comment by heidiberry** [comment]
Has this issue been resolved by https://github.com/xanzy/go-gitlab/pull/2005?

**Comment by svanharmelen** [comment]
I think so... I'll close it for now, feel free to reopen if something is still missing.
