### ISSUE TITLE
Ability to immediately delete projects in Premium/Ultimate tiers

### ISSUE THREAD

**Issue by heidiberry** [xanzy/go-gitlab#2008]
For the Premium and Ultimate tiers, by default projects are not deleted immediately on request. You can override this by passing two options to the API, full_path and permanently_remove: https://docs.gitlab.com/ee/api/projects.html#delete-project.

Prior to these fields being added to the API, there were no custom options used by the delete project endpoint. Therefore, the function for this has only two parameters: https://github.com/xanzy/go-gitlab/blob/main/projects.go#L1166.

How would you go about adding a DeleteProjectOptions parameter whilst maintaining backwards compatibility?

**Comment by svanharmelen** [comment]
The GitLab API changes a lot so it's pretty hard to keep this package up-to-data without breaking some of the API's every now and then. However annoying it may be, I don't really see how else to fix these issue without creating a massive additional maintenance burden. So I'm good with adding an option struct argument to the delete project method.
