### ISSUE TITLE
Add "maintenance note" as an option while creating a new runner

### ISSUE THREAD

**Issue by shashinandan** [xanzy/go-gitlab#2014]
When creating a new runner, there is an option in Gitlab API to add "maintenance note".
https://docs.gitlab.com/ee/api/runners.html#create-a-runner

-----
maintenance_note | string | no | Free-form maintenance notes for the runner (1024 characters).
-----

Please add it as part of the runner creation payload.
https://github.com/xanzy/go-gitlab/blob/main/runners.go#L36

**Comment by svanharmelen** [comment]
Feel free to make a PR is your up for it 👍🏻
