### ISSUE TITLE
Add endpoint for update-pipeline-metadata

### ISSUE THREAD

**Issue by alexpts** [xanzy/go-gitlab#2026]
Docs: https://docs.gitlab.com/ee/api/pipelines.html#update-pipeline-metadata

**Comment by alexpts** [comment]
Prepared PR - https://github.com/xanzy/go-gitlab/pull/2051

**Comment by alexpts** [comment]
Could you please release a new version with new endpoint?

**Comment by svanharmelen** [comment]
Will do soon... Closing this one as finished.
