### ISSUE TITLE
Proposal: Support `context.Context` for all methods

### ISSUE THREAD

**Issue by flc1125** [xanzy/go-gitlab#2052]
This component is very easy to use, but I currently encounter a problem. When I was doing link tracing, I couldn't bind it to other links due to the lack of `context.Context`.

So I suggest: all methods support `context.Context`.

> If support is needed, I can assist in handling it and submit a PR.

------

This is one of my Trace messages, it is separate.

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/1ad9cba2-2ffe-4a33-9752-4b3b0d494141">

**Comment by svanharmelen** [comment]
Please check this issue: https://github.com/xanzy/go-gitlab/issues/1944 My standpoint did not change as this would be a very, very big breaking change. So still not really open to this, sorry.
