### ISSUE TITLE
Can not find support for "GET /users/:user_id/projects"

### ISSUE THREAD

**Issue by dongmx** [xanzy/go-gitlab#208]
GitLab API document is here: `https://docs.gitlab.com/ee/api/projects.html`.
It seems that this lib not implemented `GET /users/:user_id/projects`.

**Comment by svanharmelen** [comment]
No I guess you're right... If you're up for adding it, by all means create a PR and have a go at it 👍

**Comment by fibers** [comment]
Damned, so you shouldn't publish the document with this feature ........ @svanharmelen

**Comment by BlackSpadeJack** [comment]
yeah，why the official doc is so ugly @fibers

**Comment by svanharmelen** [comment]
I’m sorry @fibers, but what exactly do you mean with your comment?

**Comment by dongmx** [comment]
@fibers @svanharmelen I'v already create a PR about this. https://github.com/xanzy/go-gitlab/pull/234

**Comment by svanharmelen** [comment]
I
