### ISSUE TITLE
i have just a file path , how can i get the cureent version string?

### ISSUE THREAD

**Issue by hellojukay** [xanzy/go-gitlab#210]
i have just a path , how can i get the cureent version string?

**Comment by svanharmelen** [comment]
@hellojukay a little bit more context is needed here. Can you give some more details of what you are doing and what you are trying to achieve? Then maybe I can point you in the right direction...

**Comment by hellojukay** [comment]
this is my filepath in git: deploy_tomcat_test/devtest/default/app.yaml
this id my proejct name: dida_config_repository
this is my groupname: foundation


i want to no the lastest commit id of this file, so, i call this function 
func (s *CommitsService) GetCommit(pid interface{}, sha string, options ...OptionFunc) (*Commit, *Response, error) 

but it response 404, like this:

ERRO[0001] GET http://gitlab.didapinche.com/api/v4/projects/dida_config_repository/master/repository/commits/deploy_tomcat_test/devtest/default/app.yaml: 404 {error: 404 Not Found}  file=logger.go func="logrus.(*Logger).Error" line=219

@svanharmelen

**Comment by svanharmelen** [comment]
And what do you put into the function call as `pid` param value? I think it should be `foundation/dida_config_repository`.

**Comment by hellojukay** [comment]
@svanharmelen i try it too,but it still not work!

ERRO[0018] GET http://gitlab.didapinche.com/api/v4/projects/foundation/dida_config_repository/master/repository/commits/deploy_tomcat_test/devtest/default/app.yaml: 404 {error: 404 Not Found}  file=logger.go func="logrus.(*Logger).Error" line=219

**Comment by svanharmelen** [comment]
Can you show the snipped of code that is calling `GetCommit`?

**Comment by hellojukay** [comment]
@svanharmelen thx every much, i made it , just kown i see the gitlab doc,it help me .thx again! thank you!!!

**Comment by svanharmelen** [comment]
Cool! Good to hear it works now... 👍
