### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by roidelapluie** [xanzy/go-gitlab#216]
https://docs.gitlab.com/ce/api/protected_branches.html

Protected branches is a new api endpoint introduced recently.

I'd love to see it supported in this project ; that way downstream project https://github.com/terraform-providers/terraform-provider-gitlab could use it.

**Comment by michaellihs** [comment]
Think this one should be fixed by !288

@svanharmelen think you can close this issue / mark it as resolved

**Comment by svanharmelen** [comment]
Fixed in PR #288. Thanks @michaellihs!
