### ISSUE TITLE
Can not delete a group parent

### ISSUE THREAD

**Issue by roidelapluie** [xanzy/go-gitlab#220]
The omitempty here means that we never pass parent_id: null in the JSON.
So we can not remove a parent_id at the moment.

I have no idea how we could deal with that.

https://github.com/xanzy/go-gitlab/blob/d11d546f58c67430417f975b453f44f280474a4d/groups.go#L119

**Comment by roidelapluie** [comment]
closing because we can not change the parent id with api anyway

**Comment by svanharmelen** [comment]
Yeah... That's indeed an interesting case. I need to think about this and see if I can come up with a solution...
