### ISSUE TITLE
Undefined: gitlab.VisibilityLevel

### ISSUE THREAD

**Issue by kairen** [xanzy/go-gitlab#226]
Today I want to run a example to control my GitLab, but I follow this repo README to create a simple code, while running code it will get a few error as below message:
```sh
$ go run client.go
# command-line-arguments
./client.go:19: undefined: gitlab.VisibilityLevel
./client.go:31: undefined: gitlab.VisibilityLevel
```

I see the `VisibilityLevel` has been changed to `Visibility`. Therefore, I replace `VisibilityLevel` with `Visibility `, but it will get new error as below:
```sh
$ go run client.go
2017/10/14 16:00:21 POST http://example.com/api/v3/projects/678/snippets: 400 {error: visibility_level is missing, visibility_level does not have a valid value}
exit status 1
```

**Comment by svanharmelen** [comment]
@kairen which version of Gitlab are you using? It seems that you are talking against an older version that doesn’t support the latest V4 API.

Check out the README.md as it mentions something about compatibility. If you need support for the V3 API you should use the `f-api-v3` branch.

**Comment by kairen** [comment]
@svanharmelen Sorry, I missed this mentions in README.md!

**Comment by svanharmelen** [comment]
No problem :+1:
