### ISSUE TITLE
Support for avatar option in create/edit project

### ISSUE THREAD

**Issue by Bouwdie** [xanzy/go-gitlab#229]
https://docs.gitlab.com/ce/api/projects.html#edit-project -> Currently the CreateProjectOptions does not contain an entry to send along an `avatar`, even thought it is supported in the API. 
Would be great if we could upload an avatar :smile_cat: 

Maybe we can also directly support the other new params `ci_config_path` and `tag_list`?

**Comment by svanharmelen** [comment]
@Bouwdie I am about to add the missing options, but it's unclear from the docs that type of info is expected for the `avatar` field. As the type is `mixed` and it's not called `avatar_url` like in other locations of the API.

So do you know what it expects here? Does it expect an URL, or the image itself (so a string or bytes)?

**Comment by Bouwdie** [comment]
@svanharmelen I totally agree with the confusion there, the documentation is lacking there. I will check tonight what setup works. Otherwise we could log an issue at Gitlab to get clarification on the field.

**Comment by svanharmelen** [comment]
👍  Thx!

**Comment by Bouwdie** [comment]
Sorry for the late reply, i dove into the code of the ce edition and found out they use a file upload, and not a url. 

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/api/projects.rb#L28
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/spec/requests/api/projects_spec.rb#L477

This means we have to send multipart i guess? Maybe you see a way to fit this nicely in the current client structure? https://matt.aimonetti.net/posts/2013/07/01/golang-multipart-file-upload-example/

**Comment by Bouwdie** [comment]
In the original merge request i also found the following curl example of an avatar upload: 
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/12143

`curl --request PUT --header "PRIVATE-TOKEN: XXXXXXXXX" --form "avatar=@/tmp/test.jpg" https://my-gitlab-instance.io/api/v4/users/2
`

**Comment by Bouwdie** [comment]
I tried to upload a file and a json part, but no luck. 

> `▶ curl --request POST --header "PRIVATE-TOKEN: xxx" --form "avatar=@/somefile" -F "{\"name\": \"else\"};type=application/json" http://localhost:9090/api/v4/projects
> 
> {"error":"name, path are missing, at least one parameter must be provided"}% `

when we use form fields instead of json it does work (expected).


> `▶ curl --request POST --header "PRIVATE-TOKEN: xxx" --form "avatar=@/somefile" -F "name=wow" http://localhost:9090/api/v4/projects 
> 
> {"id":3, ...  `

gowise we sould be looking at something like this then :crying_cat_face:

`body := &bytes.Buffer{}
writer := multipart.NewWriter(body)
part, err := writer.CreateFormFile("avatar", filepath.Base(path))
if err != nil {
	log.Fatal(err)
}
_, err = io.Copy(part, file)

writer.WriteField("name", "wow")
err = writer.Close()
fmt.Print(body)
if err != nil {
	log.Fatal(err)
}

req, err := http.NewRequest("POST", uri, body)`
I guess we do not want to send a multipart form for all api actions.
Splitting the action into a file upload part and the json data might be an idea.
Looking forward to your suggestions!

**Comment by svanharmelen** [comment]
Instead of the line `req, err := http.NewRequest("POST", uri, body)` you could something like this instead:

```go
	req, err := s.client.NewRequest("POST", u, nil)
	if err != nil {
		log.Fatal(err)
	}

	req.Body = ioutil.NopCloser(body)
```

So first create a new request (like we currently do for every API endpoint) and then set the body to the created multipart...

**Comment by Bouwdie** [comment]
So I finally got some time to look into this feature :sake:  The form multipart seems to be an option but a complex one. I find difficulties integrating this in the client NewRequest, which currently passes a simple json body as POST body. To go the form multipart way we have to figure out how to do a multipart post with a JSON and an image part. Or serialize to form values instead of json :thinking: 

```
	if method == "POST" || method == "PUT" {
		bodyBytes, err := json.Marshal(opt)
		if err != nil {
			return nil, err
		}
		bodyReader := bytes.NewReader(bodyBytes)

		u.RawQuery = ""
		req.Body = ioutil.NopCloser(bodyReader)
		req.ContentLength = int64(bodyReader.Len())
		req.Header.Set("Content-Type", "application/json")
	}
```
Another challenge would then be detect which parts of the `opt` variable are files (instance of Reader?) and which parts are json/form-fields. 

I also have seen some blog posts (not to Gitlab) where the file is actually passed as base64 encoded string in the json which would make our lives a bit easier i guess but comes with a price. + we don't know if the server-side implementation works like this.

What do you think would be the best way to go about this? :rescue_worker_helmet:

**Comment by surajbarkale** [comment]
I wrote a python script to perform this using gitlab-python module and I was able to get this to work with multipart form encoding. See the [requests library](https://github.com/kennethreitz/requests/blob/bedd9284c9646e50c10b3defdf519d4ba479e2c7/requests/models.py#L110) for python code which creates the request body. 

I used following code if you want to step through:

```python
import gitlab
from gitlab.types import FileAttribute

gl = gitlab.Gitlab('https://gitlab.instance`, private_token='XXXXX')
avatar_file = 'path/to/avatar.jpg'

# Work around the bug in gitlab module which does not return name
def createFileAttributeNamed(name):
    class CustomFileAttribute(FileAttribute):
        def get_file_name(self, attr_name=None):
            return name.split('/')[-1]
    return CustomFileAttribute

# Force project object to treat avatar as file upload
gl.projects._types = {'avatar': createFileAttributeNamed(avatar_file)}

gl.projects.create({
    'name': 'project-with-avatar',
    'avatar': open(avatar_file, 'b').read(),
})
```

**Comment by surajbarkale** [comment]
We could add a `client.NewFormRequest(path string, opt interface{}, fileFields []string) (*http.Request, error)` method. This method should convert `opt` to `map[string][]string` using [gorilla/schema](https://github.com/gorilla/schema) and replace all fields mentioned in `fileFields` with actual files.

**Comment by binlab** [comment]
It would be nice to have this feature. And even not just for `Projects` but for `Users` and `Groups` too.

@Bouwdie @svanharmelen does it any moves in this direction?

**Comment by mitar** [comment]
I would suggest that we instead make `NewFormRequest` allow for `opt` to implement `io.Reader` and if such value is provided, then we use form multipart to send the data. This would match `Do` which has a special case if `v` implements `io.Writer`.

**Comment by mitar** [comment]
It seems that [the issue is that it is not possible to remove the avatar](https://gitlab.com/gitlab-org/gitlab/-/issues/348498).

**Comment by mitar** [comment]
I made https://github.com/xanzy/go-gitlab/pull/1318 to address this issue.

**Comment by Bouwdie** [comment]
Hey @mitar thanks for your time working on this issue. I think the function to upload solely an avatar is a nice addition. I have played around with the idea to add readers for the create/update project/user/groups and when an object with a reader property gets passed (reflection I suppose) switch from json to a form multipart to do it all in one call.
