### ISSUE TITLE
branch need url encode

### ISSUE THREAD

**Issue by lincolnzhou** [xanzy/go-gitlab#233]
https://github.com/xanzy/go-gitlab/blob/e6f4b9d42e48b5dd1201aa16949b4034213ad50e/branches.go#L91

Recently, I used git flow in the development process, and there was a branch that like this format: feature/test, which resulted in the  query branch information api 404 not found.

I read the offical document and found that the branch and project name need url encode. Specific documents are as follows:
https://docs.gitlab.com/ce/api/branches.html#get-single-repository-branch

**Comment by zaquestion** [comment]
Unfortunately even url encoding the branch doesn't allow this to work, it seems to be bug/limitation in the Gitlab API. I've opened an issue here: https://gitlab.com/gitlab-org/gitlab-ce/issues/41740

**Comment by zaquestion** [comment]
@svanharmelen Depending on the response (if any) to that issue, do you think its worth detecting slashes and falling back to `https://gitlab.com/api/v4/projects/<pid>/branches` to mimic the API?

**Comment by zaquestion** [comment]
false alarm, I'm full of it :sweat_smile:

**Comment by svanharmelen** [comment]
:+1:
