### ISSUE TITLE
field "work_in_progress "  type mismatch

### ISSUE THREAD

**Issue by yangshenhuai** [xanzy/go-gitlab#238]
If I request the below api directly 
 http://ip/api/v3//projects/{project_id}/merge_requests
and if there's a WIP merge request ,the response will like below
{
...
        "work_in_progress": 0,
}

As your can see the work_in_progress is a int ,but in merge_request.go , the you defined it as bool type..
type MergeRequest struct {
...
	WorkInProgress bool   `json:"work_in_progress"`
}
so there'll be error when try to get the merge request using this method gitlabClient.MergeRequests.ListProjectMergeRequests(projectId, mrOpt)

error:
&json.UnmarshalTypeError{Value:"number", Type:(*reflect.rtype)(0x665cc0), Offset:820, Struct:"MergeRequest", Field:"work_in_progress"}

**Comment by svanharmelen** [comment]
@yangshenhuai when I look at the docs over [here](https://docs.gitlab.com/ce/api/merge_requests.html) all the examples show this field as a bool:

![image](https://user-images.githubusercontent.com/4171547/32406216-9ad3adc4-c174-11e7-9d20-34896091bdd6.png)

So I'm not sure what to make of this report. Could you tell me against what version of Gitlab you run your test? And could you maybe send me your curl output from a query against your own Gitlab server and to gitlab.com?

Hopefully that will give some insights in what is going on. Thanks!

**Comment by yangshenhuai** [comment]
@svanharmelen  yeah, I also checked the document ,and found out the work_in_progress is type bool.
my gitlab version is 8.0.5 , maybe version is too old.

**Comment by svanharmelen** [comment]
Check... Then I'll close this one for now.

Feel free to reopen the issue if you get any other or new insights!
