### ISSUE TITLE
Emoji Award API

### ISSUE THREAD

**Issue by Lorac** [xanzy/go-gitlab#240]
Is this missing in the current state of the project? It looks like it.

https://docs.gitlab.com/ce/api/award_emoji.html

**Comment by svanharmelen** [comment]
@Lorac yes, it seems this API is currently not covered...

**Comment by gjnoonan** [comment]
I'm happy to work on this 👍

**Comment by svanharmelen** [comment]
@gjnoonan feel free to do so... PR's are much appreciated! :wink:

**Comment by gjnoonan** [comment]
@svanharmelen Whilst writing the code for this, I pondered two different ways. One, follows the same pattern as the rest of the library, where AwardEmoji has it's own service

```go
type AwardEmojiService struct {}
type AwardEmoji struct {}

func (as *AwardEmojiService) ListIssueAwardEmoji(pid interface{}, issue int, options ...OptionFunc) ([]*AwardEmoji,*Response, error) {
```
and it's usage ..
```go
b, _, err := git.AwardEmoji.ListIssueAwardEmoji(37, 21)
for _, ae := range b {
	fmt.Printf("%d\t%d\t%s\t%s\n", ae.ID, ae.AwardableId, ae.Name, ae.User.Username)
}
```

Although this provides consistency with the rest of the library, because of the slight difference in API for Award Emoji, I wondered if it was more natural to call the Method on the Issue/MergeRequest/Snippet interfaces ?

```go
func (i Issue) ListAwardEmoji() []*AwardEmoji {}
```
which would be used as such:
```go
issue, _ , _ :=git.Issues.GetIssue(37, 45)
ae, err := issue.ListAwardEmoji()
```

Happy to discuss and take direction, to which you would prefer to merge.

**Comment by svanharmelen** [comment]
Yeah, this is a really good question... In the end my goal is to make this package follow (as much as possible) how the docs are organized, as I believe that will help people to easily find the things they are looking for. So in this case I think we should go for the `AwardEmoijService`, even through the other option would definately be a good solution as well...

**Comment by gjnoonan** [comment]
Thanks for getting back to me @svanharmelen I will put up a PR shortly

**Comment by svanharmelen** [comment]
Thanks 👍

**Comment by zaquestion** [comment]
@gjnoonan are you still working on this? If not would you mind pushing up what you've got? I'm thinking about finishing it up to use in [lab](https://github.com/zaquestion/lab)

**Comment by Lorac** [comment]
@zaquestion Which endpoint do you need the most? I probably can write the endpoint you need to most pretty fast.

**Comment by Lorac** [comment]
@zaquestion  I added a PR. You can look at it if you want.

**Comment by zaquestion** [comment]
@Lorac thanks! Not familiar with the available endpoints off the top of my head. I'm most interested in thumbs up/down functionality for merge requests. 

Will take a look at that PR next chance I get, it's been quite busy.
