### ISSUE TITLE
ListProjects does not work as expected

### ISSUE THREAD

**Issue by sprotest** [xanzy/go-gitlab#243]
Using this https://github.com/xanzy/go-gitlab url to testing api calls I found that this simple example does not return expected projects.
Code example:

```
token := "qwertyuiop" //example token

git := gitlab.NewClient(nil, token)
git.SetBaseURL("https://mygitlab.mydomain.io/api/v4")
opt := &gitlab.ListProjectsOptions{Search: gitlab.String("artem")}
projects, _, err := git.Projects.ListProjects(opt)
if err != nil {
		println("Function GetUserProjects error: " + err.Error())
		return nil
	}
println(len(projects))
```
len(projects) returns 0

When I call api from browser:
https://mygitlab.mydomain.io/api/v4/projects?custom_attributes[search]=artem 
It returns all my projects.

**Comment by svanharmelen** [comment]
Interesting...

For starters the example you gave above is not consistent. In the API call from your browser you are using `custom_attributes` (which is currently not supported by this package) and in the code example you're using the standard `search` field as described here: https://docs.gitlab.com/ce/api/projects.html#list-all-projects

So I wonder if the Gitlab API changes with regards to this call and if the standard `search` attribute now no longer works as expected...

**Comment by Lorac** [comment]
@sprotest I think when you do your API call from your browser if the custom_attribute does not exist ( was not created by an admin ) it will by default list all projects.

If you are logged in your instance it will list all of the projects that match that search and if you are an admin you will all public/internal/private projects. When you sign out and open a new tab and do the same call, you'll only see the public projects.

That's the behavior I noticed by doing some testing, hopefully, this is helpful for you.

**Comment by svanharmelen** [comment]
Any updates on this one @sprotest? Is this still an issue for you? If not I'm going to close this issue before the new year starts 😉

**Comment by svanharmelen** [comment]
Closing this for now, feel free to reopen or open a new issue if you want to pick this up again.
