### ISSUE TITLE
Merge request work_in_progress 

### ISSUE THREAD

**Issue by ThomasBS** [xanzy/go-gitlab#25]
Hi .. This is more a question than an issue.

When we interact with our gitlab api, the api returns the `work_in_progress` [attribute](https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L42) as `0` (if true) or `null` (if false). This means the unmarshal'ing returns an error. We've fixed the issue on our forked repo by just adding the type `int` instead of `bool`. (Although [it clearly states it should return a boolean](http://doc.gitlab.com/ce/api/merge_requests.html#list-merge-requests))

I havent made a pull request because no one else has complained or notified about this, so we we're wondering if it was a problem on our side. Has anyone stumbled across this?

Also, thank you for making this an open source project :ghost:

**Comment by svanharmelen** [comment]
@ThomasBS I think there are two ways to solve this. The first is changing the `bool` to an `int` like you suggested, but with that you change the semantics a little I suppose... Where receiving a `null` shouldn't be the same a a `0`. The other option would be to turn the `bool` into `*bool`. That would marshal to `nil` if it received a `null`, which seems to match what is send by the API.

Additionally it could be good to open an issue with Gitlab to report this discrepancy between their docs and the actual response send...

Lastly thanks for the heads up and I'll happily take any PR's for this :wink:

**Comment by ThomasBS** [comment]
Alright, I will look into creating an issue to GitLab instead. That makes sense.

Thanks for the quick response!

**Comment by ThomasBS** [comment]
Just to clarify if anyone else would experience this. It was a problem of versioning, so it had nothing to do with this awesome repo. Gitlab had a "bug" where it didnt return a boolean for the `work_in_progress` attr for the merge request api. This has been fixed in [8.2.2](https://github.com/gitlabhq/gitlabhq/commit/380392212f87fc80bd45c322eda54461d47745b0).

So the lesson to be learning is to double-check your version. Sorry for the inconvenience.

**Comment by svanharmelen** [comment]
Thanks for the feedback and clarification @ThomasBS! :+1:
