### ISSUE TITLE
Add support for /events and /users/:id/events

### ISSUE THREAD

**Issue by etsrepo** [xanzy/go-gitlab#250]
add support for events and user events as described at https://docs.gitlab.com/ce/api/events.html#get-user-contribution-events

**Comment by Lorac** [comment]
@etsrepo @svanharmelen Working on it!

**Comment by Lorac** [comment]
@svanharmelen One question here... I've put `GET /users/:id/events` `GetUserContributionEvents` inside the `users.go` file. I feel that's fine. 

What about the `GET /events` endpoints? Which is the same as the other one but for the current logged user.

And the other one is project scoped `GET /:project_id/events` `projects.go` ?

**Comment by zaquestion** [comment]
@Lorac, pretty sure practice here is to put all of this in an `events.go` as an EventService. This API is meant to be laid out matching the gitlab docs (even over the REST paths) to make the functionality discoverable when coming from the GitLab docs.

At least that's the understanding I have... I'm just a guy trying to help @svanharmelen on the other side of the clock :D

**Comment by etsrepo** [comment]
@Lorac I have a working but incomplete EventService code, I can share if you want.

**Comment by etsrepo** [comment]
https://github.com/etsrepo/go-gitlab/blob/master/events.go

**Comment by Lorac** [comment]
I need to do some live testing before starting a PR, but here is it 

https://github.com/Lorac/go-gitlab/commit/abf2e628c71c4e48e3eaabba4d2a45abe10f976d

**Comment by Lorac** [comment]
@etsrepo Thanks, I copied over some of your code over in my commit.

**Comment by svanharmelen** [comment]
Again thanks for your help @zaquestion! I really appreciate your efforts!
