### ISSUE TITLE
`expires_at` as returned by `POST /users/:user_id/impersonation_tokens` cannot be parsed

### ISSUE THREAD

**Issue by michaellihs** [xanzy/go-gitlab#251]
When I create a new impersonisation_token with `Users.CreateImpersonationToken(userId, opts)` and `opts.ExpiresAt` is set with a time object created from `2017-12-24` (as stated in the Gitlab API documentation here https://docs.gitlab.com/ce/api/users.html#create-an-impersonation-token), I get the following error message:

````
Error: parsing time ""2017-12-24"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "T"
````

This is due to the date format of `expires_at` not being compatible with the default layout used by `time.Parse()` I guess.

Solution to this could be to change the `ExpiresAt` type to some custom date format and add marshelling and un-marshelling as described in #248

**Comment by svanharmelen** [comment]
This could/should be a possible solution for this problem as well: https://github.com/michaellihs/go-gitlab/pull/1
