### ISSUE TITLE
Missing integrated CI calls

### ISSUE THREAD

**Issue by AKoetsier** [xanzy/go-gitlab#27]
The readme explains it covers 100% of the gitlab v3 api. However I cannot find some of the integrated CI-calls. For example [get the status of a commit](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/commits.md#get-the-status-of-a-commit) or [posting the status of a commit](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/commits.md#post-the-status-to-commit). Is this by design or did it not yet get implemented after the gitlab was merged with CI?

**Comment by martinsefcik** [comment]
It's not yet implemented as it is relativelly new feature in Gitlab.
I will submit PR if I have some free time. I already started working a bit on it.
