### ISSUE TITLE
is something wrong in gitlab.go (function  NewRequest)

### ISSUE THREAD

**Issue by haosheng2015** [xanzy/go-gitlab#299]
I can not get the git project by this package, get error "400 failed to parse unexpected error type: <nil>".
I debugged, and get follow modify:
      gitlab.go  line 343   function  NewRequest
     u.Opaque = c.baseURL.Path + path   => u.Path = c.baseURL.Path + path
then be ok.
my go verison is 1.9.2. 
six months ago , I use this package and everything is OK, but today I can not get the git project, it is strange. Can you resolve my  confusion？

**Comment by zaquestion** [comment]
Hey @haosheng2015 not sure quite what you're seeing, I've had some trouble with getting the URL as a string I'm the past, no functional bugs tho. 

That said, [lab](https://github.com/zaquestion/lab) uses this project for quite a bit and have tests against a live gitlab instance.

**Comment by svanharmelen** [comment]
@haosheng2015 thanks for your report!

Could you maybe create a small code snippet that would generates the error? Would be great if you could write that snippet to use gitlab.com and not a private gitlab installation.

Then we can take it from there by first trying to reproduce the problem. Thx!

**Comment by svanharmelen** [comment]
@haosheng2015 would be great if you could send an example for us to test this with. If not, then I'm inclined to close this issue as I cannot seem to be able to reproduce your issue myself...

Thanks!

**Comment by haosheng2015** [comment]
thanks for guidance
