### ISSUE TITLE
Cannot get coverage of individual jobs

### ISSUE THREAD

**Issue by rhbvkleef** [xanzy/go-gitlab#300]
The GitLab API can expose a coverage number for each individual job. This number should be included in the Jobs struct, and all methods that create it should assign it.

**Comment by zaquestion** [comment]
Can't seem to find any docs on the format of the coverage blob. Except that it can be `null`.
https://docs.gitlab.com/ce/api/jobs.html
https://docs.gitlab.com/ce/api/builds.html

I'll get something going in gitlab ci, hopefully have something up shortly.

**Comment by zaquestion** [comment]
Looks likes its `null` or `int`

```
    "coverage": 34.6,
    "coverage": null,
```

**Comment by svanharmelen** [comment]
Fixed by PR #300
