### ISSUE TITLE
recursively get all projects in a group

### ISSUE THREAD

**Issue by cuotos** [xanzy/go-gitlab#308]
I'm having issues getting all the projects for a top level group.

Using the api I can get to /groups/<ID>/subgroups and iterate through them until I get to the bottom of the tree.

a. I am unable to get subgroups using the library
b. Is there a better way to be doing this!?

Thanks in advance.

Dan

**Comment by svanharmelen** [comment]
Hi @cuotos...

I think the best approach is to read the [API docs]() and from there determine which calls you would need to accomplish your goal.

Once you have established that, you can simply look up and use the related functions in this package...

**Comment by cuotos** [comment]
The api contains "groups/<gid>/subgroups" but the go-gitlab library doesn't implement the /subgroups endpoint. 

I'm relatively new to golang but happy to have ago at creating a PR if you fancy casting an eye / feedback on it.

 Its pretty much a clone of groups.go, but contains ListSubgroups(gid, opt, options). I wont be offended if it gets binned off.

Dan

**Comment by svanharmelen** [comment]
Ah, check... Let me have a look at that one...

**Comment by svanharmelen** [comment]
Just noticed your (already closed again) PR... I think the method you added should be added to the `groups.go` file as a method of the `GroupService`. Other then that it looks fine I guess 👍

**Comment by svanharmelen** [comment]
This one is fixed by PR #309
