### ISSUE TITLE
Support for complete runners API

### ISSUE THREAD

**Issue by FlakM** [xanzy/go-gitlab#314]
I've noticed some missing endpoints from runners API (ie: [disable runner for project](https://docs.gitlab.com/ce/api/runners.html#disable-a-runner-from-project)).
Am i missing something or are they just not implemented yet? 

I'd be happy to contribute ;)

**Comment by zaquestion** [comment]
@FlakM GitLab updates their API, pretty often, its possibly that somethings are missing in the runners API. Feel free to contribute PRs. @svanharmelen is pretty good about reviewing changes as they come in.

**Comment by svanharmelen** [comment]
Hi @FlakM!

Like @zaquestion already mentioned, by all means add the missing parts and create an PR for it! PR's are always very much appreciated 👍 

Thanks!
