### ISSUE TITLE
Support for Issue links API

### ISSUE THREAD

**Issue by JohnnyQQQQ** [xanzy/go-gitlab#315]
Currently the Issue links API is not supported.

https://docs.gitlab.com/ee/api/issue_links.html

**Comment by Lorac** [comment]
@JohnnyQQQQ I'll put a PR asap

**Comment by DanMayor** [comment]
Is there documentation that shows how to use this package?  Such as for ListIssues, what are opt and options supposed to be?

**Comment by svanharmelen** [comment]
@DanMayor the answer is in both the code of this package and the GitLab docs. There are also a few [examples](https://github.com/xanzy/go-gitlab/tree/master/examples) that show the basic way to use this package.

Specifically for the [ListIssues](https://github.com/xanzy/go-gitlab/blob/master/issues.go#L124-L141) call, you can check the related [options](https://github.com/xanzy/go-gitlab/blob/master/issues.go#L106-L122) struct that shows all fields you can set (that's the `opt` part).

The valid `options` you can pass in are described [here](https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L678-L702). But they are not mandatory and can also be omitted.

Hope this helps...
