### ISSUE TITLE
Add `go tool vet .` to the CI

### ISSUE THREAD

**Issue by Lorac** [xanzy/go-gitlab#323]
It could help to detect some errors that we could miss when reviewing code.

If the commiter isn't using the tool he might miss some suspicious code. Like not using the correct `Printf` arguments and such.

What do you think?

**Comment by svanharmelen** [comment]
No need to do this... From Go 1.10 forwards, `go test` will also check/run `go vet`. So this will be inherently added when we add Go 1.10 to our Travis file 👍
