### ISSUE TITLE
Add pagination the result on a diff commit

### ISSUE THREAD

**Issue by Lorac** [xanzy/go-gitlab#338]
For now, it seems impossible to paginate this endpoint: https://docs.gitlab.com/ce/api/commits.html#get-the-diff-of-a-commit

I feel that it should be possible when you have more than 20 files in the diff.

I opened an issue with gitlab https://gitlab.com/gitlab-org/gitlab-ce/issues/43370

**Comment by svanharmelen** [comment]
@Lorac not sure if we need this issue open in here? It's a Gitlab thingy right? So I prefer to close this one unless there is a clear depending open action for `go-gitlab`?

**Comment by Lorac** [comment]
You can close, https://github.com/xanzy/go-gitlab/pull/341/files#diff-297afcd71fc11b3943eda57d4cb629dfR211

You added it :) But it won't work until https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/17203 is released.

**Comment by svanharmelen** [comment]
Check... Thanks!
