### ISSUE TITLE
Rate limitation 

### ISSUE THREAD

**Issue by Lorac** [xanzy/go-gitlab#346]
I was trying to cause a rate limitation error, and it seemed impossible. Apparently looking at the documentation, it's 10req/s. I think it's only unauthenticated requests???

We should return an error based on that if it happens or we prevent the call to the api.

There are multiple headers associated with it 

```
ratelimit-limit →600
ratelimit-observed →1
ratelimit-remaining →599
ratelimit-reset →1519126320
ratelimit-resettime →Wed, 20 Feb 2018 11:32:00 GMT
```

We could, in theory, based the on the last query know in advance if the next one will cause a rate limit error.

**Comment by svanharmelen** [comment]
Currently we will return the rate limit error that Gitlab returns (that is, I assume it does indeed generate an error for that). But I agree that preventing that you would hit the rate limit would be a nice feature.

Looking at how [`go-github`](https://github.com/google/go-github/blob/master/github/github.go) handles rate limiting, it does seem to require some new moving parts and additional logic if we want to do this right. But that shouldn't be a reason not to add this of course :wink:

**Comment by Lorac** [comment]
I started something, but then while testing it ( trying to bust the API limit ), I think I found a bug on the gitlab side for rate-limitation.

Tell me what you think, I wrote this simple loop : 
```golang
for i := 0; i < 650; i++ {
	_, resp, err := git.Projects.GetProject(13083) // Get GitlabProject
	fmt.Println(resp)
	fmt.Println(err)
}
```

I compile, run it...

```
&{0xc0420fe090 0 0 0 0 0 0 {600 1 599 1519186248 2018-02-21 04:10:48 +0000 GMT}}
<nil>
&{0xc0421d2000 0 0 0 0 0 0 {600 2 598 1519186248 2018-02-21 04:10:48 +0000 GMT}}
<nil>
&{0xc0421dc000 0 0 0 0 0 0 {600 3 597 1519186248 2018-02-21 04:10:48 +0000 GMT}}
<nil>
&{0xc0420fe1b0 0 0 0 0 0 0 {600 4 596 1519186248 2018-02-21 04:10:48 +0000 GMT}}
<nil>
&{0xc0421d2090 0 0 0 0 0 0 {600 5 595 1519186248 2018-02-21 04:10:48 +0000 GMT}}
```
You can see 600, 5, 595 these are the rate limitation headers. So far so good, it goes up to around 400 observed requests.

Now I start my program in two separate consoles. I expected the rate limitation go up MUCH faster right? Well.... Nope 😕  It gets to a maximum of 10 for the `ratelimit-observed` and then it resets to 0.

Were you expecting that kind of behavior? Maybe I should file a bug on gitlab side? 

Maybe I wrote something weird. https://github.com/Lorac/go-gitlab/commit/b2dc81bba76be96f7721f1334168ba77171b1373

That's the commit for now... Want me to do a PR and review it there instead?

**Comment by zaquestion** [comment]
> So, in other words, I can bypass the limit by doing more requests in different threads...
yeesh, thats hard to believe, hopefully its just something we're doing. Though it seems like a possible error case if they aren't synchronizing that counter properly. Would suggest checking their issue tracking and if nothings there maybe formalizing the test (like a gist they can just run) and filing a bug. Would be happy to double check your work to avoid possible :egg: :man_facepalming:

**Comment by svanharmelen** [comment]
I can observe the same (more or less) behaviour with this one-liner:

```
for i in {1..1000}; do curl -sD - -o /dev/null "https://gitlab.com/api/v4/projects/13083"; done
```

I have no clue how it is supposed to work, but it looks like there isn't much rate limiting going on. According to the docs (hard to find and now very clear) it seems the limit should be max 10 req/sec per IP address...

**Comment by Lorac** [comment]
I posted an issue on gitlab. https://gitlab.com/gitlab-org/gitlab-ce/issues/43456

Getting no attention so far.

**Comment by Lorac** [comment]
This issue just got some attention on Gitlab side. Hopefully, we can see what is wrong with their HAProxy or maybe we did something weird...

**Comment by svanharmelen** [comment]
Hi @Lorac! I was just wondering if you think we should still keep this issue open? I'm looking into a little end-of-year cleanup and unless we have an idea what to do with this issue, I think we should close it. What do you think?

**Comment by Lorac** [comment]
Yes you can close, I'll submit a PR at some point, I think we just can't poke the api fast enough to hit the rate limiter

**Comment by svanharmelen** [comment]
Check... Thanks for the update!
