### ISSUE TITLE
Test against gitlab.com

### ISSUE THREAD

**Issue by brasilikum** [xanzy/go-gitlab#35]
I think the package would profit from tests against a real API. It could be organized as follows:
- create an account just for testing
- setup tests
- insert the secret key of the testing account into the tests via ENV from eg coveralls #21 
- insert the coverage badge into the README

**Comment by mvdan** [comment]
It would be a lot more reliable to test against a mock local API server, e.g. using httptest.

**Comment by svanharmelen** [comment]
Yes, I agree with @mvdan and will (at this time) setup testing against gitlab.com.
