### ISSUE TITLE
Tags API missing releases

### ISSUE THREAD

**Issue by Dbzman** [xanzy/go-gitlab#362]
Hey there,

I just noticed that creating and updating a release is missing from the tags api:
https://docs.gitlab.com/ce/api/tags.html#create-a-new-release
https://docs.gitlab.com/ce/api/tags.html#update-a-release

Would be very handy to have :)

Cheers

**Comment by zaquestion** [comment]
@Dbzman @svanharmelen  looks like support for this was added in #373, can we close out this issue?

**Comment by Dbzman** [comment]
@zaquestion Fine for me. We've been using it for a couple of weeks already. Works great! :)
