### ISSUE TITLE
Delete Project Milestone method missing

### ISSUE THREAD

**Issue by johanbrandhorst** [xanzy/go-gitlab#369]
The documentation lists the ability to delete a project milestone: https://docs.gitlab.com/ce/api/milestones.html#delete-project-milestone. This does not appear to be implemented currently. This issue should track the implementation of this method.

**Comment by Lorac** [comment]
@svanharmelen I started implementing it, but I saw that `group_milestones` and my `project_milestones` would pretty much duplicate code. The only difference is the URL We could unify the code under `milestones.go`, so we can do something like : 

```
// ListProjectMilestones gets a list of a project's milestones.
//
// GitLab API docs:
// https://docs.gitlab.com/ce/api/members.html#list-all-members-of-a-group-or-project
func (s *MilestoneService) ListProjectMilestones(pid interface{}, opt *ListMilestonesOptions, options ...OptionFunc) ([]*Milestone, *Response, error) {
	project, err := parseID(pid)
	if err != nil {
		return nil, nil, err
	}
	u := fmt.Sprintf("projects/%s/milestones", url.QueryEscape(project))
	return listMilestones(u, opt, options)
}

// ListGroupMilestones gets a list of a groups's milestones.
//
// GitLab API docs:
// https://docs.gitlab.com/ee/api/group_milestones.html#list-group-milestones
func (s *MilestoneService) ListGroupMilestones(gid interface{}, opt *ListMilestonesOptions, options ...OptionFunc) ([]*Milestone, *Response, error) {
	group, err := parseID(gid)
	if err != nil {
		return nil, nil, err
	}
	u := fmt.Sprintf("groups/%s/milestones", url.QueryEscape(project))
	return listMilestones(u, opt, options)
}

func (s *MilestoneService) listMilestones(url string, opt *ListMilestonesOptions, options ...OptionFunc) ([]*Milestone, *Response, error) {
	req, err := s.client.NewRequest("GET", url, opt, options)
	if err != nil {
		return nil, nil, err
	}

	var pm []*Milestones
	resp, err := s.client.Do(req, &pm)
	if err != nil {
		return nil, resp, err
	}

	return pm, resp, err
}
```

What do you think?

**Comment by johanbrandhorst** [comment]
I actually think we intentionally duplicate a lot of similar code in order to make changes down the line easier. I could be wrong though.

**Comment by svanharmelen** [comment]
@Lorac I tend to agree with @johanbrandhorst on this one. We could save a few LoC here, but since we only talk about a couple of lines I don't think it adds much value.

But to be honest, I'm fine either way. Your proposed solution also looks clean and simple. So I'll leave it up to you :wink:
