### ISSUE TITLE
Add support for new project import/export API

### ISSUE THREAD

**Issue by brendano86** [xanzy/go-gitlab#370]
GitLab recently released an API to import/export projects.

Proposal would be to add support to `go-gitlab` for this: https://docs.gitlab.com/ee/api/project_import_export.html

**Comment by svanharmelen** [comment]
Not sure if/when I have time for this myself, but seems to me we should indeed add support for this API. Of course a PR adding this is very welcome and appreciated!

**Comment by RoValentim** [comment]
I need it too @brendano86, did you start to make this methods?

If yes, how can I help you?

**Comment by Snehal1112** [comment]
Guys anyone working on this enhancement

**Comment by svanharmelen** [comment]
Nope... At least now as far as I know.

**Comment by Snehal1112** [comment]
@svanharmelen I would like to work on this enhancement.

**Comment by svanharmelen** [comment]
Thanks @Shehal1112! Feel free to pick it up and create a PR for it 👍🏻

Have a look at the rest of the existing code an please try to keep things consistent.

Thanks!

**Comment by matejvelikonja** [comment]
@svanharmelen let us know when you start working on it. We would really need this feature.

**Comment by matejvelikonja** [comment]
sorry @svanharmelen, I tagged the wrong person :) I wanted to ask @Snehal1112

**Comment by Snehal1112** [comment]
@matejvelikonja @svanharmelen I have already started work on in I just stuck with import project stuff. 
I will try to commit the change ASAP.

**Comment by matejvelikonja** [comment]
@Snehal1112 could you at least make a PR for the export stuff? I would really need this functionality :)

**Comment by Snehal1112** [comment]
@matejvelikonja sorry for the late replay. last week is very hectic for me. 
I have done with the following things 
- Export status
- Export download
- Import status

Remaining thing 
- Import a file 
    - this feature was some problem and because of that i am able to reproduce this following issue 
        https://gitlab.com/gitlab-org/gitlab-ce/issues/57579
        https://gitlab.com/gitlab-org/gitlab-ce/issues/57585
    which is I think fixed now by gitlab 
- Schedule an export
