### ISSUE TITLE
Support OAuth2 with Resource Owner Password Credentials

### ISSUE THREAD

**Issue by zizhongwei** [xanzy/go-gitlab#385]
Does the clitent support OAuth2 with Resource Owner Password Credentials?

**Comment by svanharmelen** [comment]
Hi @zizhongwei! I'm not sure about that... The client does support OAuth token, but I'm not sure what `with Resource Owner Password Credentials` means in this case?

**Comment by zizhongwei** [comment]
Hi~,in GitLab Documentation：https://docs.gitlab.com/ee/api/oauth2.html ，GitLib Supported  Resource Owner Password Credentials(use username&password) like this: 
![image](https://user-images.githubusercontent.com/12456254/39680743-b53e5d9c-51d6-11e8-90e3-b276ab2ac011.png)
So dose the client supported Resource Owner Password Credentials(use username&password)?

**Comment by svanharmelen** [comment]
@zizhongwei this should now be possible using the `NewBasicAuthClient`.
