### ISSUE TITLE
ListCommits with non-Null Since/After in v0.10 not in request

### ISSUE THREAD

**Issue by lowjoel** [xanzy/go-gitlab#390]
After d8a6b1518d2ffaddbb2b6bf422ac1204f4a056a4 was applied, my ListCommits calls seem to return all commits instead of the Since/After range.

I've traced into the API call and I see that the Since/After fields are missing from the query string. I'm not entirely sure what the fix is, or if it belongs in this library or in the Google go-querystring library.

**Comment by lowjoel** [comment]
So it seems we must have google/go-querystring@53e6ce116135b80d037921a7fdd5138cf32d7a8a. My repository has that pinned to 5 commits before. So this doesn't seem like it's a problem with this go-gitlab.

Is there a way to specify dependencies so Glide (or dep) will warn when the version constraints don't match?

**Comment by lowjoel** [comment]
Quick Googling makes it seem like it's not possible. Hopefully this issue will bubble up in subsequent Google searches.

Thanks @svanharmelen!

**Comment by svanharmelen** [comment]
The general consensus is to not do vendoring for packages/libraries, so indeed I don't think there is a way to do it. But hopefully this issue will help for people searching about it and maybe I can put something in the README.md that points this out. Guess that should help as well.

**Comment by lowjoel** [comment]
Yeah, vendoring libraries is a bad idea. Hopefully this issue gets found when people do a search. I'll close it for now.
