### ISSUE TITLE
Creating a gotest framework

### ISSUE THREAD

**Issue by tinyzimmer** [xanzy/go-gitlab#391]
I saw in the README you are hoping to get some tests going eventually, and I could tell the pretty glaring complexity in how could you test throw-away gitlab environments not on your workstation or using the managed service.

So I tinkered with Travis-CI and Docker-Compose, and I have something that might intrigue you. Within the build environment a docker container of gitlab-ce is spun up using Omnibus configurations to set an initial root password. Then the tests that need to authenticate against the API can do a quick Oauth shake to get a PAT generated. Then on to the rest of your tests. 

```
=== RUN   TestGoodRunEngine
2018/05/10 13:01:17 TEST: Retrieving test gitlab oauth token
2018/05/10 13:01:17 TEST: Succesfully retrieved test gitlab oauth token: fba4bd3cfeeaa2e38f98652b8bc36cf2060fd3fca8c54b0a9ff56fc432e42a9e
2018/05/10 13:01:17 TEST: Retrieving test impersonation token
2018/05/10 13:01:17 TEST: Succesfully retrieved test gitlab impersonation token: y7vps5XHnz3JLS8nNdda
2018/05/10 13:01:17 INFO Retrieving default configurations
2018/05/10 13:01:17 INFO Parsing configurations from environment
2018/05/10 13:01:17 INFO Validated credentials
--- PASS: TestGoodRunEngine (0.40s)
```

My repo: https://github.com/tinyzimmer/gitlab-crawler - the docker-compose and .travis.yml are the nuts and bolts. 

https://github.com/tinyzimmer/gitlab-crawler/blob/master/engine/gitlabclient_test.go - line 94 is the function that uses the temporary root password to get the Oauth token. I may have looked over it, but I didn't see a raw credentials call in go-gitlab yet, not that you'd really ever want it except just for this. 

If you like this idea I'm happy to help get those tests written and we could use Travis to offload the work. Let me know what you think.

**Comment by svanharmelen** [comment]
Hi @tinyzimmer! This sounds like a really good plan 👍 

I do notice that you only spin up one container, so wouldn't just `docker run ...` work as well? And it so happened that there was an open issue for using this package with a username/password so I was just wrapping up adding that to the package (just merged it).

So now you can just create a new client with username/password and it will manage fetching and refreshing the token for you 😀

**Comment by tinyzimmer** [comment]
Can definitely just use docker run. That's how I was initially tinkering with it at home. Just think the compose file looks cleaner is all and is baked into travis so why not 😛

**Comment by svanharmelen** [comment]
Yeah, agree on that...

**Comment by tinyzimmer** [comment]
I'll get a fork goin over the weekend

**Comment by bzon** [comment]
Does this mean that the existing Test suites will poiny the api call to the running local Gitlab?

**Comment by bzon** [comment]
In our gitlab-cli project, https://github.com/devopsctl/gitlabctl, we use a local gitlab instance to test our commands. This way, we are doing a unit test and some sort of integration test as well. 

We have testdata, curl scripts that populates our Gitlab instance. See the `.travis.yml` for reference.

**Comment by svanharmelen** [comment]
Any updates on this one @tinyzimmer? If looking to do an end-of-year cleanup on stale issues, so if you abandoned this issue I'm going to close it before the new year starts :wink: So please let me know if this is still work in progress. Thanks!

**Comment by tinyzimmer** [comment]
Crap. I got busy with a new job a while back and haven't been getting as
much exposure to Gitlab these days. You can probably just close the issue.
My apologies.

**Comment by svanharmelen** [comment]
No problem at all! Same here actually :wink: Enjoy your holidays!
