### ISSUE TITLE
golang.org/x/oauth2

### ISSUE THREAD

**Issue by relax-admin** [xanzy/go-gitlab#399]
Is it possible to reference github's class library and use golang's class library to cause us to fail to download in China，I cannot go get golang.org/x/oauth2

**Comment by svanharmelen** [comment]
Hi @relax-admin! I'm not sure I understand what you mean with `reference github's class library and use golang's class library`?

Do you mean if we could build our own oauth package using only Golang standard library packages instead of using `golang.org/x/oauth2`?

**Comment by pityonline** [comment]
@relax-admin It is OK, I did this very often.

@svanharmelen Because golang.org is almost blocked in China, so we need to reference it's mirrored repository on GitHub to use the libraries.

For example, golang.org/x/oauth2 is mirrored at https://github.com/golang/oauth2 on GitHub. We need to clone it from GitHub to $GOPATH/src/golang.org/x/oauth2, to make it accessible in import statements.

**Comment by relax-admin** [comment]
@pityonline 
We may be able to solve this problem when we run the code locally, but when we publish it, when we compile the program in jenkins, we will report an error.

Error content：
Step 2/15 : RUN     go get github.com/fatih/structs     &&  go get github.com/xanzy/go-gitlab
 ---> Running in 45da8514040d
[91mpackage golang.org/x/oauth2: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
[0mRemoving intermediate container 45da8514040d
The command '/bin/sh -c go get github.com/fatih/structs     &&  go get github.com/xanzy/go-gitlab' returned a non-zero code: 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by jayschwa** [comment]
If you're using a tool like [`dep`](https://github.com/golang/dep), adding this to your `Gopkg.toml` might help:
```
[[constraint]]
  name = "golang.org/x/oauth2"
  source = "github.com/golang/oauth2"
```

**Comment by pityonline** [comment]
The problem seems to be here: 

* Even you use mirrored repo of golang.org on GitHub, the source still asks to import golang.org packages.

```
$ go get -v -u github.com/golang/oauth2
github.com/golang/oauth2 (download)
package github.com/golang/oauth2: code in directory /Users/me/.go/src/github.com/golang/oauth2 expects import "golang.org/x/oauth2"
```

* There are still some `x/* redirects` to golang.org, [check this comment](https://github.com/golang/lint/issues/397#issuecomment-384001884).

```
$ go get -v -u github.com/golang/lint
github.com/golang/lint (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/ast/astutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
golang.org/x/tools (download)
# cd /Users/me/.go/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/tools/go/ast/astutil: exit status 1
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
Fetching https://golang.org/x/tools/go/internal/gcimporter?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/internal/gcimporter?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
```

**Comment by relax-admin** [comment]
@jayschwa 
I tried dep init and found it would still time out
Importing configuration from govendor. These are only initial constraints, and are further refined during the solve process.
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
init failed: unable to solve the dependency graph: Solving failure: unable to deduce repository and source type for "golang.org/x/net/context": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/net/context?go-get=1": Get http://golang.org/x/net/context?go-get=1: dial tcp 172.217.25.81:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
@pityonline 
You are right. This is a sad story.

**Comment by svanharmelen** [comment]
@relax-admin do I understand it correctly that you now managed to download and use the package?

If not, could you try it again using this command: `git clone https://github.com/golang/oauth2 $GOPATH/src/golang.org/x/oauth2`

This should checkout the needed code into the correct (expected) directory. Let me know if it works for you now and if we can close this issue.

**Comment by relax-admin** [comment]
@svanharmelen 
Great, it can solve the problem. This is a genius idea. You seem to give us a new direction. It is a good idea to replace go get with git clone.
Dockerfile:
```
RUN go get github.com/fatih/structs \
     && git clone https://github.com/golang/oauth2 $GOPATH/src/golang.org/x/oauth2 \
     && go get github.com/xanzy/go-gitlab
```
Ci:
```
Step 2/15 : RUN     go get github.com/fatih/structs     && git clone https://github.com/golang/oauth2 $GOPATH/src/golang.org/x/oauth2     && go get github.com/xanzy/go-gitlab
 ---> Running in 119892f02642
[91mCloning into '/go/src/golang.org/x/oauth2'...
[0mRemoving intermediate container 119892f02642
 ---> 7e1bfb354bc1
```

**Comment by relax-admin** [comment]
@svanharmelen
Thank you very much, this issue should be closed

**Comment by svanharmelen** [comment]
Glad to hear this solves the problem!
