### ISSUE TITLE
ListProjectMemberOptions and ListGroupMemberOptions should have the same type

### ISSUE THREAD

**Issue by bzon** [xanzy/go-gitlab#411]
Problem:

* [__ListProjectMembersOptions__](https://godoc.org/github.com/xanzy/go-gitlab#ListGroupMembersOptions) is its own struct type and [__ListGroupMemberOption__](https://godoc.org/github.com/xanzy/go-gitlab#ListProjectMembersOptions) is a [__ListOption__](https://godoc.org/github.com/xanzy/go-gitlab#ListOptions) type. 
* ListGroupMemberOption is also missing a Query field.

Proposed Solution:

For package consistency, my proposal is to create a __ListMembersOptions__ type where both __ListGroupMemberOption__ and __ListProjectMembersOptions__ can be created. My reference is the [Group and project members API](https://docs.gitlab.com/ce/api/members.html#list-all-members-of-a-group-or-project).

**Comment by svanharmelen** [comment]
If `ListGroupMemberOptions` needs more fields, then I suggest to just create a dedicated struct for it. So something like:

```go
type ListGroupMemberOptions struct {
  ListOptions
  OtherFields   string
}
```

Creating a 3rd struct that then can be used by two others doesn't feel right to me. Even if the structs are actually the same, I prefer to just have 2 separate ones in that case.

**Comment by bzon** [comment]
@svanharmelen sounds fair to me.
