### ISSUE TITLE
Groups.TransferGroup 'project' parameter should be an 'interface{}' not 'int'

### ISSUE THREAD

**Issue by bzon** [xanzy/go-gitlab#414]
Current code: https://godoc.org/github.com/xanzy/go-gitlab#GroupsService.TransferGroup

```golang
func (s *GroupsService) TransferGroup(gid interface{}, project int, options ...OptionFunc) (*Group, *Response, error)
```

API doc: https://docs.gitlab.com/ce/api/groups.html#transfer-project-to-group

**Comment by svanharmelen** [comment]
Fixed by PR #415
