### ISSUE TITLE
API /project/*/builds/*

### ISSUE THREAD

**Issue by mishak87** [xanzy/go-gitlab#42]
Do you plan on adding `projects/<id>/{builds,repository}` API?
http://doc.gitlab.com/ce/api/builds.html

**Comment by svanharmelen** [comment]
No immediate plans and personally quite busy at the moment... But of course a PR would be most welcome! :wink:

**Comment by mishak87** [comment]
@svanharmelen PR it is then :-)

**Comment by svanharmelen** [comment]
Fixed by PR #71
