### ISSUE TITLE
404 creating webhooks when using `owner/repo` as project ID rather than the ID integer

### ISSUE THREAD

**Issue by rawlingsj** [xanzy/go-gitlab#424]
Trying to create a webhook on a repo hosted at https://gitlab.com/ fails because the URL is always encoded meaning when we use `owner/repo_name` as the project id we loose the %2F escaped value resulting in a 404.  

I tried a few things out and the only thing that seems to work is after following this issue https://stackoverflow.com/questions/20847357/golang-http-client-always-escaped-the-url

```
	req, err := s.client.NewRequest("POST", u, opt, options)
	req.URL = &url.URL{
		Scheme: "https",
		Host:   "gitlab.com",
		Opaque: "//gitlab.com/api/v4/projects/rawlingsj%2Fjr-test/hooks",
	}
	if err != nil {
		return nil, nil, err
	}
```

By adding the `Opaque` URL the encoded `/` was sent and the webhook created successfully. 

Does that make sense?  I wonder if this is always failing for all gitlab servers?  I can pop a PR together if that helps but figured I'd start a discussion.  I wonder if we need to do the above if folks use `owner/repo` rather than the ID int?

**Comment by svanharmelen** [comment]
Hi @rawlingsj! This is actually already done in the `NewRequest` method: https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L509 And on line 521 you can see that the variable `u` is assigned to the request. So what you are doing shouldn't be needed.

Can you share some more code or an example of when it doesn't work?

**Comment by rawlingsj** [comment]
Hi @svanharmelen ah ok, that's strange then as I wasn't able to create webhooks without setting that `Opaque` value.

Here's what we're doing:

```
	pid := "foo%2Fbar"

	opt := &gitlab.AddProjectHookOptions{
		URL:   "https://gitlab.com",
		Token: "",
	}

	_, _, err := g.Client.Projects.AddProjectHook(pid, opt)
```

Calling https://github.com/xanzy/go-gitlab/blob/master/projects.go#L782 and in turn calls that `NewRequest` method you mentioned.

I'm travelling today and tomorrow but will try and put a test case together that shows for real what we're doing.  FWIW this was using a test repo I have on https://gitlab.com.

**Comment by svanharmelen** [comment]
Hi @rawlingsj! Did you have time to put a test case together? And/or is this still an issue? Thanks!

**Comment by svanharmelen** [comment]
Any updates on this one @rawlingsj? If not I'm going to close this issue before the new year starts :wink:

**Comment by svanharmelen** [comment]
Closing this for now, feel free to reopen or open a new issue if you want to pick this up again.
