### ISSUE TITLE
Cannot use UpdateIssue to remove all issue assignees

### ISSUE THREAD

**Issue by lily-mara** [xanzy/go-gitlab#427]
Since `UpdateIssueOptions` defines `AssigneeIDs` as a `[]int`, and marks it as `omitempty`, it is omitted from the JSON request if an empty array is passed into it. The Gitlab API docs describe the field as follows:

> The ID of the user(s) to assign the issue to. Set to 0 or provide an empty value to unassign all assignees.

Based on the current definition of `UpdateIssueOptions`, it is impossible to unassign all assignees. You cannot remove the `omitempty` item, or every call to `UpdateIssue` will remove all issue assignees. if you want to support this, I think there needs to be a separate method.

**Comment by svanharmelen** [comment]
Thanks for the report @natemara! Did you also try to give it a `[]int{0}` as value? No idea, but maybe worth checking...

**Comment by svanharmelen** [comment]
Hi @natemara! Did you have a chance to test this, and so is this still an issue?

**Comment by 0xmohit** [comment]
Specifying `[]int{0}` as value does remove the assignee.

**Comment by svanharmelen** [comment]
Then I think the only way to solve this is by making this a `*[]int`, but I must admit that feels a bit nasty.

**Comment by no0by5** [comment]
The same problem applys to labels. You can't remove them by setting it to an emtpy slice, but if you use []string{""} it works.

**Comment by svanharmelen** [comment]
PR #1294 is a nasty breaking change, but it does fix this issue...
