### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by ecornelisse** [xanzy/go-gitlab#433]
Most endpoints of gitlab use pagination so your `ListProjects` call returns only 20 results. How should i handle pagination with this package?

**Comment by Lorac** [comment]
You can read `TotalPages` from the `Response struct` [here](https://github.com/xanzy/go-gitlab/blob/fb3ece09ef3e80cfa5c1e52dc75fcfb56c12e026/gitlab.go#L558)

From there you can loop for with the `ListProjectsOptions` by passing the `Page` number to the `ListProjects` call.

There is the `PerPage` attribute that you can modify, but I think it's cap to 20 results max.

**Comment by Lorac** [comment]
@svanharmelen Might be a good idea to add an example of pagination in the directory examples. What do you think?

**Comment by svanharmelen** [comment]
Yeah, that would be nice/helpful @Lorac :+1:

**Comment by ecornelisse** [comment]
should it be something like this?:
```golang
        currentPage := 0
	for {
		currentPage++
		projects, response, err := git.Projects.ListProjects(options, func(request *http.Request) error {
			request.URL.Query().Add("page", string(currentPage))
			request.URL.Query().Add("per_page", string(10))
			return nil
		})
            }
```

**Comment by Lorac** [comment]
@ecornelisse I added a pull request, that is my understanding of how pagination is working. I might be wrong tho.
