### ISSUE TITLE
Missing straight option in repositories compare API

### ISSUE THREAD

**Issue by Colstuwjx** [xanzy/go-gitlab#437]
Hi,

it seems that we have missing `straight` option in the repositories compare API, see our code below:

```
type CompareOptions struct {
	From *string `url:"from,omitempty" json:"from,omitempty"`
	To   *string `url:"to,omitempty" json:"to,omitempty"`
}
```

According to the [API doc](https://docs.gitlab.com/ce/api/repositories.html#compare-branches-tags-or-commits), we might need to add `straight` option.

Thanks!

**Comment by pmwebster** [comment]
#448 fixes this.
