### ISSUE TITLE
Missing 'oldrev' field in merge request event

### ISSUE THREAD

**Issue by gitlawr** [xanzy/go-gitlab#457]
In Gitlab merge request events, there's no `synchronize` action like Github. When you update the code or the labels of merge request, a webhook is triggered with the same update action.
Actually there's an `oldrev` field in the payload to distinguish the above cases. It's not obvious in the Gitlab docs though.
It is mentioned in the issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/13545
Or you can see it by checking the event payload with code changes.
This field is useful for a CI service to know if it's time to trigger a build.

**Comment by svanharmelen** [comment]
Fixed by PR #458
