### ISSUE TITLE
Search coverage

### ISSUE THREAD

**Issue by lillilli** [xanzy/go-gitlab#464]
Search is setting up as false in Readme (coverage), but I found implementation in repo (search.go).

![image](https://user-images.githubusercontent.com/19287534/45016302-e1e91a80-b02c-11e8-97cf-0bff68d32e1d.png)

Is there any needed to change current implementation?

**Comment by svanharmelen** [comment]
Nice catch, I think it should be set to `true` 👍

**Comment by svanharmelen** [comment]
Updated the field in the readme...
