### ISSUE TITLE
Go 1.7 support ?

### ISSUE THREAD

**Issue by thib-ack** [xanzy/go-gitlab#473]
Hello,

I just want to say that since b8189bef4d4ee2b365a2c03a8bc99e4f3600743e the go-gitlab project is not anymore compatible with Go v1.7 because the function url.PathUnescape(string) has been added in Go v1.8

https://github.com/xanzy/go-gitlab/blob/b8189bef4d4ee2b365a2c03a8bc99e4f3600743e/gitlab.go#L503

However, the supported Go versions are not specified anywhere in the readme, so I'm not sure this is an issue for you (even if it is one for me :-) )

Do you plan to still support Go1.7 ?

Thanks,
Thibaut

**Comment by svanharmelen** [comment]
Nice catch @thib-ack! But I'm good with not supporting Go1.7 anymore. I think in general Go developers upgrade reasonably fast, so Go1.7 almost seems ancient :wink:

**Comment by zaquestion** [comment]
Classically `go-gitlab` has only supported the last 3 versions of go which can be seen here https://github.com/xanzy/go-gitlab/blob/master/.travis.yml#L3 -- tho it's time to update ;) 

P.S. @svanharmelen I'm behind too, still haven't adopted modules in lab.

**Comment by svanharmelen** [comment]
I'm closing this one as there are no pending actions/answers for this issue.
