### ISSUE TITLE
Miss the Changes field of MergeEvent struct in event_type.go

### ISSUE THREAD

**Issue by SeananXu** [xanzy/go-gitlab#477]
Cloud you please add this field in the MergeEvent struct in event_type.go? I can use this field to know the gitlab changes in mr event.
![image](https://user-images.githubusercontent.com/26948962/46129980-bd1e4680-c26a-11e8-9ac3-ca125c8084be.png)

#478

**Comment by svanharmelen** [comment]
Fixed by PR #479
