### ISSUE TITLE
SetBaseURL use const apiVersionPath, which may be not /api/v4, for example, /api/v3.

### ISSUE THREAD

**Issue by denglitong** [xanzy/go-gitlab#500]
As mention above, i encountered that my GitLab Community Edition 8.11.3 only have /api/v3/ and not any /api/v4/ available, so I think it make sense that change const apiVersionPath to var ApiVersionPath in package, so I can configure it outside the package. Should I create a pull request? Thank you very much. :-)

**Comment by svanharmelen** [comment]
Hi @denglitong! The V3 and V4 APIs have a lot of differences, so just changing the URL would not work for all APIs.

But we still have a branch (`f-api-v3`) for the V3 API that you can (and should) use when targeting V3.

**Comment by denglitong** [comment]
Thanks, I got it.
