### ISSUE TITLE
Support push rules for projects

### ISSUE THREAD

**Issue by BernhardBerbuir** [xanzy/go-gitlab#501]
I'm not sure if features of the enterprise edition are in scope of this project, but it would be nice if [push rules](https://docs.gitlab.com/ee/api/projects.html#push-rules) (get, add, edit, delete)  would be supported (like web hooks / project hooks)

**Comment by svanharmelen** [comment]
Hi @BernhardBerbuir! The `go-gitlab` package definitely supports `ee` features as well.

I don't have much (if any) time to work this one myself, but if anyone is up to add support for the push rule APIs I have no problem with merging that PR 👍
