### ISSUE TITLE
GetUserByName

### ISSUE THREAD

**Issue by 45cali** [xanzy/go-gitlab#509]
Currently the `GetUser` method requires the id of the user. What about a `GetUserByName` method where we can pass in the username instead in case we dont have the id or need to get the id. 
```
GET /users?username=:username
```

**Comment by svanharmelen** [comment]
Sure, sounds fine to me.

**Comment by 45cali** [comment]
Actually I realised the response comes back as a list and this is more a list command with a filter.
Using the `ListUsers` method w/ `ListUserOptions` works fine.

```
	git := gitlab.NewClient(nil, *token)
	git.SetBaseURL(*baseUrl)

	options := gitlab.ListUsersOptions{
		Username: username,
	}

	usrs, _, err := git.Users.ListUsers(&options)

	if err != nil {
		panic(err)
	}

	fmt.Println(usrs[0].ID)
```

**Comment by 45cali** [comment]
Not needed
