### ISSUE TITLE
Approve Merge Request has wrong verb

### ISSUE THREAD

**Issue by miekg** [xanzy/go-gitlab#512]
Hello,

This code: https://github.com/xanzy/go-gitlab/blob/master/merge_request_approvals.go#L95 is doing a GET, but it needs[*] to be a 'POST'

[*]: https://docs.gitlab.com/ee/api/merge_request_approvals.html#approve-merge-request

**Comment by svanharmelen** [comment]
Good catch! Fixed in b7192664a3bc1f96889d8756521c1f4037b490d6

**Comment by miekg** [comment]
excellent!
