### ISSUE TITLE
The properties in the GroupMember struct are not in-sync with the API response

### ISSUE THREAD

**Issue by praneetloke** [xanzy/go-gitlab#516]
Looks like GitLab has updated the API response. Source: https://docs.gitlab.com/ce/api/members.html. The `email` and `created_at` fields are no longer available and instead `avatar_url` and `web_url` are now returned in the response to listing a group's members.

**Comment by svanharmelen** [comment]
There's not a real schedule, so mainly when people ask or when I think enough has been changed/added.

So since you asked... v0.11.7 is just released :wink:
