### ISSUE TITLE
json: cannot unmarshal array into Go value of type gitlab.Wiki

### ISSUE THREAD

**Issue by 0x-1** [xanzy/go-gitlab#518]
Hey,

I guess something with the new json/unmarshal from #490 does not work for the create/edit wiki api?
error: "json: cannot unmarshal array into Go value of type gitlab.Wiki"

I've run go get -u ./... so all dependencys are up to date and my Go version is 1.11.1

The version #486 on my laptop still works tho. Reseting my pc version to #486 does not solve the problem. I'm confused, did some dependency of the project change and break the wiki unmarshaling?

**Comment by svanharmelen** [comment]
Hi @0x-1, can you give a small code example and the actual error you are getting? As looking at the source code of `wikis.go` and the Gitlab API I cannot see that would cause any errors here.

When I look beyond the code in `wikis.go` I also see that the same `Wiki` struct is used in `search.go` and it seems the response from those API's is not actually matching the `Wiki` struct. So are you using search API when you encounter the error?

In that case I think we should create a new dedicated struct for these APIs called `WikiBlob` or something. Either way, this doesn't seem to be related to the changes made in #490 but it could still be a bug that we need to fix.

**Comment by svanharmelen** [comment]
Any updates on this one @0x-1? If not I'm going to close this issue before the new year starts :wink:

**Comment by svanharmelen** [comment]
Closing this for now, feel free to reopen or open a new issue if you want to pick this up again.
