### ISSUE TITLE
Issue creation example

### ISSUE THREAD

**Issue by xichengliudui** [xanzy/go-gitlab#531]
I want to create an issue now, can you provide an example? If not, I feel very laborious! thanks！

**Comment by svanharmelen** [comment]
I would suggest looking at the existing [examples](https://github.com/xanzy/go-gitlab/blob/master/examples) for inspiration. The API is very consistent in how it is should be used, so the [project](https://github.com/xanzy/go-gitlab/blob/master/examples/projects.go) example maps pretty wel to how you can create an issue.

And of course there are the [Gitlab API](https://docs.gitlab.com/ce/api/issues.html) docs and [Godoc](https://godoc.org/github.com/xanzy/go-gitlab) to find more info/details.
