### ISSUE TITLE
Add Support for rebase in Merge Request

### ISSUE THREAD

**Issue by aini207080** [xanzy/go-gitlab#533]
[https://docs.gitlab.com/ce/api/merge_requests.html#rebase-a-merge-request ](url)-> Automatically rebase the source_branch of the merge request against its target_branch，it is supported in the API
I think it's cool，I need this feature. Can you help me add it?
thank you

**Comment by svanharmelen** [comment]
I think this PR should add support for rebasing MRs: https://github.com/xanzy/go-gitlab/pull/534

**Comment by aini207080** [comment]
Wow, thank you very much for responding to my request so quickly. I saw your submission and hope to add it to the new version as soon as possible.
