### ISSUE TITLE
Add support for board_issue_update api 

### ISSUE THREAD

**Issue by leejie123** [xanzy/go-gitlab#550]
Gitlab website it could drag and drop the issue in the board, api like this:
```
Request URL: http://host/-/boards/1/issues/5

params:
{
from_list_id: 32
move_after_id: null
move_before_id: null
to_list_id: 31
}
```
but can not find this api in gitlabclient.Boards

**Comment by svanharmelen** [comment]
@leejie123 it looks like that API is already supported: https://github.com/xanzy/go-gitlab/blob/master/boards.go#L214 But maybe it misses some options/fields?

And could you please add a link to the API docs that describes the API you are referring to?

**Comment by coreyvan** [comment]
Looking through the documentation, I don't see where this API is made available in V4. Since lists are just based on Labels, you might be able to replicate the behaviour by editing them on an issue. Depends on what your use case is I suppose.

**Comment by svanharmelen** [comment]
I'm going to close this issue as this is not something I want to add or fix until this is also supported and documented by the GitLab API.
