### ISSUE TITLE
usage of parseID outside of go-gitlab

### ISSUE THREAD

**Issue by pschwartz** [xanzy/go-gitlab#562]
Recently, I have found myself implementing a copy of parseID in my code to make actions against API's that take Options easier.

Would anyone be against changing parseID to be exported or a wrapper around parseID that exposes it?

**Comment by svanharmelen** [comment]
I don't think we should export the `parseID` function. It's not part of what this package offers and it would prevent us from making any changes in the future (not knowing what other people may be using it for).

Last but not least, it's such a small simple function that I believe copying the few lines of code is well worth not having the additional dependency.

Thanks for the suggestion and glad that you could reuse the logic though 👍
