### ISSUE TITLE
Support for group labels API

### ISSUE THREAD

**Issue by odin243** [xanzy/go-gitlab#563]
I was examining the labels code, and it doesn't look like there's any support for the labels API within a group (rather than a project): https://docs.gitlab.com/ce/api/group_labels.html

Unless I missed it somewhere, is this something you'd be open to a PR for?

**Comment by svanharmelen** [comment]
Sure, I'm always open to PRs 😉

**Comment by kirecek** [comment]
Any update here? I can work on this if there is no assignee :)

**Comment by svanharmelen** [comment]
There's no assignee, so by all means 👍

**Comment by svanharmelen** [comment]
This issue is fixed by PR #579
