### ISSUE TITLE
"two_factor_enabled" always false

### ISSUE THREAD

**Issue by Eraac** [xanzy/go-gitlab#564]
I want to track who wasn't enable 2FA on gitlab, but method `gitlab.Users.GetUser(xx)` return always false for key `two_factor_enabled`, seems to be logic according to the documentation, this field seems to be here only for admin

But, on gitlab.com i can see this information with my account, so is there any method from the api for retrieve this information despite i am a non-admin user

FYI i don't want to track ALL users but only users under my own group where i am the owner

**Comment by svanharmelen** [comment]
Maybe you can check what API calls are done when using gitlab.com? You should be able to see all API call using the developer tools from your browser. Maybe that points you into the correct direction.

**Comment by Eraac** [comment]
On this part, gitlab render page from server-side, so no api call. They add `two_factor=disabled` when you enable the filter, but after a try on the api this parameter change nothing

**Comment by svanharmelen** [comment]
I guess this question should be asked to Gitlab. This package implements support for the Gitlab API, so if you know which API you need, we can check if it's supported.

But finding out which API you need and if your use case is something that is supported using the API, is a question I cannot answer and should be asked to Gitlab instead.

**Comment by svanharmelen** [comment]
@Eraac is there any news around this issue? Is there something concrete that we can do to follow up on this, or is it a Gitlab related thing (in which case I think we should close this issue)?

**Comment by Eraac** [comment]
@svanharmelen this issue can be close, i will see with gitlab directly, thx
