### ISSUE TITLE
Uploading a file

### ISSUE THREAD

**Issue by matm** [xanzy/go-gitlab#57]
Is there a way to upload an attachment? I can see `Note.Attachment` in the library doc, but no related method to upload a file and reference it in a note for example.

GitLab has an API endpoint for that:  http://doc.gitlab.com/ce/api/projects.html#uploads

If not, I can add support for it as a method of `ProjectsService`.

**Comment by svanharmelen** [comment]
Hmm... No I don't think it exists already, so by all means add it to the `ProjectsService` 👍

**Comment by svanharmelen** [comment]
Fixed by PR #215
