### ISSUE TITLE
Support for Container Registry API

### ISSUE THREAD

**Issue by ivanetchart** [xanzy/go-gitlab#571]
I was taking a look to the code but I think it's not supported yet. 

https://docs.gitlab.com/ee/api/container_registry.html. If you're ok with it, can I submit a PR for this?

Thanks!

**Comment by svanharmelen** [comment]
Thanks for reaching out @ivanetchart! And by all means, PRs are always welcome 👍

**Comment by ivanetchart** [comment]
Cool

Just made it. Looking forward for feedback,

Thanks!

**Comment by svanharmelen** [comment]
Thanks for the PR @ivanetchart!
