### ISSUE TITLE
Runner IP Address

### ISSUE THREAD

**Issue by sarge** [xanzy/go-gitlab#575]
Hi an interesting discovery I have found is the gitlab can return multiple ip addresses for the IP Address. Unsure if this is a configuration error on our site or not or is a consequence of running at an AWS Spot Instance managed by docker machine.

https://github.com/xanzy/go-gitlab/blob/master/runners.go#L42

"runner": {
                "id": 1,
                "description": "AWS EC2 Spot",
                "ip_address": "10.0.0.230, 127.0.0.1",
                "active": true,
                "is_shared": true,
                "name": "gitlab-runner",
                "online": true,
                "status": "online"
            },

**Comment by svanharmelen** [comment]
Hmm... Good find! So if this can be a comma separated list, I think we may have to change the field to just being a `string`.
