### ISSUE TITLE
Webhook event Label struct and Labels API Label struct shouldn't be the same.

### ISSUE THREAD

**Issue by mkc-msit** [xanzy/go-gitlab#577]
Webhook  

> {
>         "id": 206,
>         "title": "API",
>         "color": "#ffffff",
>         "project_id": 14,
>         "created_at": "2013-12-03T17:15:43Z",
>         "updated_at": "2013-12-03T17:15:43Z",
>         "template": false,
>         "description": "API related issues",
>         "type": "ProjectLabel",
>         "group_id": 41
>      }
> 

Labels API structure:

> {
>     "id" : 1,
>     "name" : "bug",
>     "color" : "#d9534f",
>     "text_color" : "#FFFFFF",
>     "description": "Bug reported by user",
>     "open_issues_count": 1,
>     "closed_issues_count": 0,
>     "open_merge_requests_count": 1,
>     "subscribed": false,
>     "priority": 10,
>     "is_project_label": true
>   }

**Comment by bzssm** [comment]
Please fix it.

**Comment by hyorigo** [comment]
The same. Please fix this bug!

**Comment by UnacceptableUse** [comment]
Does anyone know if this is fixed?

**Comment by Deichindianer** [comment]
Seems like this has been correct since a35b520b9a96ad4193fb91ce3b422d3519a446bf
@svanharmelen this can probably be closed? Just stumbled on this while browsing :)

**Comment by svanharmelen** [comment]
Thanks for letting me know 👍🏻
