### ISSUE TITLE
Possibility to download ZIP archives

### ISSUE THREAD

**Issue by bonifaido** [xanzy/go-gitlab#587]
If I'm right, it is currently not possible to download ZIP format archives as per this snippet https://github.com/xanzy/go-gitlab/blob/master/repositories.go#L152 because the format is not specified in the URL and according to the GitLab documentation if there is no format specified the default will be `tar.gz` https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

Can we make this somehow work? I'm happy to submit a PR if we agree on a proper solution here.

**Comment by svanharmelen** [comment]
Thanks for opening this issue @bonifaido! Support to select custom formats is added in PR #589

**Comment by bonifaido** [comment]
Thank you for the fix @svanharmelen!
