### ISSUE TITLE
Add support for resource label events 

### ISSUE THREAD

**Issue by ravinwind** [xanzy/go-gitlab#600]
Gitlab EE supports using Resource label events API to keep track about who, when, and which label was added or removed to an issuable.

It's a great API.

Proposal would be to add support to go-gitlab for this: 
https://docs.gitlab.com/ee/api/resource_label_events.html

Guys can check this PR to see some more details.
https://github.com/python-gitlab/python-gitlab/pull/625

**Comment by mseelye** [comment]
We also needed this, so I just temporarily added it to my project with some ugly adhoc code.

QQ: If I were to fork this to help out with this, would this belong in the projects service code, or somewhere else like events? It seems like at least the projects resource label events would be in projects as projects is in the url.

**Comment by svanharmelen** [comment]
In general I'm trying to keep the services defined in the package in line with the documentation: https://docs.gitlab.com/ee/api/README.html

So in this case I think it should probably be best to add another service called `ResourceLabels` or maybe `ResourceLabelEvents`.

**Comment by mseelye** [comment]
@ravinwind @svanharmelen Here is what I have for this. I don't have epics on my account, and we don't use MR labels, so I've only actually tested the project-issue functions.

Please take a peek and comment, if everyone is happy I can put up a MR:

https://github.com/mseelye/go-gitlab/pull/1

**Comment by mseelye** [comment]
I think this is closed. @ravinwind let us know if it works for you too.

**Comment by svanharmelen** [comment]
Yes, this should be fixed by #642 now 👍🏻

**Comment by ravinwind** [comment]
> I think this is closed. @ravinwind let us know if it works for you too.

@mseelye It does work. Thanks for the help. Highly appreciated~
