### ISSUE TITLE
Add Enterprise Merge Request Self Approvals

### ISSUE THREAD

**Issue by ipauldev** [xanzy/go-gitlab#601]
Add Enterprise Merge Request Self Approvals API functionality added in:

https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/10050

**Comment by markuslackner** [comment]
I think this is already implemented and could be closed. Looking at the linked merge request its about the field `merge_requests_author_approval` and this is available in projects API: https://github.com/xanzy/go-gitlab/blob/ea8a48513e1b409b760ebf3cfcbffb765ae2d40b/projects.go#L1366

**Comment by svanharmelen** [comment]
I think your right 👍🏻  I'll close this one, but feel free to reopen it if we are still missing something for this request. Thanks!
