### ISSUE TITLE
404 Error when list projects whose owner(user/group) has a name contains dot

### ISSUE THREAD

**Issue by hoozecn** [xanzy/go-gitlab#604]
Gitlab community edition allows to create users/groups with username has dot. But when make  requests to list projects under this owners, the api returns 404 when the dot is unescaped.

A related fix: #603

**Comment by hoozecn** [comment]
![image](https://user-images.githubusercontent.com/949360/55857101-d0f22000-5b9e-11e9-95fb-29353bfdc189.png)

![image](https://user-images.githubusercontent.com/949360/55857076-c33c9a80-5b9e-11e9-85a2-fb23a534121b.png)

**Comment by svanharmelen** [comment]
This is fixed by PR #613
