### ISSUE TITLE
Add Enterprise LDAP Sync

### ISSUE THREAD

**Issue by zoidbergwill** [xanzy/go-gitlab#605]
As a start I was gonna add it to the group details and add the endpoint for adding the LDAP group link

https://docs.gitlab.com/ee/api/groups.html#add-ldap-group-link

**Comment by svanharmelen** [comment]
Sounds good 👍

**Comment by ptzool** [comment]
Hi,

Any info about this feature?

**Comment by zoidbergwill** [comment]
@ptzool Created an MR for it.

**Comment by zoidbergwill** [comment]
I used this in a self-service portal I was working on, to get around the non-granular GitLab admin and API permissions, so it does work.
