### ISSUE TITLE
get file 404

### ISSUE THREAD

**Issue by lou-lan** [xanzy/go-gitlab#643]
get file `a a+a.yaml` 404

we used `url.PathEscape("a a+a.yaml")`
```
a%20a+a.yaml
```
gitlab need
```
a%20%20a+a.yaml
```

**Comment by svanharmelen** [comment]
@lou-lan I'm afraid I don't get it. A single space is supposed to be converted to a single `%20`. So can you share some more details about what (you think) is the problem?

**Comment by lou-lan** [comment]
Yes, A single space is supposed to be converted to a single `%20`. In some cases gitlab needs `%20%20`, you can create case file `a a+a.yaml`, I don't know this particular pattern.

**Comment by svanharmelen** [comment]
I can only assume this is a bug in the Gitlab API. If the filename contains only a single space, it correctly gets a singe `%20`. So if then the Gitlab API returns a 404, I suggest you open an issue with Gitlab.

Did you try to reproduce your findings with cURL? Maybe that helps to give more insights.
