### ISSUE TITLE
Branches are not path-escaped as specified in GitLab's docs

### ISSUE THREAD

**Issue by anurag** [xanzy/go-gitlab#654]
The library doesn't run `url.PathEscape` on branch names as specified in GitLab API docs here:

https://docs.gitlab.com/ce/api/README.html#branches-and-tags-name-encoding

Since it already does this for projects and tags, it would be great to have it also do this consistently for branch names or the `sha` (when getting the latest commit using the branch name).

**Comment by svanharmelen** [comment]
I'm open to that 👍 Yet I currently don't have much time to actually implement it... So if you feel your up to it, by all means open a PR for it 😉

**Comment by anurag** [comment]
Cool. Will do eventually!
