### ISSUE TITLE
ExportDownload404

### ISSUE THREAD

**Issue by TjuLml** [xanzy/go-gitlab#656]
gitClient.ProjectImportExport.ExportDownload(project.ID)
{message: 404 Not found or has expired}

**Comment by svanharmelen** [comment]
@TjuLml if you want me to have a look at this, you need to provide more info... Maybe a working example and some more context.

**Comment by svanharmelen** [comment]
@TjuLml please provide a bit more details. Without that I'm going to have to closer this issue. Thanks!

**Comment by TjuLml** [comment]
The problem has been dealt with.you can close this issue.Thanks very much for your help.


------------------ 原始邮件 ------------------
发件人: "Sander van Harmelen"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 下午4:36
收件人: "xanzy/go-gitlab"<go-gitlab@noreply.github.com>;
抄送: "其實丶幸福很簡單"<295554150@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xanzy/go-gitlab] ExportDownload404 (#656)




@TjuLml please provide a bit more details. Without that I'm going to have to closer this issue. Thanks!

**Comment by svanharmelen** [comment]
👍
