### ISSUE TITLE
IP address missing from runner details

### ISSUE THREAD

**Issue by klmitch** [xanzy/go-gitlab#657]
The `RunnerDetails` struct is missing a field for the IP address of the runner, which is provided as the `ip_address` key in the response from gitlab, as documented at https://docs.gitlab.com/ce/api/runners.html#get-runners-details

**Comment by svanharmelen** [comment]
By all means feel free to open a PR to add the missing fields. Ordering of struct fields is (trying) to use the same order as is used in the docs.
