### ISSUE TITLE
Update structs to reflect new fields

### ISSUE THREAD

**Issue by jippi** [xanzy/go-gitlab#658]
Hi,

First of all, thank you for a great project, it made my work for creating a GitLab <> Slackbot at work 100x easier.

I did, however, notice that a good chunk of the structs in `master` does not have all the fields that a recent GitLab API exposes.

Is there any plan to update these, or any automated way to do it to keep the maintenance burden down?

If it's "no" to both above, how would you recommend me to go about submitting updates - is there any requirements beyond just adding the fields to the structs?

Thank you

**Comment by svanharmelen** [comment]
Thanks for your question @jippi. The short answer is no, there aren't any plans to update the structs in master.

The slightly longer answer is that Gitlab is changing and updating their API continuously and there isn't a nice way to automate the syncing of structs. So the "usual" way is for people to make small PR's whenever they encounter a field they want to use is missing.

As for any requirements, the only thing I normally try to do is to keep the ordering of the fields consistent with how the fields are ordered in the Gitlab docs. This makes it easy to spot missing fields and to find fields in the docs.

**Comment by svanharmelen** [comment]
As this issue has no further open question, I'll close it for now.
