### ISSUE TITLE
Having project create issues against GitLab.com lately?

### ISSUE THREAD

**Issue by zaquestion** [xanzy/go-gitlab#661]
Curious if anyone here particularly @svanharmelen has seen any issues lately with the project create API?

Lab tests regularly against GitLab.com and have been noticing some issues since the latest `12.2.0-pre`  went live. Perhaps someone knows and I just need to update or stop sending a field? Honestly have had a chance to look to closely.

@svanharmelen feel free to close after you see this, was just reaching out, hope you're doing well I've see all the activity on `go-gitlab` :D

**Comment by svanharmelen** [comment]
@zaquestion I must admit that I'm not using this package much myself lately. Just try to be a good maintainer and facilitator 😉 So I'll keep the issue open for bit to see if anyone else has some feedback...

**Comment by alexkalderimis** [comment]
What issues are you seeing @zaquestion?

**Comment by zaquestion** [comment]
@alexkalderimis my bad probably should have included that :blush: 

https://github.com/zaquestion/lab/issues/329

```
project_create.go:67: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {visibility_level: [internal has been restricted by your GitLab administrator]}}
```

Not expecting anyone to dig this deep, but just for completeness heres the test we have: https://github.com/zaquestion/lab/blob/master/cmd/project_create_test.go

**Comment by zaquestion** [comment]
Perhaps is internal not a thing anymore on gitlab.com ? Again really just curious if anyones seen this, not expecting anyone to dig into stuff thats ultimately on `lab` team to figure out.

**Comment by zaquestion** [comment]
Turns out it was that, GitLab.com removed internal, still a thing for onprem it sounds https://github.com/zaquestion/lab/issues/329#issuecomment-525961135
