### ISSUE TITLE
Inconsistencies in naming

### ISSUE THREAD

**Issue by mvdan** [xanzy/go-gitlab#7]
e.g. `ListMergeRequests` and `ListProjectIssues`, when they both work with projects. Either make both have `Project`, or neither.

**Comment by svanharmelen** [comment]
I (tried) to just used the names that are used in the docs, so people reading/knowing the docs should be able to find the matching methods easily.

So looking at your examples, have a look at [ListMergeRequests](http://doc.gitlab.com/ce/api/merge_requests.html#list-merge-requests) and [ListProjectIssues](http://doc.gitlab.com/ce/api/issues.html#list-project-issues) to see these names are also used like this in the docs...

**Comment by mvdan** [comment]
I see, fair enough then.
