### ISSUE TITLE
Support group field: runners_token 

### ISSUE THREAD

**Issue by sudoapt-getclean** [xanzy/go-gitlab#708]
In order to fix https://github.com/terraform-providers/terraform-provider-gitlab/issues/181
that wants to expose the runners token one would need access to the runners_token field of group (and project but that is already provided)

p.s. group now has a lot more fields than the Group struct provides, might be fun to expose more of that.
p.s.2 If you would prefer me to prepare a merge request let me know.

**Comment by svanharmelen** [comment]
A PR for this would be very much appreciated!

**Comment by jrdelarosa8** [comment]
I'd like to attempt to help with this. Please assign this to me.

**Comment by svanharmelen** [comment]
There you go 👍
