### ISSUE TITLE
Support Issue Statistics API

### ISSUE THREAD

**Issue by sluongng** [xanzy/go-gitlab#730]
https://docs.gitlab.com/ee/api/issues_statistics.html

It would be nice to have this as part of the lib

**Comment by vavilen84** [comment]
@svanharmelen I can take this

**Comment by svanharmelen** [comment]
Fine with me @vavilen84 All yours 😉

**Comment by vavilen84** [comment]
@svanharmelen Please, review https://github.com/xanzy/go-gitlab/pull/901

**Comment by mhutter** [comment]
Fixed by #901 I think 👍

**Comment by svanharmelen** [comment]
Indeed 👍
