### ISSUE TITLE
Branch type doesn't include "can_push"

### ISSUE THREAD

**Issue by coreyvan** [xanzy/go-gitlab#733]
The Gitlab API specifies a field called "can_push" to denote if pushes are allowed to the branch. This is missing from the definition of the Branch type in branches.go

I've got a PR for this change and some tests. Can you advise on how I can push and create the PR? Apologies, I'm new to contributing.

**Comment by svanharmelen** [comment]
Sorry for the super late reply!

Feel free to just open a PR. As soon as you have some that I can look at, I can help you towards getting the PR in a good state.
