### ISSUE TITLE
Awarding an emoji to a note does not appear to work

### ISSUE THREAD

**Issue by rpetti** [xanzy/go-gitlab#734]
I'm currently attempting to use the `CreateMergeRequestAwardOnNote` function, and for some reason it appears that the request generated by the API is just posting `null` to the GitLab endpoint. This results in the award failing since GitLab is not being provided with the emoji name.

It looks like it might be caused by the following line passing in `nil` instead of the opts that I'm providing the function.
https://github.com/xanzy/go-gitlab/blob/457d4d018eaa1fad8e6c63502cebcd11ba60164e/award_emojis.go#L408

**Comment by svanharmelen** [comment]
@rpetti good catch! That's indeed a bug...

**Comment by svanharmelen** [comment]
Fixed in release `v0.22.1`
