### ISSUE TITLE
Implement "Require code owner approvals for a single branch"

### ISSUE THREAD

**Issue by slamdev** [xanzy/go-gitlab#736]
Seems like it is a new endpoint:
https://docs.gitlab.com/ce/api/protected_branches.html#require-code-owner-approvals-for-a-single-branch

Would be nice to have it implemented in the library

**Comment by cpackingham** [comment]
Is this issue completed?

**Comment by svanharmelen** [comment]
Yes, seems like it. Good one @cpackingham!
