### ISSUE TITLE
Add support for `has_conflicts` in MergeRequest struct

### ISSUE THREAD

**Issue by ecornelisse** [xanzy/go-gitlab#744]
The response of gitlab for merge requests now contains a boolean `has_conflicts`

https://docs.gitlab.com/ee/api/merge_requests.html

it would be nice to be able to read that from the MergeRequest struct

**Comment by mdeltour** [comment]
Hello, 

If it'll help :) 
https://github.com/xanzy/go-gitlab/pull/788

**Comment by svanharmelen** [comment]
Fixed by PR #788
