### ISSUE TITLE
Get LDAP Group with LDAP Sync enable failed

### ISSUE THREAD

**Issue by benoitmenard-richemont** [xanzy/go-gitlab#745]
Hi,

I have an issue with Terraform Provider Gitlab and Gitlab EE with LDAP Sync (on subgroup), but it seem to come from this code.

The output of the provider is:
`Error: json: cannot unmarshal number into Go struct field Group.ldap_access of type bool`

In the file groups.go I change this:
`	LDAPAccess                     bool               `json:"ldap_access"``
to:
`	LDAPAccess                     int               `json:"ldap_access"``

then, compile, and everything worked as expected
I didn't find a lot of documentation about this fields. But it seems to be integer like Gitlab Access (10,20,30 ...)

Thanks,

**Comment by gillesdouaire** [comment]
I am running in the same thing.

**Comment by gillesdouaire** [comment]
(and the above workaround unblocked my stuff)
