### ISSUE TITLE
AssigneeID should not be *int

### ISSUE THREAD

**Issue by sluongng** [xanzy/go-gitlab#751]
AssigneeID in https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L146 which is used in ListMergeRequests() could be 
- int(user id) 
- OR "None" which will return a list of unassigned merge request 
- OR "Any" which will return a list of assigned merge request.

Reference: https://docs.gitlab.com/ce/api/merge_requests.html#list-merge-requests

Suggestion: We can consider changing this from `*int` to `interface{}` since there is no union typing in golang

**Comment by svanharmelen** [comment]
Nice catch, but changing `*int` to `interface{}` will not be enough to support the full API. It will also need a custom (un)marshal method to be able to support all options properly.

**Comment by mhutter** [comment]
> It will also need a custom (un)marshal method to be able to support all options properly.

I was curious about this so I did a little test, and turns out Go's JSON library handles this pretty neatly already! See https://play.golang.org/p/w5yodAl_Tp7

However, I assume this will break compatibility with existing code?

**Comment by ax1036** [comment]
@mhutter This is more like this line: https://github.com/xanzy/go-gitlab/blob/master/types.go#L407

Unmarshal for both int value and "None" / "Any"

**Comment by mhutter** [comment]
I see, but how would you implement a type that can be either an int, "None" or "Any"?

**Comment by Bouwdie** [comment]
@svanharmelen I do think we can abstract some things away for the value object. Also, the json encode and decode are not needed since they are only used in get request options and never in a body, I could remove them. Let me know what you think :space_invader:
