### ISSUE TITLE
Missing Merge Request approval state api

### ISSUE THREAD

**Issue by sluongng** [xanzy/go-gitlab#753]
Reference https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-the-approval-state-of-merge-requests

This api is quite handy when you need to get details of approval status on a merge request.

**Comment by granular-ryanbonham** [comment]
Open MR https://github.com/xanzy/go-gitlab/pull/766

**Comment by svanharmelen** [comment]
Support for this was added by PR #766
