### ISSUE TITLE
How to upload files, especially compress packages，such as jar files、rar files

### ISSUE THREAD

**Issue by Clearlove-X** [xanzy/go-gitlab#757]
I am calling the SDK to create the file to upload the file. However, uploading the rar file in this way will invalidate the file and only create some text files

**Comment by svanharmelen** [comment]
Is this still an issue for you? And if so, can you share more details?

**Comment by svanharmelen** [comment]
I'm going to close this due to leak of response. Feel free to reopen the issue if you want to follow up on it.
