### ISSUE TITLE
Missing CreateGroupIssueBoard function

### ISSUE THREAD

**Issue by paulvollmer** [xanzy/go-gitlab#767]
Hello,

it looks like the `func` to create group issue boards is missing for https://godoc.org/github.com/xanzy/go-gitlab#GroupIssueBoardsService
here are the gitlab api docs: https://docs.gitlab.com/ce/api/group_boards.html#create-a-group-issue-board-premium

or maybe i don't find the right go func to create a group board.
if the func is missing, i can implement it if you like.

thanks in advance, paul

**Comment by paulvollmer** [comment]
I send a PR for that right now...

**Comment by svanharmelen** [comment]
Thanks! Fixed by PR #768

**Comment by paulvollmer** [comment]
@svanharmelen thank you for the fast merge
