### ISSUE TITLE
Add `web_url` field to `Issue`

### ISSUE THREAD

**Issue by the-shank** [xanzy/go-gitlab#77]
The [`Issue`](https://godoc.org/github.com/xanzy/go-gitlab#Issue) struct (and the parsing stuff etc.) does not have the `web_url` field.

Would you be willing to accept a PR in case, I make the necessary changes to add the same?

**Comment by svanharmelen** [comment]
@the-shank, yes PR's are very much welcome :wink: Thx!

**Comment by the-shank** [comment]
@svanharmelen Please check the latest commit in the PR.
