### ISSUE TITLE
g tools 1.13.8 does not work

### ISSUE THREAD

**Issue by mizunos** [xanzy/go-gitlab#781]
Getting the library today.  I am using go 1.13.8.

go get this package but it will not compile.  error mismatched with go tool 1.13.8

**Comment by svanharmelen** [comment]
Can you share the exact error?

**Comment by mizunos** [comment]
Close my previous issue.  I think my GOTOOLDIR pointed to a different version of Go tools.  Cleanup all the go installation and the error went away.
