### ISSUE TITLE
Cannot get issue/MR by internal ID

### ISSUE THREAD

**Issue by mvdan** [xanzy/go-gitlab#8]
I just tried to use `GetIssue` to fetch information on an issue on a project of mine. To my surprise, it gave a 404.

Digging through the gitlab api docs, I found out that in `/projects/:id/issues/:issue_id`, `:issue_id` is global, and not local.

Hence, `GetIssue` is of very little use. I had to use `ListProjectIssues` with `&client.ListProjectIssuesOptions{IID: n}` for it to work.

I'm not saying this is an issue on your end - this very much looks like a bug or a misfeature on their API. We should ask them about it, and add a comment on methods like `GetIssue` that suffer from this if they are not going to fix it.

**Comment by svanharmelen** [comment]
@mvdan I hear you, but indeed don't think I can do much about it in here... There is already a comment linking to the GitLab docs on to of every function, so I think that should be enough for people to get more info about a specific API call:

```go
// GetIssue gets a single project issue.
//
// GitLab API docs: http://doc.gitlab.com/ce/api/issues.html#single-issues
func (s *IssuesService) GetIssue(pid interface{}, issue int) (*Issue, *Response, error) {
```

And of course if you are coding against the GitLab API, you will need to get familiar with it anyway right?

So I'll close this one and leave it up to you wether or not to create an issue with GitLab for this one.

Thx!

**Comment by mvdan** [comment]
I'm bothered by such a simple yet annoying issue, so I opened [#2465](https://gitlab.com/gitlab-org/gitlab-ce/issues/2465).

**Comment by svanharmelen** [comment]
:+1: would be nice if they agree on updating/changing this...

**Comment by mvdan** [comment]
In case anyone stumbles upon this, this issue hasn't been fixed yet on their end.
