### ISSUE TITLE
Pipelines API

### ISSUE THREAD

**Issue by wahmedswl** [xanzy/go-gitlab#80]
Hi, is there support for pipelines api

```
https://docs.gitlab.com/ce/api/pipelines.html
```

Thanks

**Comment by svanharmelen** [comment]
@wahmedswl no currently this is not supported... Of course PR's are always welcome 👍

**Comment by ivaravko** [comment]
@wahmedswl done https://github.com/xanzy/go-gitlab/pull/116

**Comment by svanharmelen** [comment]
👍🏻

**Comment by wahmedswl** [comment]
Thanks 👍
