### ISSUE TITLE
Add support for new list pagination

### ISSUE THREAD

**Issue by klmitch** [xanzy/go-gitlab#815]
gitlab is experimenting with a new means of performing pagination that promises to be more efficient for them; they're calling it ["Keyset-based pagination"](https://gitlab.com/help/api/README.md#keyset-based-pagination), and it uses the existing "per_page" query parameter and a new "pagination" parameter (set to the string "keyset").  It's intended to be used in conjunction with the `Link` header, which may specify some additional query parameters (their example includes "order_by", "sort", and "id_after").  It would be nice if go-gitlab could support this, so that go applications utilizing it could try out this new form of pagination.

(As of right now, it appears to only be implemented on the projects endpoint, with "order_by=id".  My read from discussions with them regarding this feature is that they intend to implement it across the board over the long term, though.)

**Comment by svanharmelen** [comment]
I'm not sure if I want to add support for this now already. And if we do, I'm not yet sure how we should support both the old and new solutions concurrently. Guess I need to have a closer look to find out and form an opinion...

Of course if you have specific ideas and/or am willing to create a PR, I'm always open to look at that or discuss it.

**Comment by klmitch** [comment]
Yeah, my purpose in opening this issue was to make sure to document it so everyone interested can begin to think about what it should look like.

**Comment by k-mckinney** [comment]
I noticed today on the documentation for the [repository tree API](https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree) that this endpoint has deprecated support for the `page` pagination in favor of keyset pagination, and it will be unsupported as of Gitlab 15.0.

**Comment by Shocktrooper** [comment]
As of right now all I can find in terms of deprecation of the old pagination for supported endpoints in go-gitlab is what @k-mckinney mentioned in the above thread.  With knowledge at least this endpoint we should completely transition this over before 15.0 and notify maintainers of downstream projects if we can. @timofurrer I looked and didn't see anything using this endpoint in the terraform provider.  If you could do a once over when you have time it would be appreciated.

**Comment by mitar** [comment]
Could we just add `Pagination` field to `ListOptions` for now? So that people can use it if they want. We can add any sugar on top later on.

**Comment by timofurrer** [comment]
> I looked and didn't see anything using this endpoint in the terraform provider. If you could do a once over when you have time it would be appreciated.

@Shocktrooper Yes, we are not using this API right now.

**Comment by pwlandoll** [comment]
#1827 has been merged, is that functionality sufficient to close this issue?

**Comment by klmitch** [comment]
After looking over the example included in the PR that you referenced, it does seem to me that this would address my concern.  Do you have an ETA on when a release will be cut with this functionality?  (Feel free to close the issue, I'm just leaving it open in the hopes that you'll answer my question :)

**Comment by svanharmelen** [comment]
Its already part of `v0.94.0`
