### ISSUE TITLE
Make retry configurable

### ISSUE THREAD

**Issue by klmitch** [xanzy/go-gitlab#822]
Currently, retries are hard-coded to always occur with hard-coded times and number of retries.  It would be really nice to be able to customize this; a back-of-the-envelope calculation based on the current hard-coded values suggests that a failing gitlab request won't time out for around 15 minutes, which may not be appropriate for all users.

**Comment by svanharmelen** [comment]
I'm about a PR that changes how a client can be created. The change enables adding option functions. So I also added three options for managing the retry logic. You can now disable retries all together or configure a custom backoff and/or retry policy.

See #813 for more details. I'll close this issue as it will be solved as soon as that PR is merged (end of this week probably).
