### ISSUE TITLE
Add New System Hook Optional Parameters Missing

### ISSUE THREAD

**Issue by MetalBlueberry** [xanzy/go-gitlab#824]
I've noticed that the optional parameters are not available in AddHookOptions.
Is there any other way to pass optional paramters?

https://docs.gitlab.com/ee/api/system_hooks.html#add-new-system-hook
```
opt := &gitlab.AddHookOptions{
	URL: &hookEndpoint,
}
```

i've tried to add to token parameter by modifying the AddHookOptions in a fork, but it seems that Gitlab doesn't like it. :(

**Comment by MetalBlueberry** [comment]
Did you try this implementation? I've tried id adding only the Token and Gitlab seems to reject it.

**Comment by svanharmelen** [comment]
See the docs, `URL` is required so it needs at least that. The rest is optional: https://docs.gitlab.com/ee/api/system_hooks.html#add-new-system-hook

**Comment by MetalBlueberry** [comment]
I'm sorry, I've tested the master version and it works like a charm.
Thank you very much for the quick response.
