### ISSUE TITLE
Support pagination in BuildsService.ListProjectBuilds

### ISSUE THREAD

**Issue by JonathonReinhart** [xanzy/go-gitlab#83]
Currently, [`BuildsService.ListProjectBuilds()`](https://godoc.org/github.com/xanzy/go-gitlab#BuildsService.ListProjectBuilds) will only return the 20 most recent builds.

The [GitLab API documentation](http://docs.gitlab.com/ce/api/builds.html#list-project-builds) doesn't indicate which endpoints use pagination and which ones do not, but I've experimentally determined that `GET /projects/:id/builds` indeed does use pagination, and supports `page` and `per_page`.

In `go-gitlab`, the [`ProjectsService.ListProjects()`](https://godoc.org/github.com/xanzy/go-gitlab#ProjectsService.ListProjects) API for example, takes a [`ListProjectsOptions`](https://godoc.org/github.com/xanzy/go-gitlab#ListProjectsOptions) argument, which embeds a [`ListOptions`](https://godoc.org/github.com/xanzy/go-gitlab#ListOptions) struct which handles the pagination. [`ListBuildsOptions`](https://godoc.org/github.com/xanzy/go-gitlab#ListBuildsOptions) on the other hand does not embed `ListOptions`.

**Comment by JonathonReinhart** [comment]
I see that this was recently added in #71 by @arkbriar. Was there any reason this was left out, or just overlooked?

**Comment by svanharmelen** [comment]
@JonathonReinhart I guess it was overlooked... Will add it in a few, thx!

**Comment by JonathonReinhart** [comment]
Works great, thanks for taking care of this so quickly!
