### ISSUE TITLE
Release v0.31.0 is breaking

### ISSUE THREAD

**Issue by 6543** [xanzy/go-gitlab#837]
please leave a note to the release what is to change to migrate to this release.

**Comment by svanharmelen** [comment]
I did make an issue to inform people, but agree I've could it in the release notes as well: https://github.com/xanzy/go-gitlab/issues/826

**Comment by svanharmelen** [comment]
Done: https://github.com/xanzy/go-gitlab/releases/tag/v0.31.0

**Comment by 6543** [comment]
@svanharmelen "Sorry for any inconveniences caused by this":

as long as v0. ... this should be expect by those who use that lib - but realy: thanks for adding this to the release notes :)

looking forward at using this lib 👍

**Comment by 6543** [comment]
and the link 'https://github.com/xanzy/go-gitlab/blob/svh/f-client-options/client_options.go' is wrong
better use `https://github.com/xanzy/go-gitlab/blob/master/client_options.go`

**Comment by svanharmelen** [comment]
Oeps, thats the link to the branch used for the changes. I’ll update it right away. Thanks!

**Comment by svanharmelen** [comment]
Done 👍🏻
