### ISSUE TITLE
Add support for option "Squash commits when merge request is accepted." for projects

### ISSUE THREAD

**Issue by MarcinNowak-codes** [xanzy/go-gitlab#838]
GitLab is working on option "Squash commits when merge request is accepted." for projects. Ticket for it is [Configurable defaults for "Squash commits" option](https://gitlab.com/gitlab-org/gitlab/-/issues/17613)

The ticket is since Mar 26, 2017 but MR is already in WIP status and is scheduled for GitLab 13.1. I added this issue to cross track progress. 

Issue [[Feature Request] Support for option "Squash commits when merge request is accepted." for projects](https://github.com/terraform-providers/terraform-provider-gitlab/issues/292) in project terraform-provider-gitlab depends on it.

**Comment by cpackingham** [comment]
The gitlab ticket you linked is closed, but it doesn't look like having commits squashed by default is available on the api - am I missing something?

**Comment by MarcinNowak-codes** [comment]
True. There is another MR https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33099 for API and it's already merged. 
In API documentation https://docs.gitlab.com/ee/api/projects.html is nothing about "Squash commits".
I raise the question https://gitlab.com/gitlab-org/gitlab/-/issues/17613#note_439580224

**Comment by ThePlenkov** [comment]
@MarcinNowak-codes it is there already 
![image](https://user-images.githubusercontent.com/6381507/135177555-5e4d5870-a94c-46db-b487-6c83cd8250ab.png)

**Comment by svanharmelen** [comment]
I think this is actually already supported by this package through PRs: #1194 and #1231. Is that correct, can this one be closed?

**Comment by MarcinNowak-codes** [comment]
The repository terraform-provider-gitlab was moved. Now the issue link is https://github.com/gitlabhq/terraform-provider-gitlab/pull/702 
There is one more PR by @mkjmdski to add this functionality to Terraform. We can close here. Thanks
