### ISSUE TITLE
Incorrect handling of API errors

### ISSUE THREAD

**Issue by sindrepm** [xanzy/go-gitlab#84]
I discovered a possible bug today related to how the client handles validation errors returned from the API. According to the [docs](https://docs.gitlab.com/ce/api/README.html#data-validation-and-error-reporting), validation errors will be formatted as following in the response:

``` json
HTTP/1.1 400 Bad Request
Content-Type: application/json
{
    "message": {
        "bio": [
            "is too long (maximum is 255 characters)"
        ]
    }
}

{
    "message": {
        "<property-name>": [
            "<error-message>",
            "<error-message>",
            ...
        ],
        "<embed-entity>": {
            "<property-name>": [
                "<error-message>",
                "<error-message>",
                ...
            ],
        }
    }
}
```

In the code, an error response body is always unmarshalled into a `ErrorResponse` struct:

``` go
type ErrorResponse struct {
    Response *http.Response // HTTP response that caused this error
    Message  string         `json:"message"` // error message
    Errors   []Error        `json:"errors"`  // more detail on individual errors
}
```

This fails because the struct does not correctly reflect the response, resulting in an empty `ErrorResponse` being returned.

I have no experience with the older versions of the Gitlab API, so don't know if the error response format has changed, or whether this always has been a bug.

**Comment by svanharmelen** [comment]
@sindrepm thanks for the report! I'll have a closer look at this coming week (if time permits)...

**Comment by sindrepm** [comment]
@svanharmelen had a chance to look into this yet?

**Comment by svanharmelen** [comment]
@sindrepm thanks for reminding me of this one and sorry for the delay... Will make sure to review and/or fix this this week.

**Comment by sindrepm** [comment]
@svanharmelen just wondering if this has been fixed by now?

**Comment by svanharmelen** [comment]
@sindrepm I must sadly admit I didn't yet get to this one. I didn't forget it and it's getting higher and higher on my todo list. So hang in there just a little while longer...

What would help me get started are a few (maybe curl) commands or code snippets that produce the different errors. That would speed up diving in and fixing any issues with the error handling greatly!

**Comment by sindrepm** [comment]
@svanharmelen if it is okay with you I can have a look at this and see if I can put together a PR with the changes needed.

**Comment by svanharmelen** [comment]
@sindrepm of course that is OK 👍  Thanks for your efforts!

**Comment by sindrepm** [comment]
@svanharmelen I have implemented parsing of the data validation errors according to the documented format here: https://docs.gitlab.com/ce/api/README.html#data-validation-and-error-reporting

To not introduce breaking changes I have left the old `ErrorResponse` unchanged, but added a new `ValidationErrorResponse`. If the API response cannot be unmarshaled as an `ErrorResponse`, it tries to unmarshal it as an `ValidationErrorResponse`.

What makes it a bit messy is the fact that the response can contain two levels of nesting (simple array of error messages for each field, or a map with embedded entities at the outer level. I could have just formatted everything as a string and put it as `Message` on `ErrorResponse`, but then you would lose the structure and not be able to access each field/message individually.

From the perspective of the consumer you can just check whether the type of error is a `ValidationErrorResponse` and do type assertions on the `.Message` map values:

```
type ValidationErrorResponse struct {
	Response *http.Response
	Message  map[string]interface{}
}
```

They will be one of `[]string` or `map[string][]string`.

Please have a look and let me know what you think.

**Comment by svanharmelen** [comment]
Thanks @sindrepm! I'm pretty time constrained atm, but will make sure to review the PR tomorrow or Wednesday!
