### ISSUE TITLE
why having a String() method

### ISSUE THREAD

**Issue by jgengo** [xanzy/go-gitlab#840]
Hello,

I'm currently creating a tool with go-gitlab, and was wondering why do you use *string for some of your struct like for example for `ListIssuesOptions`. It forces me to allocate a string and return the pointer. I've noticed that you are using your own String() function for that.

```
listProjectIssue := &gitlab.ListIssuesOptions{AssigneeID: &currentUser.ID, Scope: gitlab.String("all")}
assignedIssues, _, err := git.Issues.ListIssues(listProjectIssue)
```

It makes it longer and less clear.

Thank you in advance.

**Comment by svanharmelen** [comment]
@jgengo we use pointers in all option structs as a way to make a difference between sending a [zero value](https://tour.golang.org/basics/12) and not sending a value. There are more API client packages that use this pattern, and while maybe a bit strange at first it does actually serve a purpose.

For more background I would like to point you to this thread, which is one on many you can find out there were this patterns is discussed: https://github.com/aws/aws-sdk-go-v2/issues/205

I hope that will give enough background on this design choice...

**Comment by jgengo** [comment]
Hello @svanharmelen

It makes totally sense to me now. Thank you for your time.
