### ISSUE TITLE
per_page  max 100

### ISSUE THREAD

**Issue by 1032231418** [xanzy/go-gitlab#850]
Hi:

The number of pages, the largest one hundred, how to get all the items?

pagination | keyset (to enable keyset pagination)
per_page | Number of items to list per page (default: 20, max: 100)

**Comment by 1032231418** [comment]
```
opt := &gitlab.ListProjectsOptions{
	ListOptions:              gitlab.ListOptions{
		Page:    1,
		PerPage: 50000,
	},
}

projects, _, err := git.Projects.ListProjects(opt)
fmt.Println(len(projects))

100
```

**Comment by svanharmelen** [comment]
Did you try to omit the `ListOptions` field all together? So like:

```
opt := &gitlab.ListProjectsOptions{}

projects, _, err := git.Projects.ListProjects(opt)
```

**Comment by svanharmelen** [comment]
Additionally I would suggest to first try and test if your desired behavior is supported by the GitLab API using a cURL command. If that works, the next step is to see how we can create the same type of call using this API client.

**Comment by 1032231418** [comment]
Tested, not supported, gitlab api default 20 maximum 100

**Comment by 1032231418** [comment]
I can only turn pages internally

**Comment by svanharmelen** [comment]
So then your only option is to "walk" through the pages I guess. Not much I can do from this package if the API doesn't support it...

**Comment by 1032231418** [comment]
Ok， thank you

**Comment by binkkatal** [comment]
@1032231418 maybe you can try like the [bitbucket client](https://github.com/ktrysmt/go-bitbucket/blob/master/client.go#L221) does
