### ISSUE TITLE
ListGroupIssuesOptions missing WithLabelDetails

### ISSUE THREAD

**Issue by skast96** [xanzy/go-gitlab#852]
```WithLabelDetails *bool      `url:"with_labels_details,omitempty" json:"with_labels_details,omitempty"` ``` is missing in the ListGroupIssuesOptions.

**Comment by svanharmelen** [comment]
Added in https://github.com/xanzy/go-gitlab/commit/7389c7e09cbc8331b825744bbec412d07a22b7cb
