### ISSUE TITLE
Unmarshal error "WithLabelDetails"

### ISSUE THREAD

**Issue by skast96** [xanzy/go-gitlab#853]
``` json: cannot unmarshal object into Go struct field Issue.labels of type string ```

The error occurs when trying to get the labels of an issue with more information (color, etc).

**Comment by svanharmelen** [comment]
Hmm... So you didn't actually test #852 😏 Looking at what this switch does exactly, I think it's quite difficult to support this properly without making backwards breaking changes.

This switch changes the returned object, which in Go (being statically typed) makes parsing the response a bit difficult. I can still solve it, but not without breaking some stuff which I'm not sure am willing to do at this moment.

So I'm thinking about reverting the change for now. Thoughts?

**Comment by skast96** [comment]
Can`t we just check the value of the "Label" if it fits into the struct or not? I am not an GoLang specialist, but this is how I`d handle it in C# or Java.

**Comment by svanharmelen** [comment]
I think the main problem is how to present the type to users of the package. Parsing the unknown value to something we know is not difficult, but that would mean that the result struct always contains all the fields for a detailed label, as we cannot dynamically change the result type based on the given options. Or at least that becomes a whole lot more difficult...

So I'm thinking a little about the possible impact and usability of switching from `type Label []string` to `type Labels []LabelDetails`, as that could be a solution going forward.

**Comment by skast96** [comment]
Did you have a look at my solution I am parsing the object either to a string array or to a struct LabelDetails depending on the data that is received. The drawback is that the struct Label contains a interface named Data as the more abstract way would be a custom Marshal function for the struct Issue.

**Comment by svanharmelen** [comment]
Yeah, I already had a look at your solution before my previous reaction.

My problem with that approach is that it requires an `interface{}` field in the `Issue` struct (or the `LabelDetails` sub-struct), which makes it (IMO) very user unfriendly and not really ergonomic to use.

That’s why I was thinking about always using the ‘LabelDetails` as a sub-struct as then it no longer matters if you only get the name or all details, the struct people have to use will always be the same.

Of course this also requires some custom JSON methods, but thats fine.

**Comment by svanharmelen** [comment]
I Just thought of a nice solution for this. Will have a go at it later today or tomorrow...

**Comment by svanharmelen** [comment]
@skast96 please have a look at #861 as I think this is the best solution for this use case. After merging that PR `Labels` will always contain a slice with label names, and if `WithLabelDetails` was set, then additionally `LabelDetails` will contain a slice with label details. See the tests as well. Unless you foresee big issues, I'm going to merge this one to solve this issue.

**Comment by skast96** [comment]
@svanharmelen yeah that also a good solution thank you for your time :+1:
