### ISSUE TITLE
how to add InsecureSkipVerify for http client in version v0.31

### ISSUE THREAD

**Issue by zhangpy** [xanzy/go-gitlab#856]
I have to connect gitlab through a gateway and ignore the tls check. 
In v0.29, I could use
```go
c := &http.Client{Transport: &http.Transport{
 	TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}}
gitlab.NewClient(c, "token")
```
how to do this in new release? thanks.

**Comment by svanharmelen** [comment]
@zhangpy this example is actuall shown in the release notes: https://github.com/xanzy/go-gitlab/releases/tag/v0.31.0

**Comment by zhangpy** [comment]
thanks :)
