### ISSUE TITLE
could I get branch info related to an issue ?

### ISSUE THREAD

**Issue by yeqown** [xanzy/go-gitlab#873]
![image](https://user-images.githubusercontent.com/27146233/85219311-395ca400-b3d5-11ea-8b95-6b7d1695f358.png)

in the image, there is a link named `6-testfeat-issue`， I want to get thi, but found nothing helpful in `gitlab API`, anybody could provide any advise?

**Comment by svanharmelen** [comment]
I'm not sure if I understand your question correctly, but if this is about the functionality of the GitLab API (which it looks like to me) then I would suggest to have a look at the GitLab API [docs](https://docs.gitlab.com/ee/api/api_resources.html) or ask your question there if it's still unclear.

I don't know the answer from the top of my head and this is only a client using the functionality exposed by the API. So if you know _how_ you can achieve what you want using the API, then you only need to find the related calls in this client to make it work.

**Comment by yeqown** [comment]
I have a look at the GitLab API doc, I didn't found the related API, but I can get above page which contains the function in the image, so I ask here ~

**Comment by svanharmelen** [comment]
So where did you get the above page? I just spent 10 minutes of my time looking at this, but I cannot find a similar page. Willing to take another quick look if you clearly describe how (or were) I can generate such a page. But still believe this is a question for GitLab...

**Comment by yeqown** [comment]
Hah... I didn't mean that this issue is a question of `go-gitlab`, I just want some help ~ to achieve my goal. my goal is to get related branch of one issue by gitlab API, but I cannot not found an API could achieve that~

**Comment by svanharmelen** [comment]
Had another look, but as far as I can tell there is no API call to get the related branches.

I understand you are looking for support, but I still think you should ask this question to GitLab (here: https://gitlab.com/gitlab-org/gitlab/-/issues) as they are building and managing their API and should be able to confirm if an API exists for this and (if it does) what the API is called and how to use it.

When we know that, we can help here to see how that API can be called from this client. Without that info, its really hard to help you as (at least in this case) there isn't an obvious solution in the client already.

**Comment by yeqown** [comment]
got it, thanks a lot
