### ISSUE TITLE
Make `default_branch` nullable?

### ISSUE THREAD

**Issue by abitrolly** [xanzy/go-gitlab#875]
I noted that GitLab API may return `"default_branch": null,` for empty repos, which is transforms to the empty string through `go-gitlab`. It is probably a minor issue, because empty string is probably an invalid value for `default_branch`, but still - maybe it is better to return `nil` if it is not set?

**Comment by svanharmelen** [comment]
@abitrolly the API client is designed like this on purpose. Of course it's always debatable, but I found that having to `null` check and de-reference everywhere when you are trying to use a value is much more annoying then sometimes having to check a value. And to introduce it only for some fields would make the client much less consistent to use (you would have to check each field to see if it's a pointer or now). So I'm not really open to changing this, sorry!

**Comment by abitrolly** [comment]
@svanharmelen does something like https://github.com/guregu/null help?

**Comment by svanharmelen** [comment]
I usually use https://github.com/gobuffalo/nulls which is a similar package... So I am aware of these solutions, but think they weren't used that much when this package was originally created. And adding that now for all applicable fields would be a very big change which would cause backwards issues for every single user using this client.

I must admit it's an interesting idea, but I'm not sure if I would want to introduce it now...

**Comment by abitrolly** [comment]
Fair enough. Maybe next version. )
