### ISSUE TITLE
Project mirror configuration

### ISSUE THREAD

**Issue by lukemgriffith** [xanzy/go-gitlab#876]
GitLab's API now supports the configuration of mirror config https://docs.gitlab.com/ee/api/remote_mirrors.html

It would be great to support this, as I would like to implement it on the terraform provider. 

I can do the implementation.

**Comment by svanharmelen** [comment]
Hi @lukemgriffith, I noticed your PR but also noticed you closed it. I think it looked reasonable (saw a few issues, but nothing exiting). Feel free to reopen or update the PR and let me know when you want it to be reviewed 👍

**Comment by lukemgriffith** [comment]
hey @svanharmelen was doing some testing my side, think its good to go #879

**Comment by lukemgriffith** [comment]
One thing to note on this, i have a running thread with GitLab, although this is implemented as per the spec (and the same way the python library does), there are some issues with the API its self. Not something addressable here though, and it does function (i.e adding mirrors, updating, etc). Just some edges they need to configure. Don't believe its something this project needs to be concerned with.

https://gitlab.com/gitlab-org/gitlab/-/issues/225428

**Comment by lukemgriffith** [comment]
hey @svanharmelen  thanks for the assist on this, is there a schedule for the next tag? I'm keen to create this functionality for this in the terraform provider, would be great to know when a new tag with the project mirror additions will be available. 

Thanks

**Comment by svanharmelen** [comment]
Just created `v0.33.0` 👍
