### ISSUE TITLE
Typo in JSON hint for CreateProjectOptions.BuildsEnabled

### ISSUE THREAD

**Issue by seelensonne** [xanzy/go-gitlab#88]
There's a typo in the JSON hint for `CreateProjectOptions.BuildsEnabled`:

- Current: `json:"build_events,omitempty"`
- Correct: `json:"builds_enabled,omitempty"`

See https://github.com/xanzy/go-gitlab/blob/master/projects.go#L346

**Comment by svanharmelen** [comment]
Thanks for the report @seelensonne! Fixed in PR #89.
