### ISSUE TITLE
gitfile api

### ISSUE THREAD

**Issue by zzhzero** [xanzy/go-gitlab#885]
GitFile can use query string? my gitlab only work in `?file_path=`

**Comment by svanharmelen** [comment]
Not sure if I understand your issue. The `GetFile` method is a `GET` call that uses query strings. See [here](https://github.com/xanzy/go-gitlab/blob/master/repository_files.go#L68) for more info...

**Comment by svanharmelen** [comment]
Closing this issue due to a lack of response...
