### ISSUE TITLE
Cannot unmarshal issue JSON

### ISSUE THREAD

**Issue by jamesramsay** [xanzy/go-gitlab#907]
@xanzy I've run into a situation where I write out `Issue` to a JSON record (stored in BadgerDB or locally in a `ndjson` file) as part of a cache system. Previously this wasn't a problem, but in recent versions of `go-gitlab` this no longer works.

- v0.20.1 working: https://play.golang.org/p/jKxW7XrT5v3
- v0.21.0 broken: https://play.golang.org/p/QN5NKvdzoNz

Any help would be appreciated. Thanks 🙂

**Comment by svanharmelen** [comment]
Thanks for the nice issue report! Made it quite easy to find the root cause 👍 Should be fixed in version v0.34.2.

**Comment by jamesramsay** [comment]
@svanharmelen I think my example was too basic because `Labels` was `nil`, but any real world API response will return an array - empty or otherwise. See https://play.golang.org/p/a-sa9JlRmEp

**Comment by svanharmelen** [comment]
Fixed in PR #912
