### ISSUE TITLE
Add support for custom rate limiter

### ISSUE THREAD

**Issue by 2785** [xanzy/go-gitlab#909]
Sort of a feature request, use cases may include private gitlab instance not doing the rate limiting itself and not returning rate limit headers and / or when someone wishes to limit load to lower than what's automatically configured. 

Can make a pull request to add it, wanted some thoughts and considerations that I'm not thinking about :)

Thanks.

**Comment by svanharmelen** [comment]
You can already configure pretty much all rate limiter options, or give your own HTTP client which then can have it's own rate limiter: https://github.com/xanzy/go-gitlab/blob/master/client_options.go

So no need to do any coding for that :wink:

**Comment by 2785** [comment]
The retryable http takes a concrete `http.Client` not some sort of a generic interface value, can't inject rate limiter no? :thinking:

**Comment by svanharmelen** [comment]
Your right! I was too quick in typing my reply... I was looking at the retry logic not at the internal rate limiter. Sorry!

The internal rate limiter will be disabled if it doesn't receive the correct headers, so it should not be a problem if those headers are not given. There indeed is no way to configure your own rate limiter, but to be very honest I'm not too exited about adding a feature to do so.

Yet thinking about it just a little I do see a way that could introduce something like that, using an interface like:

```
type RateLimiter interface{
    Wait(context.Context)
}
```

And then in the `configureLimiter()` start with:

```
func (c *Client) configureLimiter() error {
	if c.limiter != nil {
		return nil
	}
	...
``` 

Guess that could be acceptable... But only if it really is as small as it seems 😏

**Comment by 2785** [comment]
Believe the nil check would be taken care of by the `sync,Once`, was thinking something like

```
func WithCustomLimiter(r rate.Limit, burst int) ClientOptionFunc {
	return func(c *Client) error {
		c.configureLimiterOnce.Do(func() {
			c.limiter = rate.NewLimiter(r, burst)
		})
		return nil
	}
}
```

I guess a `RateLimiter` interface would be cleaner :thinking:

**Comment by 2785** [comment]
Re: the piece on disabling internal rate limiter if it doesn't get the headers. My problem was that the rate limiting was performed at a netscaler level that's in front of the gitlab instance. Use case is to retrieve all merge request status / pipeline / approvals of a number of users and it can potentially spam quite hard and make the netscaler rate limiting kick in. (that setup isn't the greatest but...)

**Comment by svanharmelen** [comment]
Hmm... Well that also looks pretty reasonable to be honest. I think the main difference is that you are still bound to the `rate` package while with an interface you can practically insert everything you want. Guess both are acceptable solutions...

**Comment by 2785** [comment]
I'll go and implement the interface version a bit later and lets see how it looks like. Thanks for all the input!

**Comment by 2785** [comment]
I mean the library is already quite bound to `http`, `retryablehttp` etc :thinking:

**Comment by 2785** [comment]
Any plans to tag it anytime soon :nerd_face:  ?

**Comment by svanharmelen** [comment]
Done, `v0.35.0` 👍
