### ISSUE TITLE
Difference of struct between ListProjectIssuesOptions and ListProjectMergeRequestsOptions

### ISSUE THREAD

**Issue by brunellegrossmann** [xanzy/go-gitlab#915]
I've noticed a difference in the struct of ListProjectOptions for Issues and MergeRequests

```
 -type ListProjectIssuesOptions struct {
	ListOptions
	...
	Labels             Labels     `url:"labels,comma,omitempty" json:"labels,omitempty"`
	...
  }
```
```
 - type ListProjectMergeRequestsOptions struct {
	ListOptions
	...
	Labels          *Labels    `url:"labels,omitempty" json:"labels,omitempty"`
	...
   }
```

----------------------------------------------------------------------------------------------------

**Comment by svanharmelen** [comment]
Nice catch. I guess the latter needs to be updated to make it work as expected.

**Comment by ahuret** [comment]
looks related to https://github.com/xanzy/go-gitlab/pull/715
