### ISSUE TITLE
Unable to use URL with sub path

### ISSUE THREAD

**Issue by alexweide** [xanzy/go-gitlab#922]
We are hosting our own Gitlab instances which are accessible via "https://instance1.my.company.com/gitlab". So I try to access the instance using `git, err := gitlab.NewBasicAuthClient("MYUSERNAME", "MYPASSWORD", WithBaseURL("https://instance1.my.company.com/gitlab"))`. But I always receive 404, because it always tries to connect to "https://instance1.my.company.com/". Is there a way to set the sub path?

Go version 1.15

**Comment by svanharmelen** [comment]
So is the API endpoint then located at: `https://instance1.my.company.com/gitlab/api/v4`? As that will be the path used by the client after setting `https://instance1.my.company.com/gitlab` as base URL.

And can you share any errors or logging that shows what URL is actually being used?

**Comment by alexweide** [comment]
Right, the API endpoint is located at <code>https://instance1.my.company.com/gitlab/api/v4</code>. 

I think I found a solution: Adding the URL path here and in the following line should fix the issue: https://github.com/xanzy/go-gitlab/blob/ed99a969739b88065bcb4c0f7694d81f68e7f56c/gitlab.go#L677

**Comment by svanharmelen** [comment]
Fixed by PR #928
