### ISSUE TITLE
Add Support for AssigneeUsername in ListIssuesOptions

### ISSUE THREAD

**Issue by j-mcavoy** [xanzy/go-gitlab#925]
Add `assignee_username` as a parameter for list issues, similar to how it is already implemented for ListGroupIssueOptions.

**Comment by j-mcavoy** [comment]
https://github.com/xanzy/go-gitlab/compare/master...j-mcavoy:master

**Comment by j-mcavoy** [comment]
Relevant API docs https://docs.gitlab.com/ee/api/issues.html#list-issues

**Comment by j-mcavoy** [comment]
https://github.com/j-mcavoy/go-gitlab/blob/56b95cef2211eed5b057ce885b57b21995e7e016/issues.go#L214

**Comment by svanharmelen** [comment]
Fixed by PR #927
