### ISSUE TITLE
defaultBaseURL can't change?

### ISSUE THREAD

**Issue by BESTLyc** [xanzy/go-gitlab#941]
I want use it with Gitlab EE,so I should change the defaultBaseURL .Can I change defaultBaseURL in outside?

**Comment by svanharmelen** [comment]
Did you read the README? It actually shows an example for exactly this: https://github.com/xanzy/go-gitlab#usage

**Comment by BESTLyc** [comment]
ok:)my mistake.use gitlab.WithBaseURL() can do it

**Comment by svanharmelen** [comment]
👍🏻
