### ISSUE TITLE
Add support for User Memberships

### ISSUE THREAD

**Issue by edshelton** [xanzy/go-gitlab#944]
https://docs.gitlab.com/ee/api/users.html#user-memberships-admin-only

This would be useful to be able to get the lowest `access_level` for a given user in order to determine whether that user is using a license seat. Any GitLab user with an `access_level` of `20` or greater and a `state` that != `blocked` consumes a seat, `20` being the `Developer` role.

**Comment by cpackingham** [comment]
Mind if I take this one?

**Comment by svanharmelen** [comment]
By all means :)
