### ISSUE TITLE
Support for Freeze Periods API

### ISSUE THREAD

**Issue by pcnc** [xanzy/go-gitlab#946]
There is a new project-level Freeze Periods API that is currently not implemented in go-gitlab.

GitLab Issue: https://gitlab.com/gitlab-org/gitlab/-/issues/214328
API Docs: https://docs.gitlab.com/ee/api/freeze_periods.html

I submitted PR #945 as a potential candidate to add the missing API functionality in go-gitlab.

**Comment by svanharmelen** [comment]
Implemented by PR #945
