### ISSUE TITLE
ListIssuesOptions missing 'in' property

### ISSUE THREAD

**Issue by burtonr** [xanzy/go-gitlab#948]
I'm looking to be able to search issues by title only (as the descriptions can be quite long), but finding that the search is returning results that match the text in the description as well. 

I found that the search can be limited to only the title with the `in` parameter. However, that is not yet provided in this client.

GitLab documentation: https://docs.gitlab.com/ce/api/issues.html#list-issues
ListIssuesOptions source: https://github.com/xanzy/go-gitlab/blob/v0.38.1/issues.go#L201

Not sure if that was intentionally excluded, or if it was accidentally missed. I don't see when it was added, so it may be new.

Happy to put together a PR if it's something that would be welcomed.

**Comment by Starttoaster** [comment]
Hey! I'm not a maintainer here but can say from experience that GitLab actively develops their API so if something is not available in this package that the API supports (especially if it's documented in their API docs) then PR contributions are welcome

**Comment by svanharmelen** [comment]
Full agree with @Starttoaster (thanks!). PR's, especially from documented APIs, are always welcome 👍🏻

**Comment by burtonr** [comment]
Great! Thank you both for the feedback.

I'll get something together in the next day or two
