### ISSUE TITLE
json: cannot unmarshal

### ISSUE THREAD

**Issue by mustafayildirim** [xanzy/go-gitlab#96]
Hi, I am writing code for gitlab Push Hook event.
When I am Unmarshal the gitlab's example [https://docs.gitlab.com/ce/web_hooks/web_hooks.html#push-events](url)

But I have a problem with json unmarshal.
The output 
**json: cannot unmarshal string into Go value of type gitlab.ProjectNamespace**
jsonBlob is gitlab's example json.

`var e gitlab.PushEvent`
`unmarshalErr := json.Unmarshal(jsonBlob, &e)`

Could you help me?

**Comment by svanharmelen** [comment]
@mustafayildirim should be fixed by PR #97

**Comment by mustafayildirim** [comment]
Thanks @svanharmelen It's working now.
