### ISSUE TITLE
IssueCommentEvent should have labels field

### ISSUE THREAD

**Issue by hanzei** [xanzy/go-gitlab#973]
According to https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#comment-on-issue `IssueCommentEvent.Issue` should have a `labels` field.

**Comment by hanzei** [comment]
@svanharmelen Can you confirm that https://github.com/xanzy/go-gitlab/commit/3cea82bc256e0730d5ca504702ef9b2517daec0a actually solves this issue? From looking at the code it doesn't seem like.

**Comment by svanharmelen** [comment]
See my comments to that PR. It doesn’t solve anything and doesn’t change any code.

I must admit I’m puzzled why he wanted to update the JSON file without adding any logic and a new test using it.

So I can only assume (and hope) he is still working on those and that they will come in a separate PR 🤷🏻‍♂️

**Comment by svanharmelen** [comment]
FYI I didn’t close this manually, it was closed due to the reference in the PR.

**Comment by svanharmelen** [comment]
Check! Thanks for letting me know 👍🏻
